export const events = [
  {
    event_id: "AYon01ExAACHS4OW4em4Pn0s",
    "datadog.index": "rum",
    id: "AgAAAYon01Ex85KJvgAAAAAAAAAYAAAAAEFZb24wMUV4QUFDSFM0T1c0ZW00UG4wcwAAACQAAAAAMDE4YTI3ZDMtNTEzMS00NDE5LWExYzktYzNiZjIyY2I2Zjdk",
    event: {
      client_time: 1692885274473,
      random_draw: 0.7582989188029269,
      custom: {
        os: {
          name: "Mac OS X",
          version: "10.15.7",
          version_major: "10",
        },
        session: {
          ip: "103.163.91.139",
          useragent:
            "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36",
          id: "3d6e6af0-0727-4def-862c-7a02e6e4b2ce",
          has_replay: true,
          type: "user",
          plan: "replay",
        },
        display: {
          viewport: {
            width: 1680,
            height: 643,
          },
          scroll: {
            initial_fold_pct: 100,
            max_depth_time: 4148000000,
            max_depth_scroll_height: 643,
            max_depth: 643,
            max_depth_pct: 100,
            max_depth_scroll_top: 0,
          },
        },
        privacy: {
          replay_level: "mask-user-input",
        },
        type: "view",
        geo: {
          continent: "Asia",
          country: "India",
          as: {
            domain: "limericktechnologies.com",
            name: "Limerick Technologies Pvt. Ltd.",
            type: "isp",
          },
          country_iso_code: "IN",
          city: "Pimpri",
          latitude: 18.62292,
          continent_code: "AS",
          country_subdivision_iso_code: "IN-MH",
          location: [73.80696, 18.62292],
          country_subdivision: "Maharashtra",
          longitude: 73.80696,
        },
        view: {
          url_query: {
            org_identifier: "bhargav_organization_74",
          },
          load_event: 2437600000,
          long_task: {
            count: 2,
          },
          cumulative_layout_shift: 0,
          error: {
            count: 3,
          },
          dom_content_loaded: 1902600000,
          time_spent: 1070876000000,
          first_byte: 129200000,
          url_path_group: "/metrics",
          loading_time: 4148000000,
          action: {
            count: 0,
          },
          id: "ca74d86b-4346-46d4-8036-5d59460da872",
          url_host: "localhost",
          url_path: "/metrics",
          is_active: false,
          dom_interactive: 309100000,
          resource: {
            count: 273,
          },
          frustration: {
            count: 0,
          },
          dom_complete: 2437200000,
          url: "http://localhost:8081/metrics?org_identifier=bhargav_organization_74",
          url_scheme: "http",
          referrer:
            "http://localhost:8081/metrics?org_identifier=bhargav_organization_74",
          name: "/metrics",
          loading_type: "initial_load",
          url_port: 8081,
          referrer_url: {
            url_query: {
              org_identifier: "bhargav_organization_74",
            },
            url_port: 8081,
            url_host: "localhost",
            url_path: "/metrics",
            url_scheme: "http",
          },
        },
        application: {
          name: "Openobserve",
          id: "8ffa2388-4048-436b-b64a-a28f233eba22",
        },
        service: "openobserve",
        browser: {
          name: "Chrome",
          version: "114.0.0.0",
          version_major: "114",
        },
        context: {},
        device: {
          name: "Mac",
          model: "Mac",
          type: "Desktop",
          brand: "Apple",
        },
        _dd: {
          format_version: 2,
          configuration: {
            session_replay_sample_rate: 100,
            session_sample_rate: 100,
          },
          session: {
            plan: 2,
          },
          replay_stats: {
            records_count: 11,
            segments_count: 2,
            segments_total_raw_size: 914997,
          },
          origin: "reducer",
          lowercase_name: "/metrics",
          reducer_status: "closed",
          document_version: 15,
          drift: 1063888,
          migration_number: 1,
        },
      },
      end_time: 1692886345805,
      tiebreaker: -208500290,
      source: "browser",
      discovery_timestamp: 1692885274929,
      client_end_time: 1692886345349,
      tags: [
        "env:alpha1",
        "service:openobserve",
        "sdk_version:4.47.0",
        "source:browser",
        "api:xhr",
      ],
      update_time: 1692886575412,
      source_fragment_id: "018a27d3-5131-4419-a1c9-c3bf22cb6f7d",
      intake_time: 1692886575412,
      service: ["openobserve"],
      hashes: {
        view: {
          id: -8697713571277457000,
        },
        session: {
          id: 2467401570302887000,
        },
      },
      timeline: {
        token: "V3CBAwA",
      },
      metric_timestamp: 1692886345805,
      id: "AYon01ExAACHS4OW4em4Pn0s",
      tag: {
        service: "openobserve",
        sdk_version: "4.47.0",
        source: "browser",
        api: "xhr",
        env: "alpha1",
      },
      timestamp: "2023-08-24T13:54:34.929Z",
    },
  },
  {
    event_id: "AYonzLA6AABb4s4oN3ZEvgAF",
    "datadog.index": "rum",
    id: "AgAAAYonzD9yYE5y7gAAAAAAAAAYAAAAAEFZb256TEE2QUFCYjRzNG9OM1pFdmdBRgAAACQAAAAAMDE4YTI3ZDMtNjEyYy00YTEyLTlkZGQtMThiOTNkM2ZlMjhk",
    event: {
      client_time: 1692884811293,
      random_draw: 0.3045901108324043,
      custom: {
        os: {
          name: "Mac OS X",
          version: "10.15.7",
          version_major: "10",
        },
        session: {
          ip: "103.163.91.139",
          useragent:
            "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36",
          id: "3d6e6af0-0727-4def-862c-7a02e6e4b2ce",
          has_replay: true,
          type: "user",
          plan: "replay",
        },
        display: {
          viewport: {
            width: 1680,
            height: 643,
          },
        },
        error: {
          stack: "AxiosError: Request failed with status code 403",
          handling: "unhandled",
          source_type: "browser",
          id: "bdd2adc1-6caf-49a9-b936-e3815d1e757c",
          source: "source",
          message: "Request failed with status code 403",
          type: "AxiosError",
        },
        type: "error",
        geo: {
          continent: "Asia",
          country: "India",
          as: {
            domain: "limericktechnologies.com",
            name: "Limerick Technologies Pvt. Ltd.",
            type: "isp",
          },
          country_iso_code: "IN",
          city: "Pimpri",
          latitude: 18.62292,
          continent_code: "AS",
          country_subdivision_iso_code: "IN-MH",
          location: [73.80696, 18.62292],
          country_subdivision: "Maharashtra",
          longitude: 73.80696,
        },
        view: {
          referrer:
            "http://localhost:8081/traces?org_identifier=bhargav_organization_74",
          url_query: {
            org_identifier: "bhargav_organization_74",
          },
          in_foreground: true,
          url_path_group: "/metrics",
          name: "/metrics",
          id: "88478b71-e4d5-4122-9ddf-1123b69b5aaf",
          url_port: 8081,
          referrer_url: {
            url_query: {
              org_identifier: "bhargav_organization_74",
            },
            url_port: 8081,
            url_host: "localhost",
            url_scheme: "http",
            url_path: "/traces",
          },
          url: "http://localhost:8081/metrics?org_identifier=bhargav_organization_74",
          url_host: "localhost",
          url_scheme: "http",
          url_path: "/metrics",
        },
        application: {
          name: "Openobserve",
          id: "8ffa2388-4048-436b-b64a-a28f233eba22",
        },
        service: "openobserve",
        browser: {
          name: "Chrome",
          version: "114.0.0.0",
          version_major: "114",
        },
        device: {
          name: "Mac",
          model: "Mac",
          type: "Desktop",
          brand: "Apple",
        },
        _dd: {
          format_version: 2,
          configuration: {
            session_replay_sample_rate: 100,
            session_sample_rate: 100,
          },
          session: {
            plan: 2,
          },
          origin: "sdk",
          drift: 0,
        },
      },
      source: "browser",
      tiebreaker: 1615753966,
      discovery_timestamp: 1692884840506,
      tags: [
        "env:alpha1",
        "service:openobserve",
        "sdk_version:4.47.0",
        "source:browser",
        "api:fetch",
      ],
      ingest_size_in_bytes: 891,
      source_fragment_id: "018a27d3-612c-4a12-9ddd-18b93d3fe28d",
      intake_time: 1692884840506,
      service: "openobserve",
      hashes: {
        view: {
          id: -4424802500333962000,
        },
        session: {
          id: 2467401570302887000,
        },
      },
      id: "AYonzLA6AABb4s4oN3ZEvgAF",
      tag: {
        service: "openobserve",
        sdk_version: "4.47.0",
        source: "browser",
        api: "fetch",
        env: "alpha1",
      },
      timestamp: "2023-08-24T13:46:51.634Z",
    },
  },
  {
    event_id: "AYonzD8xAADCl_GRzlV83VQY",
    "datadog.index": "rum",
    id: "AgAAAYonzD8xvxBWQwAAAAAAAAAYAAAAAEFZb256RDh4QUFEQ2xfR1J6bFY4M1ZRWQAAACQAAAAAMDE4YTI3ZDMtNTEzMS00NDE5LWExYzktYzNiZjIyY2I2Zjdk",
    event: {
      client_time: 1692884811228,
      random_draw: 0.16964935003062342,
      custom: {
        os: {
          name: "Mac OS X",
          version: "10.15.7",
          version_major: "10",
        },
        session: {
          ip: "103.163.91.139",
          useragent:
            "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36",
          id: "3d6e6af0-0727-4def-862c-7a02e6e4b2ce",
          has_replay: true,
          type: "user",
          plan: "replay",
        },
        display: {
          viewport: {
            width: 1680,
            height: 643,
          },
          scroll: {
            initial_fold_pct: 100,
            max_depth_time: 90000000,
            max_depth_scroll_height: 643,
            max_depth: 643,
            max_depth_pct: 100,
            max_depth_scroll_top: 0,
          },
        },
        privacy: {
          replay_level: "mask-user-input",
        },
        type: "view",
        geo: {
          continent: "Asia",
          country: "India",
          as: {
            domain: "limericktechnologies.com",
            name: "Limerick Technologies Pvt. Ltd.",
            type: "isp",
          },
          country_iso_code: "IN",
          city: "Pimpri",
          latitude: 18.62292,
          continent_code: "AS",
          country_subdivision_iso_code: "IN-MH",
          location: [73.80696, 18.62292],
          country_subdivision: "Maharashtra",
          longitude: 73.80696,
        },
        view: {
          url_query: {
            org_identifier: "bhargav_organization_74",
          },
          is_active: false,
          in_foreground_periods: [
            {
              duration: 6613700000,
              start: 0,
            },
          ],
          resource: {
            count: 2,
          },
          frustration: {
            count: 0,
          },
          long_task: {
            count: 0,
          },
          cumulative_layout_shift: 0.0062,
          error: {
            count: 1,
          },
          url: "http://localhost:8081/metrics?org_identifier=bhargav_organization_74",
          url_scheme: "http",
          time_spent: 463210000000,
          referrer:
            "http://localhost:8081/traces?org_identifier=bhargav_organization_74",
          url_path_group: "/metrics",
          loading_time: 90000000,
          name: "/metrics",
          action: {
            count: 0,
          },
          loading_type: "route_change",
          id: "88478b71-e4d5-4122-9ddf-1123b69b5aaf",
          url_port: 8081,
          referrer_url: {
            url_query: {
              org_identifier: "bhargav_organization_74",
            },
            url_port: 8081,
            url_host: "localhost",
            url_path: "/traces",
            url_scheme: "http",
          },
          url_host: "localhost",
          url_path: "/metrics",
        },
        application: {
          name: "Openobserve",
          id: "8ffa2388-4048-436b-b64a-a28f233eba22",
        },
        service: "openobserve",
        browser: {
          name: "Chrome",
          version: "114.0.0.0",
          version_major: "114",
        },
        context: {},
        device: {
          name: "Mac",
          model: "Mac",
          type: "Desktop",
          brand: "Apple",
        },
        _dd: {
          format_version: 2,
          configuration: {
            session_replay_sample_rate: 100,
            session_sample_rate: 100,
          },
          session: {
            plan: 2,
          },
          replay_stats: {
            records_count: 37,
            segments_count: 4,
            segments_total_raw_size: 971893,
          },
          origin: "reducer",
          lowercase_name: "/metrics",
          reducer_status: "closed",
          document_version: 15,
          drift: -6,
          migration_number: 1,
        },
      },
      end_time: 1692885274779,
      tiebreaker: -1089448381,
      source: "browser",
      discovery_timestamp: 1692884811569,
      client_end_time: 1692885274438,
      tags: [
        "env:alpha1",
        "service:openobserve",
        "api:beacon",
        "sdk_version:4.47.0",
        "source:browser",
      ],
      update_time: 1692885275021,
      source_fragment_id: "018a27d3-5131-4419-a1c9-c3bf22cb6f7d",
      intake_time: 1692885275021,
      service: ["openobserve"],
      hashes: {
        view: {
          id: -4424802500333962000,
        },
        session: {
          id: 2467401570302887000,
        },
      },
      timeline: {
        token: "V3CBAwA",
      },
      metric_timestamp: 1692885274779,
      id: "AYonzD8xAADCl_GRzlV83VQY",
      tag: {
        service: "openobserve",
        sdk_version: "4.47.0",
        api: "beacon",
        source: "browser",
        env: "alpha1",
      },
      timestamp: "2023-08-24T13:46:51.569Z",
    },
  },
  {
    event_id: "AYonzDngAAAv8nX32Nv50Byb",
    "datadog.index": "rum",
    id: "AgAAAYonzDngpEbbjwAAAAAAAAAYAAAAAEFZb256RG5nQUFBdjhuWDMyTnY1MEJ5YgAAACQAAAAAMDE4YTI3ZDMtNTEzMS00NDE5LWExYzktYzNiZjIyY2I2Zjdk",
    event: {
      client_time: 1692884809842,
      random_draw: 0.8796321676978858,
      custom: {
        os: {
          name: "Mac OS X",
          version: "10.15.7",
          version_major: "10",
        },
        session: {
          ip: "103.163.91.139",
          useragent:
            "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36",
          id: "3d6e6af0-0727-4def-862c-7a02e6e4b2ce",
          has_replay: true,
          type: "user",
          plan: "replay",
        },
        display: {
          viewport: {
            width: 1680,
            height: 643,
          },
          scroll: {
            initial_fold_pct: 99,
            max_depth_time: 403000000,
            max_depth_scroll_height: 647,
            max_depth: 643,
            max_depth_pct: 99,
            max_depth_scroll_top: 0,
          },
        },
        privacy: {
          replay_level: "mask-user-input",
        },
        type: "view",
        geo: {
          continent: "Asia",
          country: "India",
          as: {
            domain: "limericktechnologies.com",
            name: "Limerick Technologies Pvt. Ltd.",
            type: "isp",
          },
          country_iso_code: "IN",
          city: "Pimpri",
          latitude: 18.62292,
          continent_code: "AS",
          country_subdivision_iso_code: "IN-MH",
          location: [73.80696, 18.62292],
          country_subdivision: "Maharashtra",
          longitude: 73.80696,
        },
        view: {
          url_query: {
            org_identifier: "bhargav_organization_74",
          },
          is_active: false,
          in_foreground_periods: [
            {
              duration: 1386000000,
              start: 0,
            },
          ],
          resource: {
            count: 3,
          },
          frustration: {
            count: 0,
          },
          long_task: {
            count: 1,
          },
          cumulative_layout_shift: 0.02,
          error: {
            count: 0,
          },
          url: "http://localhost:8081/traces?org_identifier=bhargav_organization_74",
          url_scheme: "http",
          time_spent: 1386000000,
          referrer:
            "http://localhost:8081/dashboards?org_identifier=bhargav_organization_74",
          url_path_group: "/traces",
          loading_time: 403000000,
          name: "/traces",
          action: {
            count: 0,
          },
          loading_type: "route_change",
          id: "5890806a-26f4-45bb-bf6c-ee63b4485fe6",
          url_port: 8081,
          referrer_url: {
            url_query: {
              org_identifier: "bhargav_organization_74",
            },
            url_port: 8081,
            url_host: "localhost",
            url_path: "/dashboards",
            url_scheme: "http",
          },
          url_host: "localhost",
          url_path: "/traces",
        },
        application: {
          name: "Openobserve",
          id: "8ffa2388-4048-436b-b64a-a28f233eba22",
        },
        service: "openobserve",
        browser: {
          name: "Chrome",
          version: "114.0.0.0",
          version_major: "114",
        },
        context: {},
        device: {
          name: "Mac",
          model: "Mac",
          type: "Desktop",
          brand: "Apple",
        },
        _dd: {
          format_version: 2,
          configuration: {
            session_replay_sample_rate: 100,
            session_sample_rate: 100,
          },
          session: {
            plan: 2,
          },
          replay_stats: {
            records_count: 28,
            segments_count: 2,
            segments_total_raw_size: 955966,
          },
          origin: "reducer",
          lowercase_name: "/traces",
          reducer_status: "closed",
          document_version: 14,
          drift: 0,
          migration_number: 1,
        },
      },
      end_time: 1692884811594,
      tiebreaker: -1538860145,
      source: "browser",
      discovery_timestamp: 1692884810208,
      client_end_time: 1692884811228,
      tags: [
        "env:alpha1",
        "service:openobserve",
        "sdk_version:4.47.0",
        "source:browser",
        "api:fetch",
      ],
      update_time: 1692884840506,
      source_fragment_id: "018a27d3-5131-4419-a1c9-c3bf22cb6f7d",
      intake_time: 1692884840506,
      service: ["openobserve"],
      hashes: {
        view: {
          id: 3454953571502258700,
        },
        session: {
          id: 2467401570302887000,
        },
      },
      timeline: {
        token: "VXhT2jQ",
      },
      metric_timestamp: 1692884811594,
      id: "AYonzDngAAAv8nX32Nv50Byb",
      tag: {
        service: "openobserve",
        sdk_version: "4.47.0",
        source: "browser",
        api: "fetch",
        env: "alpha1",
      },
      timestamp: "2023-08-24T13:46:50.208Z",
    },
  },
  {
    event_id: "AYonzDsZAADG2W-tsM2S-gAJ",
    "datadog.index": "rum",
    id: "AgAAAYonzDbtikopGQAAAAAAAAAYAAAAAEFZb256RHNaQUFERzJXLXRzTTJTLWdBSgAAACQAAAAAMDE4YTI3ZDMtNjEyYy00YTEyLTlkZGQtMThiOTNkM2ZlMjhk",
    event: {
      client_time: 1692884809087,
      random_draw: 0.3063644549293486,
      custom: {
        os: {
          name: "Mac OS X",
          version: "10.15.7",
          version_major: "10",
        },
        session: {
          ip: "103.163.91.139",
          useragent:
            "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36",
          id: "3d6e6af0-0727-4def-862c-7a02e6e4b2ce",
          has_replay: true,
          type: "user",
          plan: "replay",
        },
        display: {
          viewport: {
            width: 1680,
            height: 643,
          },
        },
        error: {
          stack: "AxiosError: Request failed with status code 403",
          handling: "handled",
          source_type: "browser",
          id: "5495076b-ed3d-40fb-a6b3-daf1bbf11160",
          source: "console",
          message:
            "console error: AxiosError: Request failed with status code 403",
          handling_stack:
            "Error: \n  at <anonymous> @ http://localhost:8081/src/views/Dashboards/Dashboards.vue:169:17\n  at async getDashboards @ http://localhost:8081/src/views/Dashboards/Dashboards.vue:157:7",
        },
        type: "error",
        geo: {
          continent: "Asia",
          country: "India",
          as: {
            domain: "limericktechnologies.com",
            name: "Limerick Technologies Pvt. Ltd.",
            type: "isp",
          },
          country_iso_code: "IN",
          city: "Pimpri",
          latitude: 18.62292,
          continent_code: "AS",
          country_subdivision_iso_code: "IN-MH",
          location: [73.80696, 18.62292],
          country_subdivision: "Maharashtra",
          longitude: 73.80696,
        },
        view: {
          referrer:
            "http://localhost:8081/functions/functions?org_identifier=bhargav_organization_74",
          url_query: {
            org_identifier: "bhargav_organization_74",
          },
          in_foreground: true,
          url_path_group: "/dashboards",
          name: "/dashboards",
          id: "8866f5a5-5889-4554-9053-1face673a245",
          url_port: 8081,
          referrer_url: {
            url_query: {
              org_identifier: "bhargav_organization_74",
            },
            url_port: 8081,
            url_host: "localhost",
            url_scheme: "http",
            url_path: "/functions/functions",
          },
          url: "http://localhost:8081/dashboards?org_identifier=bhargav_organization_74",
          url_host: "localhost",
          url_scheme: "http",
          url_path: "/dashboards",
        },
        application: {
          name: "Openobserve",
          id: "8ffa2388-4048-436b-b64a-a28f233eba22",
        },
        service: "openobserve",
        browser: {
          name: "Chrome",
          version: "114.0.0.0",
          version_major: "114",
        },
        device: {
          name: "Mac",
          model: "Mac",
          type: "Desktop",
          brand: "Apple",
        },
        _dd: {
          format_version: 2,
          configuration: {
            session_replay_sample_rate: 100,
            session_sample_rate: 100,
          },
          session: {
            plan: 2,
          },
          origin: "sdk",
          drift: 0,
        },
      },
      source: "browser",
      tiebreaker: -1974851303,
      discovery_timestamp: 1692884810521,
      tags: [
        "env:alpha1",
        "service:openobserve",
        "sdk_version:4.47.0",
        "source:browser",
        "api:fetch",
      ],
      ingest_size_in_bytes: 1117,
      source_fragment_id: "018a27d3-612c-4a12-9ddd-18b93d3fe28d",
      intake_time: 1692884810521,
      service: "openobserve",
      hashes: {
        view: {
          id: -1476873391101175600,
        },
        session: {
          id: 2467401570302887000,
        },
      },
      id: "AYonzDsZAADG2W-tsM2S-gAJ",
      tag: {
        service: "openobserve",
        sdk_version: "4.47.0",
        source: "browser",
        api: "fetch",
        env: "alpha1",
      },
      timestamp: "2023-08-24T13:46:49.453Z",
    },
  },
  {
    event_id: "AYonzDZdAADrgRd5wTAY84t2",
    "datadog.index": "rum",
    id: "AgAAAYonzDZd85IzcAAAAAAAAAAYAAAAAEFZb256RFpkQUFEcmdSZDV3VEFZODR0MgAAACQAAAAAMDE4YTI3ZDMtNTEzMS00NDE5LWExYzktYzNiZjIyY2I2Zjdk",
    event: {
      client_time: 1692884808943,
      random_draw: 0.2826036737730754,
      custom: {
        os: {
          name: "Mac OS X",
          version: "10.15.7",
          version_major: "10",
        },
        session: {
          ip: "103.163.91.139",
          useragent:
            "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36",
          id: "3d6e6af0-0727-4def-862c-7a02e6e4b2ce",
          has_replay: true,
          type: "user",
          plan: "replay",
        },
        display: {
          viewport: {
            width: 1680,
            height: 643,
          },
          scroll: {
            initial_fold_pct: 100,
            max_depth_time: 186000000,
            max_depth_scroll_height: 643,
            max_depth: 643,
            max_depth_pct: 100,
            max_depth_scroll_top: 0,
          },
        },
        privacy: {
          replay_level: "mask-user-input",
        },
        type: "view",
        geo: {
          continent: "Asia",
          country: "India",
          as: {
            domain: "limericktechnologies.com",
            name: "Limerick Technologies Pvt. Ltd.",
            type: "isp",
          },
          country_iso_code: "IN",
          city: "Pimpri",
          latitude: 18.62292,
          continent_code: "AS",
          country_subdivision_iso_code: "IN-MH",
          location: [73.80696, 18.62292],
          country_subdivision: "Maharashtra",
          longitude: 73.80696,
        },
        view: {
          url_query: {
            org_identifier: "bhargav_organization_74",
          },
          is_active: false,
          in_foreground_periods: [
            {
              duration: 899000000,
              start: 0,
            },
          ],
          resource: {
            count: 3,
          },
          frustration: {
            count: 0,
          },
          long_task: {
            count: 1,
          },
          cumulative_layout_shift: 0,
          error: {
            count: 1,
          },
          url: "http://localhost:8081/dashboards?org_identifier=bhargav_organization_74",
          url_scheme: "http",
          time_spent: 899000000,
          referrer:
            "http://localhost:8081/functions/functions?org_identifier=bhargav_organization_74",
          url_path_group: "/dashboards",
          loading_time: 186000000,
          name: "/dashboards",
          action: {
            count: 0,
          },
          loading_type: "route_change",
          id: "8866f5a5-5889-4554-9053-1face673a245",
          url_port: 8081,
          referrer_url: {
            url_query: {
              org_identifier: "bhargav_organization_74",
            },
            url_port: 8081,
            url_host: "localhost",
            url_path: "/functions/functions",
            url_scheme: "http",
          },
          url_host: "localhost",
          url_path: "/dashboards",
        },
        application: {
          name: "Openobserve",
          id: "8ffa2388-4048-436b-b64a-a28f233eba22",
        },
        service: "openobserve",
        browser: {
          name: "Chrome",
          version: "114.0.0.0",
          version_major: "114",
        },
        context: {},
        device: {
          name: "Mac",
          model: "Mac",
          type: "Desktop",
          brand: "Apple",
        },
        _dd: {
          format_version: 2,
          configuration: {
            session_replay_sample_rate: 100,
            session_sample_rate: 100,
          },
          session: {
            plan: 2,
          },
          replay_stats: {
            records_count: 21,
            segments_count: 2,
            segments_total_raw_size: 870136,
          },
          origin: "reducer",
          lowercase_name: "/dashboards",
          reducer_status: "closed",
          document_version: 14,
          drift: 0,
          migration_number: 1,
        },
      },
      end_time: 1692884810208,
      tiebreaker: -208522384,
      source: "browser",
      discovery_timestamp: 1692884809309,
      client_end_time: 1692884809842,
      tags: [
        "env:alpha1",
        "service:openobserve",
        "sdk_version:4.47.0",
        "source:browser",
        "api:fetch",
      ],
      update_time: 1692884840506,
      source_fragment_id: "018a27d3-5131-4419-a1c9-c3bf22cb6f7d",
      intake_time: 1692884840506,
      service: ["openobserve"],
      hashes: {
        view: {
          id: -1476873391101175600,
        },
        session: {
          id: 2467401570302887000,
        },
      },
      timeline: {
        token: "VswTgVA",
      },
      metric_timestamp: 1692884810208,
      id: "AYonzDZdAADrgRd5wTAY84t2",
      tag: {
        service: "openobserve",
        sdk_version: "4.47.0",
        source: "browser",
        api: "fetch",
        env: "alpha1",
      },
      timestamp: "2023-08-24T13:46:49.309Z",
    },
  },
  {
    event_id: "AYonzDJ4AAD6uHk5ztAUVtQ7",
    "datadog.index": "rum",
    id: "AgAAAYonzDJ4pEbbAgAAAAAAAAAYAAAAAEFZb256REo0QUFENnVIazV6dEFVVnRRNwAAACQAAAAAMDE4YTI3ZDMtNTEzMS00NDE5LWExYzktYzNiZjIyY2I2Zjdk",
    event: {
      client_time: 1692884807969,
      random_draw: 0.3015142990303037,
      custom: {
        os: {
          name: "Mac OS X",
          version: "10.15.7",
          version_major: "10",
        },
        session: {
          ip: "103.163.91.139",
          useragent:
            "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36",
          id: "3d6e6af0-0727-4def-862c-7a02e6e4b2ce",
          has_replay: true,
          type: "user",
          plan: "replay",
        },
        display: {
          viewport: {
            width: 1680,
            height: 643,
          },
          scroll: {
            initial_fold_pct: 100,
            max_depth_time: 494000000,
            max_depth_scroll_height: 646,
            max_depth: 643,
            max_depth_pct: 100,
            max_depth_scroll_top: 0,
          },
        },
        privacy: {
          replay_level: "mask-user-input",
        },
        type: "view",
        geo: {
          continent: "Asia",
          country: "India",
          as: {
            domain: "limericktechnologies.com",
            name: "Limerick Technologies Pvt. Ltd.",
            type: "isp",
          },
          country_iso_code: "IN",
          city: "Pimpri",
          latitude: 18.62292,
          continent_code: "AS",
          country_subdivision_iso_code: "IN-MH",
          location: [73.80696, 18.62292],
          country_subdivision: "Maharashtra",
          longitude: 73.80696,
        },
        view: {
          url_query: {
            org_identifier: "bhargav_organization_74",
          },
          is_active: false,
          in_foreground_periods: [
            {
              duration: 973000000,
              start: 0,
            },
          ],
          resource: {
            count: 5,
          },
          frustration: {
            count: 0,
          },
          long_task: {
            count: 2,
          },
          cumulative_layout_shift: 0.0068,
          error: {
            count: 0,
          },
          url: "http://localhost:8081/functions/functions?org_identifier=bhargav_organization_74",
          url_scheme: "http",
          time_spent: 973000000,
          referrer:
            "http://localhost:8081/functions?org_identifier=bhargav_organization_74",
          url_path_group: "/functions/functions",
          loading_time: 494000000,
          name: "/functions/functions",
          action: {
            count: 0,
          },
          loading_type: "route_change",
          id: "dbd1dbdb-328b-472f-b468-74832e8a86e2",
          url_port: 8081,
          referrer_url: {
            url_query: {
              org_identifier: "bhargav_organization_74",
            },
            url_port: 8081,
            url_host: "localhost",
            url_path: "/functions",
            url_scheme: "http",
          },
          url_host: "localhost",
          url_path: "/functions/functions",
        },
        application: {
          name: "Openobserve",
          id: "8ffa2388-4048-436b-b64a-a28f233eba22",
        },
        service: "openobserve",
        browser: {
          name: "Chrome",
          version: "114.0.0.0",
          version_major: "114",
        },
        context: {},
        device: {
          name: "Mac",
          model: "Mac",
          type: "Desktop",
          brand: "Apple",
        },
        _dd: {
          format_version: 2,
          configuration: {
            session_replay_sample_rate: 100,
            session_sample_rate: 100,
          },
          session: {
            plan: 2,
          },
          replay_stats: {
            records_count: 21,
            segments_count: 2,
            segments_total_raw_size: 863085,
          },
          origin: "reducer",
          lowercase_name: "/functions/functions",
          reducer_status: "closed",
          document_version: 14,
          drift: -1,
          migration_number: 1,
        },
      },
      end_time: 1692884809285,
      tiebreaker: -1538860286,
      source: "browser",
      discovery_timestamp: 1692884808312,
      client_end_time: 1692884808942,
      tags: [
        "env:alpha1",
        "service:openobserve",
        "sdk_version:4.47.0",
        "source:browser",
        "api:fetch",
      ],
      update_time: 1692884810521,
      source_fragment_id: "018a27d3-5131-4419-a1c9-c3bf22cb6f7d",
      intake_time: 1692884810521,
      service: ["openobserve"],
      hashes: {
        view: {
          id: -380420879322967000,
        },
        session: {
          id: 2467401570302887000,
        },
      },
      timeline: {
        token: "VhVt_og",
      },
      metric_timestamp: 1692884809285,
      id: "AYonzDJ4AAD6uHk5ztAUVtQ7",
      tag: {
        service: "openobserve",
        sdk_version: "4.47.0",
        source: "browser",
        api: "fetch",
        env: "alpha1",
      },
      timestamp: "2023-08-24T13:46:48.312Z",
    },
  },
  {
    event_id: "AYonzDE1AABxiOHjYO8lffKD",
    "datadog.index": "rum",
    id: "AgAAAYonzDE1pEbbBwAAAAAAAAAYAAAAAEFZb256REUxQUFCeGlPSGpZTzhsZmZLRAAAACQAAAAAMDE4YTI3ZDMtNTEzMS00NDE5LWExYzktYzNiZjIyY2I2Zjdk",
    event: {
      client_time: 1692884807646,
      random_draw: 0.9786737313445124,
      custom: {
        os: {
          name: "Mac OS X",
          version: "10.15.7",
          version_major: "10",
        },
        session: {
          ip: "103.163.91.139",
          useragent:
            "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36",
          id: "3d6e6af0-0727-4def-862c-7a02e6e4b2ce",
          has_replay: true,
          type: "user",
          plan: "replay",
        },
        display: {
          viewport: {
            width: 1680,
            height: 643,
          },
          scroll: {
            initial_fold_pct: 100,
            max_depth_time: 61000000,
            max_depth_scroll_height: 643,
            max_depth: 643,
            max_depth_pct: 100,
            max_depth_scroll_top: 0,
          },
        },
        privacy: {
          replay_level: "mask-user-input",
        },
        type: "view",
        geo: {
          continent: "Asia",
          country: "India",
          as: {
            domain: "limericktechnologies.com",
            name: "Limerick Technologies Pvt. Ltd.",
            type: "isp",
          },
          country_iso_code: "IN",
          city: "Pimpri",
          latitude: 18.62292,
          continent_code: "AS",
          country_subdivision_iso_code: "IN-MH",
          location: [73.80696, 18.62292],
          country_subdivision: "Maharashtra",
          longitude: 73.80696,
        },
        view: {
          url_query: {
            org_identifier: "bhargav_organization_74",
          },
          is_active: false,
          in_foreground_periods: [
            {
              duration: 322000000,
              start: 0,
            },
          ],
          resource: {
            count: 5,
          },
          frustration: {
            count: 0,
          },
          long_task: {
            count: 1,
          },
          cumulative_layout_shift: 0,
          error: {
            count: 0,
          },
          url: "http://localhost:8081/functions?org_identifier=bhargav_organization_74",
          url_scheme: "http",
          time_spent: 322000000,
          referrer: "http://localhost:8081/",
          url_path_group: "/functions",
          loading_time: 61000000,
          name: "/functions",
          action: {
            count: 0,
          },
          loading_type: "route_change",
          id: "ea0ed042-77ff-4af8-a12e-32f054967121",
          url_port: 8081,
          referrer_url: {
            url_port: 8081,
            url_host: "localhost",
            url_path: "/",
            url_scheme: "http",
          },
          url_host: "localhost",
          url_path: "/functions",
        },
        application: {
          name: "Openobserve",
          id: "8ffa2388-4048-436b-b64a-a28f233eba22",
        },
        service: "openobserve",
        browser: {
          name: "Chrome",
          version: "114.0.0.0",
          version_major: "114",
        },
        context: {},
        device: {
          name: "Mac",
          model: "Mac",
          type: "Desktop",
          brand: "Apple",
        },
        _dd: {
          format_version: 2,
          configuration: {
            session_replay_sample_rate: 100,
            session_sample_rate: 100,
          },
          session: {
            plan: 2,
          },
          replay_stats: {
            records_count: 8,
            segments_count: 2,
            segments_total_raw_size: 853173,
          },
          origin: "reducer",
          lowercase_name: "/functions",
          reducer_status: "closed",
          document_version: 14,
          drift: -1,
          migration_number: 1,
        },
      },
      end_time: 1692884808311,
      tiebreaker: -1538860281,
      source: "browser",
      discovery_timestamp: 1692884807989,
      client_end_time: 1692884807968,
      tags: [
        "env:alpha1",
        "service:openobserve",
        "sdk_version:4.47.0",
        "source:browser",
        "api:fetch",
      ],
      update_time: 1692884840506,
      source_fragment_id: "018a27d3-5131-4419-a1c9-c3bf22cb6f7d",
      intake_time: 1692884840506,
      service: ["openobserve"],
      hashes: {
        view: {
          id: 8181037089818617000,
        },
        session: {
          id: 2467401570302887000,
        },
      },
      timeline: {
        token: "VZrNRyg",
      },
      metric_timestamp: 1692884808311,
      id: "AYonzDE1AABxiOHjYO8lffKD",
      tag: {
        service: "openobserve",
        sdk_version: "4.47.0",
        source: "browser",
        api: "fetch",
        env: "alpha1",
      },
      timestamp: "2023-08-24T13:46:47.989Z",
    },
  },
  {
    event_id: "AYonzB6oAADG2W-tsM2CRQAO",
    "datadog.index": "rum",
    id: "AgAAAYonzB6EeZUpHgAAAAAAAAAYAAAAAEFZb256QjZvQUFERzJXLXRzTTJDUlFBTwAAACQAAAAAMDE4YTI3ZDMtNjEyYy00YTEyLTlkZGQtMThiOTNkM2ZlMjhk",
    event: {
      client_time: 1692884802873,
      random_draw: 0.521284519805033,
      custom: {
        os: {
          name: "Mac OS X",
          version: "10.15.7",
          version_major: "10",
        },
        session: {
          ip: "103.163.91.139",
          useragent:
            "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36",
          id: "3d6e6af0-0727-4def-862c-7a02e6e4b2ce",
          has_replay: true,
          type: "user",
          plan: "replay",
        },
        display: {
          viewport: {
            width: 1680,
            height: 643,
          },
        },
        error: {
          stack: "No stack, consider using an instance of Error",
          handling: "unhandled",
          source_type: "browser",
          id: "f6f974e1-5a63-4c15-ac08-cf78226152c8",
          source: "source",
          message:
            'Uncaught "Browser doesn\'t support required api, or doNotTrack is active."',
        },
        type: "error",
        geo: {
          continent: "Asia",
          country: "India",
          as: {
            domain: "limericktechnologies.com",
            name: "Limerick Technologies Pvt. Ltd.",
            type: "isp",
          },
          country_iso_code: "IN",
          city: "Pimpri",
          latitude: 18.62292,
          continent_code: "AS",
          country_subdivision_iso_code: "IN-MH",
          location: [73.80696, 18.62292],
          country_subdivision: "Maharashtra",
          longitude: 73.80696,
        },
        view: {
          referrer: "http://localhost:8081/cb",
          in_foreground: true,
          url_path_group: "/",
          name: "/",
          id: "e029e437-4216-48c0-8f53-3d2138d0c9a4",
          url_port: 8081,
          referrer_url: {
            url_port: 8081,
            url_host: "localhost",
            url_scheme: "http",
            url_path: "/cb",
          },
          url: "http://localhost:8081/",
          url_host: "localhost",
          url_scheme: "http",
          url_path: "/",
        },
        application: {
          name: "Openobserve",
          id: "8ffa2388-4048-436b-b64a-a28f233eba22",
        },
        service: "openobserve",
        browser: {
          name: "Chrome",
          version: "114.0.0.0",
          version_major: "114",
        },
        device: {
          name: "Mac",
          model: "Mac",
          type: "Desktop",
          brand: "Apple",
        },
        _dd: {
          format_version: 2,
          configuration: {
            session_replay_sample_rate: 100,
            session_sample_rate: 100,
          },
          session: {
            plan: 2,
          },
          origin: "sdk",
          drift: 0,
        },
      },
      source: "browser",
      tiebreaker: 2039818526,
      discovery_timestamp: 1692884803240,
      tags: [
        "env:alpha1",
        "service:openobserve",
        "sdk_version:4.47.0",
        "source:browser",
        "api:fetch",
      ],
      ingest_size_in_bytes: 820,
      source_fragment_id: "018a27d3-612c-4a12-9ddd-18b93d3fe28d",
      intake_time: 1692884803240,
      service: "openobserve",
      hashes: {
        view: {
          id: 8705634528655405000,
        },
        session: {
          id: 2467401570302887000,
        },
      },
      id: "AYonzB6oAADG2W-tsM2CRQAO",
      tag: {
        service: "openobserve",
        sdk_version: "4.47.0",
        source: "browser",
        api: "fetch",
        env: "alpha1",
      },
      timestamp: "2023-08-24T13:46:43.204Z",
    },
  },
  {
    event_id: "AYonzB6oAADG2W-tsM2CRQAN",
    "datadog.index": "rum",
    id: "AgAAAYonzB26eZUpHQAAAAAAAAAYAAAAAEFZb256QjZvQUFERzJXLXRzTTJDUlFBTgAAACQAAAAAMDE4YTI3ZDMtNjEyYy00YTEyLTlkZGQtMThiOTNkM2ZlMjhk",
    event: {
      client_time: 1692884802671,
      random_draw: 0.994936090462369,
      custom: {
        os: {
          name: "Mac OS X",
          version: "10.15.7",
          version_major: "10",
        },
        session: {
          ip: "103.163.91.139",
          useragent:
            "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36",
          id: "3d6e6af0-0727-4def-862c-7a02e6e4b2ce",
          has_replay: true,
          type: "user",
          plan: "replay",
        },
        display: {
          viewport: {
            width: 1680,
            height: 643,
          },
        },
        error: {
          handling: "handled",
          source_type: "browser",
          id: "d91f5f54-4b89-47d8-bfea-3c85bcb77ce0",
          source: "console",
          message:
            "console error: OpenReplay: Your website must be publicly accessible and running on SSL in order for OpenReplay to properly capture and replay the user session. You can disable this check by setting `__DISABLE_SECURE_MODE` option to `true` if you are testing in localhost. Keep in mind, that asset files on a local machine are not available to the outside world. This might affect tracking if you use css files.",
          handling_stack:
            "Error: \n  at new API @ http://localhost:8081/node_modules/.vite/deps/@openreplay_tracker.js?v=62ecd837:3353:15\n  at setup @ http://localhost:8081/src/layouts/MainLayout.vue:341:23\n  at callWithErrorHandling @ http://localhost:8081/node_modules/.vite/deps/chunk-GYDGIFSZ.js?v=62ecd837:1560:18\n  at setupStatefulComponent @ http://localhost:8081/node_modules/.vite/deps/chunk-GYDGIFSZ.js?v=62ecd837:6168:25\n  at setupComponent @ http://localhost:8081/node_modules/.vite/deps/chunk-GYDGIFSZ.js?v=62ecd837:6131:36\n  at mountComponent @ http://localhost:8081/node_modules/.vite/deps/chunk-GYDGIFSZ.js?v=62ecd837:5056:7\n  at processComponent @ http://localhost:8081/node_modules/.vite/deps/chunk-GYDGIFSZ.js?v=62ecd837:5034:9\n  at patch @ http://localhost:8081/node_modules/.vite/deps/chunk-GYDGIFSZ.js?v=62ecd837:4752:11",
        },
        type: "error",
        geo: {
          continent: "Asia",
          country: "India",
          as: {
            domain: "limericktechnologies.com",
            name: "Limerick Technologies Pvt. Ltd.",
            type: "isp",
          },
          country_iso_code: "IN",
          city: "Pimpri",
          latitude: 18.62292,
          continent_code: "AS",
          country_subdivision_iso_code: "IN-MH",
          location: [73.80696, 18.62292],
          country_subdivision: "Maharashtra",
          longitude: 73.80696,
        },
        view: {
          referrer: "http://localhost:8081/cb",
          in_foreground: true,
          url_path_group: "/",
          name: "/",
          id: "e029e437-4216-48c0-8f53-3d2138d0c9a4",
          url_port: 8081,
          referrer_url: {
            url_port: 8081,
            url_host: "localhost",
            url_scheme: "http",
            url_path: "/cb",
          },
          url: "http://localhost:8081/",
          url_host: "localhost",
          url_scheme: "http",
          url_path: "/",
        },
        application: {
          name: "Openobserve",
          id: "8ffa2388-4048-436b-b64a-a28f233eba22",
        },
        service: "openobserve",
        browser: {
          name: "Chrome",
          version: "114.0.0.0",
          version_major: "114",
        },
        device: {
          name: "Mac",
          model: "Mac",
          type: "Desktop",
          brand: "Apple",
        },
        _dd: {
          format_version: 2,
          configuration: {
            session_replay_sample_rate: 100,
            session_sample_rate: 100,
          },
          session: {
            plan: 2,
          },
          origin: "sdk",
          drift: 0,
        },
      },
      source: "browser",
      tiebreaker: 2039818525,
      discovery_timestamp: 1692884803240,
      tags: [
        "env:alpha1",
        "service:openobserve",
        "sdk_version:4.47.0",
        "source:browser",
        "api:fetch",
      ],
      ingest_size_in_bytes: 1941,
      source_fragment_id: "018a27d3-612c-4a12-9ddd-18b93d3fe28d",
      intake_time: 1692884803240,
      service: "openobserve",
      hashes: {
        view: {
          id: 8705634528655405000,
        },
        session: {
          id: 2467401570302887000,
        },
      },
      id: "AYonzB6oAADG2W-tsM2CRQAN",
      tag: {
        service: "openobserve",
        sdk_version: "4.47.0",
        source: "browser",
        api: "fetch",
        env: "alpha1",
      },
      timestamp: "2023-08-24T13:46:43.002Z",
    },
  },
  {
    event_id: "AYonzBX5AAB40KB6uOFwpCxi",
    "datadog.index": "rum",
    id: "AgAAAYonzBX5wVASewAAAAAAAAAYAAAAAEFZb256Qlg1QUFCNDBLQjZ1T0Z3cEN4aQAAACQAAAAAMDE4YTI3ZDMtNTEzMS00NDE5LWExYzktYzNiZjIyY2I2Zjdk",
    event: {
      client_time: 1692884800678,
      random_draw: 0.058897868127349096,
      custom: {
        os: {
          name: "Mac OS X",
          version: "10.15.7",
          version_major: "10",
        },
        session: {
          ip: "103.163.91.139",
          useragent:
            "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36",
          id: "3d6e6af0-0727-4def-862c-7a02e6e4b2ce",
          has_replay: true,
          type: "user",
          plan: "replay",
        },
        display: {
          viewport: {
            width: 1680,
            height: 643,
          },
          scroll: {
            initial_fold_pct: 100,
            max_depth_time: 2820000000,
            max_depth_scroll_height: 643,
            max_depth: 643,
            max_depth_pct: 100,
            max_depth_scroll_top: 0,
          },
        },
        privacy: {
          replay_level: "mask-user-input",
        },
        type: "view",
        geo: {
          continent: "Asia",
          country: "India",
          as: {
            domain: "limericktechnologies.com",
            name: "Limerick Technologies Pvt. Ltd.",
            type: "isp",
          },
          country_iso_code: "IN",
          city: "Pimpri",
          latitude: 18.62292,
          continent_code: "AS",
          country_subdivision_iso_code: "IN-MH",
          location: [73.80696, 18.62292],
          country_subdivision: "Maharashtra",
          longitude: 73.80696,
        },
        view: {
          first_input_delay: 3500000,
          load_event: 1750700000,
          long_task: {
            count: 2,
          },
          cumulative_layout_shift: 0,
          error: {
            count: 2,
          },
          dom_content_loaded: 1373500000,
          time_spent: 6966000000,
          first_input_time: 6111000000,
          first_contentful_paint: 2184400000,
          first_byte: 20900000,
          url_path_group: "/",
          loading_time: 2820000000,
          action: {
            count: 0,
          },
          id: "e029e437-4216-48c0-8f53-3d2138d0c9a4",
          url_host: "localhost",
          url_path: "/",
          is_active: false,
          in_foreground_periods: [
            {
              duration: 5620400000,
              start: 1345600000,
            },
          ],
          dom_interactive: 168200000,
          resource: {
            count: 273,
          },
          frustration: {
            count: 0,
          },
          largest_contentful_paint: 2241600000,
          dom_complete: 1750400000,
          url: "http://localhost:8081/",
          url_scheme: "http",
          referrer: "http://localhost:8081/cb",
          name: "/",
          loading_type: "initial_load",
          url_port: 8081,
          referrer_url: {
            url_port: 8081,
            url_host: "localhost",
            url_path: "/cb",
            url_scheme: "http",
          },
        },
        application: {
          name: "Openobserve",
          id: "8ffa2388-4048-436b-b64a-a28f233eba22",
        },
        service: "openobserve",
        browser: {
          name: "Chrome",
          version: "114.0.0.0",
          version_major: "114",
        },
        context: {},
        device: {
          name: "Mac",
          model: "Mac",
          type: "Desktop",
          brand: "Apple",
        },
        _dd: {
          format_version: 2,
          configuration: {
            session_replay_sample_rate: 100,
            session_sample_rate: 100,
          },
          session: {
            plan: 2,
          },
          replay_stats: {
            records_count: 43,
            segments_count: 2,
            segments_total_raw_size: 854138,
          },
          origin: "reducer",
          lowercase_name: "/",
          reducer_status: "closed",
          document_version: 14,
          drift: 0,
          migration_number: 1,
        },
      },
      end_time: 1692884807983,
      tiebreaker: -1051716997,
      source: "browser",
      discovery_timestamp: 1692884801017,
      client_end_time: 1692884807644,
      tags: [
        "env:alpha1",
        "service:openobserve",
        "sdk_version:4.47.0",
        "source:browser",
        "api:fetch",
      ],
      update_time: 1692884808431,
      source_fragment_id: "018a27d3-5131-4419-a1c9-c3bf22cb6f7d",
      intake_time: 1692884808431,
      service: ["openobserve"],
      hashes: {
        view: {
          id: 8705634528655405000,
        },
        session: {
          id: 2467401570302887000,
        },
      },
      timeline: {
        token: "VSmteTw",
      },
      metric_timestamp: 1692884807983,
      id: "AYonzBX5AAB40KB6uOFwpCxi",
      tag: {
        service: "openobserve",
        sdk_version: "4.47.0",
        source: "browser",
        api: "fetch",
        env: "alpha1",
      },
      timestamp: "2023-08-24T13:46:41.017Z",
    },
  },
  {
    event_id: "AYony8kvAAA80wkQygk3owAJ",
    "datadog.index": "rum",
    id: "AgAAAYony8RxtndoUwAAAAAAAAAYAAAAAEFZb255OGt2QUFBODB3a1F5Z2szb3dBSgAAACQAAAAAMDE4YTI3ZDMtNjEyYy00YTEyLTlkZGQtMThiOTNkM2ZlMjhk",
    event: {
      client_time: 1692884779786,
      random_draw: 0.9344650172817827,
      custom: {
        os: {
          name: "Mac OS X",
          version: "10.15.7",
          version_major: "10",
        },
        session: {
          ip: "103.163.91.139",
          useragent:
            "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36",
          id: "3d6e6af0-0727-4def-862c-7a02e6e4b2ce",
          has_replay: true,
          type: "user",
          plan: "replay",
        },
        display: {
          viewport: {
            width: 1680,
            height: 643,
          },
        },
        type: "action",
        geo: {
          continent: "Asia",
          country: "India",
          as: {
            domain: "limericktechnologies.com",
            name: "Limerick Technologies Pvt. Ltd.",
            type: "isp",
          },
          country_iso_code: "IN",
          city: "Pimpri",
          latitude: 18.62292,
          continent_code: "AS",
          country_subdivision_iso_code: "IN-MH",
          location: [73.80696, 18.62292],
          country_subdivision: "Maharashtra",
          longitude: 73.80696,
        },
        view: {
          referrer: "http://localhost:8081/",
          in_foreground: true,
          url_path_group: "/",
          name: "/",
          id: "5aee9026-8bbf-491a-b26e-4b32f737c089",
          url_port: 8081,
          referrer_url: {
            url_port: 8081,
            url_host: "localhost",
            url_scheme: "http",
            url_path: "/",
          },
          url: "http://localhost:8081/",
          url_host: "localhost",
          url_scheme: "http",
          url_path: "/",
        },
        application: {
          name: "Openobserve",
          id: "8ffa2388-4048-436b-b64a-a28f233eba22",
        },
        service: "openobserve",
        browser: {
          name: "Chrome",
          version: "114.0.0.0",
          version_major: "114",
        },
        action: {
          resource: {
            count: 0,
          },
          loading_time: 54000000,
          name: "click on Bhargav Patel arrow_drop_down",
          long_task: {
            count: 0,
          },
          id: "bf120b2f-f1b6-4855-9e16-2dc10d7e9a30",
          type: "click",
          error: {
            count: 0,
          },
          target: {
            name: "Bhargav Patel arrow_drop_down",
          },
        },
        device: {
          name: "Mac",
          model: "Mac",
          type: "Desktop",
          brand: "Apple",
        },
        _dd: {
          format_version: 2,
          configuration: {
            session_replay_sample_rate: 100,
            session_sample_rate: 100,
          },
          session: {
            plan: 2,
          },
          origin: "sdk",
          action: {
            position: {
              x: 101,
              y: 0,
              ratio: {
                grid10x: 656,
                grid10y: 125,
                x: 656,
                y: 0,
              },
            },
            target: {
              width: 154,
              selector:
                "#app>DIV.q-layout>HEADER.q-header>DIV.q-toolbar>DIV.q-mr-xs>BUTTON.q-btn>SPAN.q-btn__content>DIV.row",
              height: 32,
            },
          },
          lowercase_name: "click on bhargav patel arrow_drop_down",
          drift: 0,
        },
      },
      end_time: 1692884780199,
      source: "browser",
      tiebreaker: -1233688493,
      discovery_timestamp: 1692884781359,
      tags: [
        "env:alpha1",
        "service:openobserve",
        "api:beacon",
        "sdk_version:4.47.0",
        "source:browser",
      ],
      client_end_time: 1692884779840,
      ingest_size_in_bytes: 980,
      source_fragment_id: "018a27d3-612c-4a12-9ddd-18b93d3fe28d",
      intake_time: 1692884781359,
      service: "openobserve",
      hashes: {
        view: {
          id: 4889299009760955000,
        },
        session: {
          id: 2467401570302887000,
        },
      },
      timeline: {
        token: "ALJ-7zQ",
      },
      id: "AYony8kvAAA80wkQygk3owAJ",
      tag: {
        service: "openobserve",
        sdk_version: "4.47.0",
        api: "beacon",
        source: "browser",
        env: "alpha1",
      },
      timestamp: "2023-08-24T13:46:20.145Z",
    },
  },
  {
    event_id: "AYony5tNAABD2keLdXiNPvea",
    "datadog.index": "rum",
    id: "AgAAAYony5tNpEbVxQAAAAAAAAAYAAAAAEFZb255NXROQUFCRDJrZUxkWGlOUHZlYQAAACQAAAAAMDE4YTI3ZDMtNTEzMS00NDE5LWExYzktYzNiZjIyY2I2Zjdk",
    event: {
      client_time: 1692884769273,
      random_draw: 0.7723210206696562,
      custom: {
        os: {
          name: "Mac OS X",
          version: "10.15.7",
          version_major: "10",
        },
        session: {
          ip: "103.163.91.139",
          useragent:
            "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36",
          id: "3d6e6af0-0727-4def-862c-7a02e6e4b2ce",
          has_replay: true,
          type: "user",
          plan: "replay",
        },
        display: {
          viewport: {
            width: 1680,
            height: 643,
          },
          scroll: {
            initial_fold_pct: 100,
            max_depth_time: 8742000000,
            max_depth_scroll_height: 643,
            max_depth: 643,
            max_depth_pct: 100,
            max_depth_scroll_top: 0,
          },
        },
        privacy: {
          replay_level: "mask-user-input",
        },
        type: "view",
        geo: {
          continent: "Asia",
          country: "India",
          as: {
            domain: "limericktechnologies.com",
            name: "Limerick Technologies Pvt. Ltd.",
            type: "isp",
          },
          country_iso_code: "IN",
          city: "Pimpri",
          latitude: 18.62292,
          continent_code: "AS",
          country_subdivision_iso_code: "IN-MH",
          location: [73.80696, 18.62292],
          country_subdivision: "Maharashtra",
          longitude: 73.80696,
        },
        view: {
          first_input_delay: 7700000,
          load_event: 7624300000,
          long_task: {
            count: 1,
          },
          cumulative_layout_shift: 0,
          error: {
            count: 2,
          },
          dom_content_loaded: 7230600000,
          time_spent: 11726000000,
          first_input_time: 10500600000,
          first_contentful_paint: 8060600000,
          first_byte: 27800000,
          url_path_group: "/",
          loading_time: 8742000000,
          action: {
            count: 1,
          },
          id: "5aee9026-8bbf-491a-b26e-4b32f737c089",
          url_host: "localhost",
          url_path: "/",
          is_active: false,
          in_foreground_periods: [
            {
              duration: 1219400000,
              start: 10506600000,
            },
          ],
          dom_interactive: 158200000,
          resource: {
            count: 289,
          },
          frustration: {
            count: 0,
          },
          largest_contentful_paint: 8113000000,
          dom_complete: 7624100000,
          url: "http://localhost:8081/",
          url_scheme: "http",
          referrer: "http://localhost:8081/",
          name: "/",
          loading_type: "initial_load",
          url_port: 8081,
          referrer_url: {
            url_port: 8081,
            url_host: "localhost",
            url_path: "/",
            url_scheme: "http",
          },
        },
        application: {
          name: "Openobserve",
          id: "8ffa2388-4048-436b-b64a-a28f233eba22",
        },
        service: "openobserve",
        browser: {
          name: "Chrome",
          version: "114.0.0.0",
          version_major: "114",
        },
        context: {},
        device: {
          name: "Mac",
          model: "Mac",
          type: "Desktop",
          brand: "Apple",
        },
        _dd: {
          format_version: 2,
          configuration: {
            session_replay_sample_rate: 100,
            session_sample_rate: 100,
          },
          session: {
            plan: 2,
          },
          replay_stats: {
            records_count: 56,
            segments_count: 2,
            segments_total_raw_size: 855849,
          },
          origin: "reducer",
          lowercase_name: "/",
          reducer_status: "closed",
          document_version: 14,
          drift: -1,
          migration_number: 1,
        },
      },
      end_time: 1692884781339,
      tiebreaker: -1538861627,
      source: "browser",
      discovery_timestamp: 1692884769613,
      client_end_time: 1692884780999,
      tags: [
        "env:alpha1",
        "service:openobserve",
        "api:beacon",
        "sdk_version:4.47.0",
        "source:browser",
      ],
      update_time: 1692884781359,
      source_fragment_id: "018a27d3-5131-4419-a1c9-c3bf22cb6f7d",
      intake_time: 1692884781359,
      service: ["openobserve"],
      hashes: {
        view: {
          id: 4889299009760955000,
        },
        session: {
          id: 2467401570302887000,
        },
      },
      timeline: {
        token: "VSmteTw",
      },
      metric_timestamp: 1692884781339,
      id: "AYony5tNAABD2keLdXiNPvea",
      tag: {
        service: "openobserve",
        sdk_version: "4.47.0",
        api: "beacon",
        source: "browser",
        env: "alpha1",
      },
      timestamp: "2023-08-24T13:46:09.613Z",
    },
  },
  {
    event_id: "AYonyMq9AABaFeJmSJxCWcvD",
    "datadog.index": "rum",
    id: "AgAAAYonyMq9qMXmswAAAAAAAAAYAAAAAEFZb255TXE5QUFCYUZlSm1TSnhDV2N2RAAAACQAAAAAMDE4YTI3YzgtY2FiZC00Yjc5LWJlZGEtZTliNWJkNTU4ZTRl",
    event: {
      client_time: 1692884584805,
      random_draw: 0.8034933076901679,
      custom: {
        os: {
          name: "Mac OS X",
          version: "10.15.7",
          version_major: "10",
        },
        session: {
          ip: "103.163.91.139",
          useragent:
            "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36",
          id: "3d6e6af0-0727-4def-862c-7a02e6e4b2ce",
          has_replay: true,
          type: "user",
          plan: "replay",
        },
        display: {
          viewport: {
            width: 1680,
            height: 643,
          },
          scroll: {
            initial_fold_pct: 100,
            max_depth_time: 2758000000,
            max_depth_scroll_height: 643,
            max_depth: 643,
            max_depth_pct: 100,
            max_depth_scroll_top: 0,
          },
        },
        privacy: {
          replay_level: "mask-user-input",
        },
        type: "view",
        geo: {
          continent: "Asia",
          country: "India",
          as: {
            domain: "limericktechnologies.com",
            name: "Limerick Technologies Pvt. Ltd.",
            type: "isp",
          },
          country_iso_code: "IN",
          city: "Pimpri",
          latitude: 18.62292,
          continent_code: "AS",
          country_subdivision_iso_code: "IN-MH",
          location: [73.80696, 18.62292],
          country_subdivision: "Maharashtra",
          longitude: 73.80696,
        },
        view: {
          load_event: 1807100000,
          long_task: {
            count: 2,
          },
          cumulative_layout_shift: 0,
          error: {
            count: 2,
          },
          dom_content_loaded: 1424500000,
          time_spent: 184464000000,
          first_contentful_paint: 2092900000,
          first_byte: 22300000,
          url_path_group: "/",
          loading_time: 2758000000,
          action: {
            count: 0,
          },
          id: "4e29bd59-aefa-4e19-98d3-3fda3d606a0b",
          url_host: "localhost",
          url_path: "/",
          is_active: false,
          in_foreground_periods: [
            {
              duration: 3315600000,
              start: 1401100000,
            },
          ],
          dom_interactive: 160900000,
          resource: {
            count: 274,
          },
          frustration: {
            count: 0,
          },
          largest_contentful_paint: 2154700000,
          dom_complete: 1806600000,
          url: "http://localhost:8081/",
          url_scheme: "http",
          referrer: "http://localhost:8081/cb",
          name: "/",
          loading_type: "initial_load",
          url_port: 8081,
          referrer_url: {
            url_port: 8081,
            url_host: "localhost",
            url_path: "/cb",
            url_scheme: "http",
          },
        },
        application: {
          name: "Openobserve",
          id: "8ffa2388-4048-436b-b64a-a28f233eba22",
        },
        service: "openobserve",
        browser: {
          name: "Chrome",
          version: "114.0.0.0",
          version_major: "114",
        },
        context: {},
        device: {
          name: "Mac",
          model: "Mac",
          type: "Desktop",
          brand: "Apple",
        },
        _dd: {
          format_version: 2,
          configuration: {
            session_replay_sample_rate: 100,
            session_sample_rate: 100,
          },
          session: {
            plan: 2,
          },
          replay_stats: {
            records_count: 17,
            segments_count: 3,
            segments_total_raw_size: 849248,
          },
          origin: "reducer",
          lowercase_name: "/",
          reducer_status: "closed",
          document_version: 15,
          drift: -2,
          migration_number: 1,
        },
      },
      end_time: 1692884769613,
      tiebreaker: -1463425357,
      source: "browser",
      discovery_timestamp: 1692884585149,
      client_end_time: 1692884769269,
      tags: [
        "env:alpha1",
        "service:openobserve",
        "api:beacon",
        "sdk_version:4.47.0",
        "source:browser",
      ],
      update_time: 1692884769616,
      source_fragment_id: "018a27c8-cabd-4b79-beda-e9b5bd558e4e",
      intake_time: 1692884769616,
      service: ["openobserve"],
      hashes: {
        view: {
          id: 6491343366857180000,
        },
        session: {
          id: 2467401570302887000,
        },
      },
      timeline: {
        token: "VSmteTw",
      },
      metric_timestamp: 1692884769613,
      id: "AYonyMq9AABaFeJmSJxCWcvD",
      tag: {
        service: "openobserve",
        sdk_version: "4.47.0",
        api: "beacon",
        source: "browser",
        env: "alpha1",
      },
      timestamp: "2023-08-24T13:43:05.149Z",
    },
  },
  {
    event_id: "AYonxNCwAABX1lumFQh4aiTa",
    "datadog.index": "rum",
    id: "AgAAAYonxNCwwU_XNwAAAAAAAAAYAAAAAEFZb254TkN3QUFCWDFsdW1GUWg0YWlUYQAAACQAAAAAMDE4YTI3YzgtY2FiZC00Yjc5LWJlZGEtZTliNWJkNTU4ZTRl",
    event: {
      client_time: 1692884313964,
      random_draw: 0.5482959094828326,
      custom: {
        os: {
          name: "Mac OS X",
          version: "10.15.7",
          version_major: "10",
        },
        session: {
          ip: "103.163.91.139",
          useragent:
            "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36",
          id: "3d6e6af0-0727-4def-862c-7a02e6e4b2ce",
          has_replay: true,
          type: "user",
          plan: "replay",
        },
        display: {
          viewport: {
            width: 1680,
            height: 643,
          },
          scroll: {
            initial_fold_pct: 100,
            max_depth_time: 118000000,
            max_depth_scroll_height: 643,
            max_depth: 643,
            max_depth_pct: 100,
            max_depth_scroll_top: 0,
          },
        },
        privacy: {
          replay_level: "mask-user-input",
        },
        type: "view",
        geo: {
          continent: "Asia",
          country: "India",
          as: {
            domain: "limericktechnologies.com",
            name: "Limerick Technologies Pvt. Ltd.",
            type: "isp",
          },
          country_iso_code: "IN",
          city: "Pimpri",
          latitude: 18.62292,
          continent_code: "AS",
          country_subdivision_iso_code: "IN-MH",
          location: [73.80696, 18.62292],
          country_subdivision: "Maharashtra",
          longitude: 73.80696,
        },
        view: {
          url_query: {
            org_identifier: "bhargav_organization_74",
          },
          is_active: false,
          in_foreground_periods: [
            {
              duration: 1081000000,
              start: 0,
            },
          ],
          resource: {
            count: 0,
          },
          frustration: {
            count: 0,
          },
          long_task: {
            count: 1,
          },
          cumulative_layout_shift: 0,
          error: {
            count: 0,
          },
          url: "http://localhost:8081/organizations?org_identifier=bhargav_organization_74",
          url_scheme: "http",
          time_spent: 1081000000,
          referrer:
            "http://localhost:8081/organizations?org_identifier=bhargav_organization_74",
          url_path_group: "/organizations",
          loading_time: 118000000,
          name: "/organizations",
          action: {
            count: 0,
          },
          loading_type: "route_change",
          id: "4f4c46d9-bcf9-4fa5-9936-c1c14c8167bc",
          url_port: 8081,
          referrer_url: {
            url_query: {
              org_identifier: "bhargav_organization_74",
            },
            url_port: 8081,
            url_host: "localhost",
            url_path: "/organizations",
            url_scheme: "http",
          },
          url_host: "localhost",
          url_path: "/organizations",
        },
        application: {
          name: "Openobserve",
          id: "8ffa2388-4048-436b-b64a-a28f233eba22",
        },
        service: "openobserve",
        browser: {
          name: "Chrome",
          version: "114.0.0.0",
          version_major: "114",
        },
        context: {},
        device: {
          name: "Mac",
          model: "Mac",
          type: "Desktop",
          brand: "Apple",
        },
        _dd: {
          format_version: 2,
          configuration: {
            session_replay_sample_rate: 100,
            session_sample_rate: 100,
          },
          session: {
            plan: 2,
          },
          replay_stats: {
            records_count: 25,
            segments_count: 2,
            segments_total_raw_size: 861715,
          },
          origin: "reducer",
          lowercase_name: "/organizations",
          reducer_status: "closed",
          document_version: 15,
          drift: 1482487,
          migration_number: 1,
        },
      },
      end_time: 1692884325609,
      tiebreaker: -1051732169,
      source: "browser",
      discovery_timestamp: 1692884324528,
      client_end_time: 1692884315045,
      tags: [
        "env:alpha1",
        "service:openobserve",
        "api:beacon",
        "sdk_version:4.47.0",
        "source:browser",
      ],
      update_time: 1692898726025,
      source_fragment_id: "018a27c8-cabd-4b79-beda-e9b5bd558e4e",
      intake_time: 1692884325609,
      service: ["openobserve"],
      hashes: {
        view: {
          id: 6329347095191386000,
        },
        session: {
          id: 2467401570302887000,
        },
      },
      timeline: {
        token: "VzyORow",
      },
      metric_timestamp: 1692884325609,
      id: "AYonxNCwAABX1lumFQh4aiTa",
      tag: {
        service: "openobserve",
        sdk_version: "4.47.0",
        api: "beacon",
        source: "browser",
        env: "alpha1",
      },
      timestamp: "2023-08-24T13:38:44.528Z",
    },
  },
];
