ARG CROSS_BASE_IMAGE
FROM $CROSS_BASE_IMAGE

RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive TZ=Etc/UTC apt-get install -y --option=Dpkg::Options::=--force-confnew \
    libssl-dev pkg-config musl-dev musl-tools libboost-all-dev cmake patch wget unzip

RUN wget https://github.com/protocolbuffers/protobuf/releases/download/v21.12/protoc-21.12-linux-x86_64.zip && \
    unzip protoc-21.12-linux-x86_64.zip -d protoc && \
    cp protoc/bin/protoc /usr/local/bin/ && \
    cp -r protoc/include/google /usr/local/include/

RUN ln -s /usr/include/boost/ "/usr/local/${CROSS_CMAKE_SYSTEM_PROCESSOR}-linux-musl/include/"
