"""
Alert History API Tests - Generated by The Gatekeeper
Covers: Contract validation, Sort parameters, Error paths

API Endpoint: GET /api/v2/{org_id}/alerts/history

These tests complement the E2E test in test_alerts.py by covering:
- Response schema contract validation
- Sort parameter variations (sort_by, sort_order)
- Error path tests for invalid parameters
- Unauthorized access

Note: Tests using sort_by/sort_order parameters require the triggers stream
to exist. The ensure_triggers_stream fixture creates an alert and triggers it
to ensure the stream exists before running tests.
"""

import pytest
import requests
import logging
import os
import time
import base64
from datetime import datetime, timedelta, timezone

logger = logging.getLogger(__name__)

# Use TEST_ORG_ID to match conftest.py's DEFAULT_ORG_ID for consistency across tests
# Falls back to "default" which is the standard test organization
ORG_ID = os.environ.get("TEST_ORG_ID", "default")
BASE_URL = os.environ.get("ZO_BASE_URL", "http://localhost:5080/")


@pytest.fixture(scope="module")
def ensure_triggers_stream(create_session, base_url):
    """Ensure the triggers stream exists by creating and triggering a test alert.

    This fixture is independent - it creates its own test data and cleans up after.
    The triggers stream is created when an alert executes, which populates the
    alert history that these tests query.
    """
    session = create_session
    url = base_url
    org_id = ORG_ID
    headers = {"Content-Type": "application/json"}

    # Generate unique names to avoid conflicts
    timestamp = int(time.time() * 1000)
    template_name = f"history_api_test_template_{timestamp}"
    destination_name = f"history_api_test_dest_{timestamp}"
    stream_name = f"history_api_test_stream_{timestamp}"
    alert_name = f"history_api_test_alert_{timestamp}"

    created_resources = {
        "template": None,
        "destination": None,
        "stream": None,
        "alert_id": None,
    }

    try:
        # Step 1: Create template
        template_payload = {
            "name": template_name,
            "body": '{"text": "{alert_name} triggered"}',
            "isDefault": False,
        }
        resp = session.post(
            f"{url}api/{org_id}/alerts/templates",
            json=template_payload,
            headers=headers,
        )
        if resp.status_code == 200:
            created_resources["template"] = template_name
            logger.info(f"Created template: {template_name}")
        else:
            logger.warning(f"Failed to create template: {resp.status_code} - {resp.text}")

        # Step 2: Create destination
        destination_payload = {
            "name": destination_name,
            "url": "http://localhost:9999/webhook",  # Dummy endpoint
            "method": "post",
            "skip_tls_verify": True,
            "template": template_name,
        }
        resp = session.post(
            f"{url}api/{org_id}/alerts/destinations",
            json=destination_payload,
            headers=headers,
        )
        if resp.status_code == 200:
            created_resources["destination"] = destination_name
            logger.info(f"Created destination: {destination_name}")
        else:
            logger.warning(f"Failed to create destination: {resp.status_code} - {resp.text}")

        # Step 3: Create stream and ingest data
        test_data = [
            {"level": "error", "message": "Test error for alert history", "count": 100}
        ]
        resp = session.post(
            f"{url}api/{org_id}/{stream_name}/_json",
            json=test_data,
            headers=headers,
        )
        if resp.status_code == 200:
            created_resources["stream"] = stream_name
            logger.info(f"Ingested data to stream: {stream_name}")
        else:
            logger.warning(f"Failed to ingest data: {resp.status_code} - {resp.text}")

        # Wait for data to be indexed
        time.sleep(3)

        # Step 4: Create alert
        now = datetime.now(timezone.utc)
        start_time = (now - timedelta(hours=1)).strftime("%Y-%m-%dT%H:%M:%S")
        end_time = now.strftime("%Y-%m-%dT%H:%M:%S")

        alert_payload = {
            "name": alert_name,
            "stream_type": "logs",
            "stream_name": stream_name,
            "query_condition": {
                "type": "sql",
                "conditions": None,
                "sql": f'SELECT count(*) as count FROM "{stream_name}"',
                "promql": None,
                "promql_condition": None,
                "aggregation": None,
                "vrl_function": None,
                "search_event_type": "DerivedStream",
            },
            "trigger_condition": {
                "period": 1,
                "operator": ">=",
                "threshold": 0,
                "frequency": 1,
                "cron": "",
                "frequency_type": "minutes",
                "silence": 5,
            },
            "destinations": [destination_name],
            "enabled": True,
            "description": "Test alert for history API tests",
        }
        resp = session.post(
            f"{url}api/v2/{org_id}/alerts",
            json=alert_payload,
            headers=headers,
        )
        if resp.status_code == 200:
            # Get alert ID from response or list
            resp_list = session.get(f"{url}api/v2/{org_id}/alerts")
            if resp_list.status_code == 200:
                for alert in resp_list.json().get("list", []):
                    if alert["name"] == alert_name:
                        created_resources["alert_id"] = alert["alert_id"]
                        logger.info(f"Created alert: {alert_name} (ID: {alert['alert_id']})")
                        break
        else:
            logger.warning(f"Failed to create alert: {resp.status_code} - {resp.text}")

        # Step 5: Wait for alert to trigger (creates triggers stream entry)
        logger.info("Waiting 35 seconds for alert to trigger...")
        time.sleep(35)

        # Verify triggers stream exists
        resp = session.get(f"{url}api/v2/{org_id}/alerts/history?size=1")
        if resp.status_code == 200:
            logger.info("Triggers stream verified - alert history accessible")
        else:
            logger.warning(f"Triggers stream may not exist: {resp.status_code}")

        yield created_resources

    finally:
        # Cleanup
        logger.info("Cleaning up test resources...")

        if created_resources["alert_id"]:
            resp = session.delete(f"{url}api/v2/{org_id}/alerts/{created_resources['alert_id']}")
            logger.info(f"Deleted alert: {resp.status_code}")

        if created_resources["destination"]:
            resp = session.delete(f"{url}api/{org_id}/alerts/destinations/{destination_name}")
            logger.info(f"Deleted destination: {resp.status_code}")

        if created_resources["template"]:
            resp = session.delete(f"{url}api/{org_id}/alerts/templates/{template_name}")
            logger.info(f"Deleted template: {resp.status_code}")

        if created_resources["stream"]:
            resp = session.delete(f"{url}api/{org_id}/streams/{stream_name}?type=logs")
            logger.info(f"Deleted stream: {resp.status_code}")


def is_stream_not_found_error(resp):
    """Check if response is a 500 error due to missing triggers stream."""
    return resp.status_code == 500 and "stream not found" in resp.text.lower()


class TestAlertHistoryContract:
    """Contract tests for Alert History API - validates response schemas.

    These tests don't use sort parameters, so they work even without triggers stream.
    """

    def test_response_schema_structure(self, create_session, base_url):
        """Validate GET /api/v2/{org_id}/alerts/history response has required fields."""
        session = create_session

        resp = session.get(f"{base_url}api/v2/{ORG_ID}/alerts/history?size=5")
        assert resp.status_code == 200, f"Expected 200, got {resp.status_code}: {resp.text}"

        body = resp.json()

        # Top-level schema validation
        required_fields = ["total", "from", "size", "hits"]
        for field in required_fields:
            assert field in body, f"Response missing required field: {field}"

        assert isinstance(body["total"], int), f"'total' should be int, got {type(body['total'])}"
        assert isinstance(body["from"], int), f"'from' should be int, got {type(body['from'])}"
        assert isinstance(body["size"], int), f"'size' should be int, got {type(body['size'])}"
        assert isinstance(body["hits"], list), f"'hits' should be list, got {type(body['hits'])}"

        logger.info(f"Contract validation passed: total={body['total']}, size={body['size']}")

    def test_history_entry_schema(self, create_session, base_url):
        """Validate individual history entry has all required fields."""
        session = create_session

        resp = session.get(f"{base_url}api/v2/{ORG_ID}/alerts/history?size=1")
        assert resp.status_code == 200, f"Expected 200, got {resp.status_code}: {resp.text}"

        body = resp.json()

        if body["hits"]:
            entry = body["hits"][0]

            # Required fields per AlertHistoryEntry schema
            required_fields = [
                "timestamp", "alert_name", "org", "status",
                "is_realtime", "is_silenced", "start_time", "end_time", "retries"
            ]

            for field in required_fields:
                assert field in entry, f"Entry missing required field: {field}"

            # Type validations
            assert isinstance(entry["timestamp"], int), "timestamp should be int"
            assert isinstance(entry["alert_name"], str), "alert_name should be string"
            assert isinstance(entry["org"], str), "org should be string"
            assert isinstance(entry["status"], str), "status should be string"
            assert isinstance(entry["is_realtime"], bool), "is_realtime should be bool"
            assert isinstance(entry["is_silenced"], bool), "is_silenced should be bool"
            assert isinstance(entry["start_time"], int), "start_time should be int"
            assert isinstance(entry["end_time"], int), "end_time should be int"
            assert isinstance(entry["retries"], int), "retries should be int"

            logger.info(f"Entry schema validated: alert_name={entry['alert_name']}, status={entry['status']}")
        else:
            logger.warning("No history entries found - skipping entry schema validation")


@pytest.mark.usefixtures("ensure_triggers_stream")
class TestAlertHistorySorting:
    """Tests for sort_by and sort_order parameters.

    These tests require the triggers stream to exist because the API
    attempts to sort results which requires stream access.
    """

    @pytest.mark.parametrize("sort_field", [
        "timestamp",
        "alert_name",
        "status",
        "is_realtime",
        "is_silenced",
        "start_time",
        "end_time",
        "duration",
        "retries",
        "delay_in_secs",
        "evaluation_took_in_secs",
        "source_node",
        "query_took",
    ])
    def test_sort_by_valid_fields(self, create_session, base_url, sort_field):
        """Validate all documented sort_by fields are accepted."""
        session = create_session

        resp = session.get(f"{base_url}api/v2/{ORG_ID}/alerts/history?sort_by={sort_field}&size=5")

        # Skip if triggers stream doesn't exist (API returns 500 for sort queries without stream)
        if is_stream_not_found_error(resp):
            pytest.skip("Triggers stream not found - sort tests require alert history data")

        assert resp.status_code == 200, (
            f"Expected 200 for sort_by={sort_field}, got {resp.status_code}: {resp.text}"
        )

        body = resp.json()
        assert "hits" in body, f"Response missing 'hits' for sort_by={sort_field}"
        logger.info(f"sort_by={sort_field}: returned {len(body['hits'])} entries")

    @pytest.mark.parametrize("sort_order", ["asc", "desc", "ASC", "DESC"])
    def test_sort_order_valid_values(self, create_session, base_url, sort_order):
        """Validate asc/desc sort_order values (case-insensitive).

        API implementation uses to_lowercase() on sort_order before matching,
        so uppercase variants are intentionally supported.
        See: src/handler/http/request/alerts/history.rs line 229
        """
        session = create_session

        resp = session.get(
            f"{base_url}api/v2/{ORG_ID}/alerts/history?sort_by=timestamp&sort_order={sort_order}&size=5"
        )

        # Skip if triggers stream doesn't exist
        if is_stream_not_found_error(resp):
            pytest.skip("Triggers stream not found - sort tests require alert history data")

        assert resp.status_code == 200, (
            f"Expected 200 for sort_order={sort_order}, got {resp.status_code}: {resp.text}"
        )

        body = resp.json()
        assert "hits" in body, f"Response missing 'hits' for sort_order={sort_order}"
        logger.info(f"sort_order={sort_order}: returned {len(body['hits'])} entries")

    def test_sort_by_timestamp_desc_ordering(self, create_session, base_url):
        """Verify descending sort by timestamp returns entries in correct order."""
        session = create_session

        resp = session.get(
            f"{base_url}api/v2/{ORG_ID}/alerts/history?sort_by=timestamp&sort_order=desc&size=10"
        )

        # Skip if triggers stream doesn't exist
        if is_stream_not_found_error(resp):
            pytest.skip("Triggers stream not found - sort tests require alert history data")

        assert resp.status_code == 200, f"Expected 200, got {resp.status_code}: {resp.text}"

        body = resp.json()
        hits = body.get("hits", [])

        if len(hits) >= 2:
            timestamps = [entry["timestamp"] for entry in hits]
            for i in range(len(timestamps) - 1):
                assert timestamps[i] >= timestamps[i + 1], (
                    f"Entries not in descending order: {timestamps[i]} < {timestamps[i+1]}"
                )
            logger.info(f"Descending order verified for {len(hits)} entries")
        else:
            logger.warning("Not enough entries to verify ordering")

    def test_sort_by_timestamp_asc_ordering(self, create_session, base_url):
        """Verify ascending sort by timestamp returns entries in correct order."""
        session = create_session

        resp = session.get(
            f"{base_url}api/v2/{ORG_ID}/alerts/history?sort_by=timestamp&sort_order=asc&size=10"
        )

        # Skip if triggers stream doesn't exist
        if is_stream_not_found_error(resp):
            pytest.skip("Triggers stream not found - sort tests require alert history data")

        assert resp.status_code == 200, f"Expected 200, got {resp.status_code}: {resp.text}"

        body = resp.json()
        hits = body.get("hits", [])

        if len(hits) >= 2:
            timestamps = [entry["timestamp"] for entry in hits]
            for i in range(len(timestamps) - 1):
                assert timestamps[i] <= timestamps[i + 1], (
                    f"Entries not in ascending order: {timestamps[i]} > {timestamps[i+1]}"
                )
            logger.info(f"Ascending order verified for {len(hits)} entries")
        else:
            logger.warning("Not enough entries to verify ordering")


class TestAlertHistoryErrors:
    """Error path tests for Alert History API."""

    def test_invalid_sort_by_field(self, create_session, base_url):
        """Invalid sort_by field should return 400.

        API validates sort_by against whitelist and returns MetaHttpResponse::bad_request
        for invalid fields. See: src/handler/http/request/alerts/history.rs lines 217-220
        """
        session = create_session

        resp = session.get(
            f"{base_url}api/v2/{ORG_ID}/alerts/history?sort_by=invalid_field"
        )
        assert resp.status_code == 400, (
            f"Expected 400 for invalid sort_by, got {resp.status_code}: {resp.text}"
        )
        logger.info("Invalid sort_by correctly rejected with 400")

    def test_invalid_sort_order_value(self, create_session, base_url):
        """Invalid sort_order value should return 400.

        API validates sort_order against "asc"/"desc" and returns MetaHttpResponse::bad_request
        for invalid values. See: src/handler/http/request/alerts/history.rs lines 232-235
        """
        session = create_session

        resp = session.get(
            f"{base_url}api/v2/{ORG_ID}/alerts/history?sort_order=invalid"
        )
        assert resp.status_code == 400, (
            f"Expected 400 for invalid sort_order, got {resp.status_code}: {resp.text}"
        )
        logger.info("Invalid sort_order correctly rejected with 400")

    def test_unauthorized_access(self, base_url):
        """Verify 401 for unauthenticated requests."""
        # Use raw requests without auth
        resp = requests.get(f"{base_url}api/v2/{ORG_ID}/alerts/history")
        assert resp.status_code == 401, (
            f"Expected 401 for unauthenticated request, got {resp.status_code}"
        )
        logger.info("Unauthorized request correctly rejected with 401")

    def test_negative_from_parameter(self, create_session, base_url):
        """Negative from parameter should be treated as 0."""
        session = create_session

        resp = session.get(f"{base_url}api/v2/{ORG_ID}/alerts/history?from=-10&size=5")
        assert resp.status_code == 200, (
            f"Expected 200 (negative from clamped), got {resp.status_code}: {resp.text}"
        )

        body = resp.json()
        # From should be clamped to 0
        assert body["from"] == 0, f"Expected from=0 (clamped), got {body['from']}"
        logger.info("Negative from parameter correctly clamped to 0")

    def test_zero_size_parameter(self, create_session, base_url):
        """Zero size parameter should be clamped to minimum (1).

        API uses .clamp(1, 1000) on size parameter, so 0 is clamped to 1.
        The response reflects the clamped value, not the requested value.
        See: src/handler/http/request/alerts/history.rs line 170
        """
        session = create_session

        resp = session.get(f"{base_url}api/v2/{ORG_ID}/alerts/history?size=0")
        assert resp.status_code == 200, (
            f"Expected 200 (zero size clamped), got {resp.status_code}: {resp.text}"
        )

        body = resp.json()
        # Size should be clamped to at least 1 (API uses .clamp(1, 1000))
        assert body["size"] >= 1, f"Expected size>=1 (clamped), got {body['size']}"
        logger.info(f"Zero size parameter clamped to {body['size']}")


@pytest.mark.usefixtures("ensure_triggers_stream")
class TestAlertHistoryPaginationEdgeCases:
    """Edge case tests for pagination parameters."""

    def test_offset_beyond_total(self, create_session, base_url):
        """Offset beyond total should return empty hits."""
        session = create_session

        # First get total count
        resp = session.get(f"{base_url}api/v2/{ORG_ID}/alerts/history?size=1")
        assert resp.status_code == 200
        total = resp.json()["total"]

        # Request with offset beyond total
        resp = session.get(f"{base_url}api/v2/{ORG_ID}/alerts/history?from={total + 100}&size=10")
        assert resp.status_code == 200, f"Expected 200, got {resp.status_code}: {resp.text}"

        body = resp.json()
        assert len(body["hits"]) == 0, f"Expected empty hits, got {len(body['hits'])}"
        logger.info(f"Offset beyond total ({total + 100}) correctly returned empty hits")

    def test_combined_sort_and_pagination(self, create_session, base_url):
        """Test sort_by and pagination work together correctly."""
        session = create_session

        resp = session.get(
            f"{base_url}api/v2/{ORG_ID}/alerts/history?sort_by=timestamp&sort_order=desc&from=0&size=5"
        )

        # Skip if triggers stream doesn't exist
        if is_stream_not_found_error(resp):
            pytest.skip("Triggers stream not found - sort tests require alert history data")

        assert resp.status_code == 200, f"Expected 200, got {resp.status_code}: {resp.text}"

        body = resp.json()
        assert body["from"] == 0, f"Expected from=0, got {body['from']}"
        assert body["size"] == 5, f"Expected size=5, got {body['size']}"
        assert len(body["hits"]) <= 5, f"Expected at most 5 hits, got {len(body['hits'])}"
        logger.info("Combined sort and pagination working correctly")

    def test_time_range_with_sorting(self, create_session, base_url):
        """Test time range filtering with sort parameters."""
        session = create_session

        end_time = int(datetime.now(timezone.utc).timestamp() * 1_000_000)
        start_time = int((datetime.now(timezone.utc) - timedelta(days=1)).timestamp() * 1_000_000)

        resp = session.get(
            f"{base_url}api/v2/{ORG_ID}/alerts/history"
            f"?start_time={start_time}&end_time={end_time}"
            f"&sort_by=timestamp&sort_order=asc&size=10"
        )

        # Skip if triggers stream doesn't exist
        if is_stream_not_found_error(resp):
            pytest.skip("Triggers stream not found - sort tests require alert history data")

        assert resp.status_code == 200, f"Expected 200, got {resp.status_code}: {resp.text}"

        body = resp.json()
        logger.info(f"Time range + sort: {body['total']} total, {len(body['hits'])} returned")
