"""
Alert History API Tests - Generated by The Gatekeeper
Covers: Contract validation, Sort parameters, Error paths

API Endpoint: GET /api/{org_id}/alerts/history

These tests complement the E2E test in test_alerts.py by covering:
- Response schema contract validation
- Sort parameter variations (sort_by, sort_order)
- Error path tests for invalid parameters
- Unauthorized access
"""

import pytest
import time
import requests
import logging
from datetime import datetime, timedelta

logger = logging.getLogger(__name__)

ORG_ID = "default"


class TestAlertHistoryContract:
    """Contract tests for Alert History API - validates response schemas."""

    def test_response_schema_structure(self, create_session, base_url):
        """Validate GET /api/{org_id}/alerts/history response has required fields."""
        session = create_session

        resp = session.get(f"{base_url}api/{ORG_ID}/alerts/history?size=5")
        assert resp.status_code == 200, f"Expected 200, got {resp.status_code}: {resp.text}"

        body = resp.json()

        # Top-level schema validation
        required_fields = ["total", "from", "size", "hits"]
        for field in required_fields:
            assert field in body, f"Response missing required field: {field}"

        assert isinstance(body["total"], int), f"'total' should be int, got {type(body['total'])}"
        assert isinstance(body["from"], int), f"'from' should be int, got {type(body['from'])}"
        assert isinstance(body["size"], int), f"'size' should be int, got {type(body['size'])}"
        assert isinstance(body["hits"], list), f"'hits' should be list, got {type(body['hits'])}"

        logger.info(f"Contract validation passed: total={body['total']}, size={body['size']}")

    def test_history_entry_schema(self, create_session, base_url):
        """Validate individual history entry has all required fields."""
        session = create_session

        resp = session.get(f"{base_url}api/{ORG_ID}/alerts/history?size=1")
        assert resp.status_code == 200, f"Expected 200, got {resp.status_code}: {resp.text}"

        body = resp.json()

        if body["hits"]:
            entry = body["hits"][0]

            # Required fields per AlertHistoryEntry schema
            required_fields = [
                "timestamp", "alert_name", "org", "status",
                "is_realtime", "is_silenced", "start_time", "end_time", "retries"
            ]

            for field in required_fields:
                assert field in entry, f"Entry missing required field: {field}"

            # Type validations
            assert isinstance(entry["timestamp"], int), "timestamp should be int"
            assert isinstance(entry["alert_name"], str), "alert_name should be string"
            assert isinstance(entry["org"], str), "org should be string"
            assert isinstance(entry["status"], str), "status should be string"
            assert isinstance(entry["is_realtime"], bool), "is_realtime should be bool"
            assert isinstance(entry["is_silenced"], bool), "is_silenced should be bool"
            assert isinstance(entry["start_time"], int), "start_time should be int"
            assert isinstance(entry["end_time"], int), "end_time should be int"
            assert isinstance(entry["retries"], int), "retries should be int"

            logger.info(f"Entry schema validated: alert_name={entry['alert_name']}, status={entry['status']}")
        else:
            logger.warning("No history entries found - skipping entry schema validation")


class TestAlertHistorySorting:
    """Tests for sort_by and sort_order parameters."""

    @pytest.mark.parametrize("sort_field", [
        "timestamp",
        "alert_name",
        "status",
        "is_realtime",
        "is_silenced",
        "start_time",
        "end_time",
        "duration",
        "retries",
        "delay_in_secs",
        "evaluation_took_in_secs",
        "source_node",
        "query_took",
    ])
    def test_sort_by_valid_fields(self, create_session, base_url, sort_field):
        """Validate all documented sort_by fields are accepted."""
        session = create_session

        resp = session.get(f"{base_url}api/{ORG_ID}/alerts/history?sort_by={sort_field}&size=5")
        assert resp.status_code == 200, (
            f"Expected 200 for sort_by={sort_field}, got {resp.status_code}: {resp.text}"
        )

        body = resp.json()
        assert "hits" in body, f"Response missing 'hits' for sort_by={sort_field}"
        logger.info(f"sort_by={sort_field}: returned {len(body['hits'])} entries")

    @pytest.mark.parametrize("sort_order", ["asc", "desc", "ASC", "DESC"])
    def test_sort_order_valid_values(self, create_session, base_url, sort_order):
        """Validate asc/desc sort_order values (case-insensitive)."""
        session = create_session

        resp = session.get(
            f"{base_url}api/{ORG_ID}/alerts/history?sort_by=timestamp&sort_order={sort_order}&size=5"
        )
        assert resp.status_code == 200, (
            f"Expected 200 for sort_order={sort_order}, got {resp.status_code}: {resp.text}"
        )

        body = resp.json()
        assert "hits" in body, f"Response missing 'hits' for sort_order={sort_order}"
        logger.info(f"sort_order={sort_order}: returned {len(body['hits'])} entries")

    def test_sort_by_timestamp_desc_ordering(self, create_session, base_url):
        """Verify descending sort by timestamp returns entries in correct order."""
        session = create_session

        resp = session.get(
            f"{base_url}api/{ORG_ID}/alerts/history?sort_by=timestamp&sort_order=desc&size=10"
        )
        assert resp.status_code == 200, f"Expected 200, got {resp.status_code}: {resp.text}"

        body = resp.json()
        hits = body.get("hits", [])

        if len(hits) >= 2:
            timestamps = [entry["timestamp"] for entry in hits]
            for i in range(len(timestamps) - 1):
                assert timestamps[i] >= timestamps[i + 1], (
                    f"Entries not in descending order: {timestamps[i]} < {timestamps[i+1]}"
                )
            logger.info(f"Descending order verified for {len(hits)} entries")
        else:
            logger.warning("Not enough entries to verify ordering")

    def test_sort_by_timestamp_asc_ordering(self, create_session, base_url):
        """Verify ascending sort by timestamp returns entries in correct order."""
        session = create_session

        resp = session.get(
            f"{base_url}api/{ORG_ID}/alerts/history?sort_by=timestamp&sort_order=asc&size=10"
        )
        assert resp.status_code == 200, f"Expected 200, got {resp.status_code}: {resp.text}"

        body = resp.json()
        hits = body.get("hits", [])

        if len(hits) >= 2:
            timestamps = [entry["timestamp"] for entry in hits]
            for i in range(len(timestamps) - 1):
                assert timestamps[i] <= timestamps[i + 1], (
                    f"Entries not in ascending order: {timestamps[i]} > {timestamps[i+1]}"
                )
            logger.info(f"Ascending order verified for {len(hits)} entries")
        else:
            logger.warning("Not enough entries to verify ordering")


class TestAlertHistoryErrors:
    """Error path tests for Alert History API."""

    def test_invalid_sort_by_field(self, create_session, base_url):
        """Invalid sort_by field should return 400."""
        session = create_session

        resp = session.get(
            f"{base_url}api/{ORG_ID}/alerts/history?sort_by=invalid_field"
        )
        assert resp.status_code == 400, (
            f"Expected 400 for invalid sort_by, got {resp.status_code}: {resp.text}"
        )
        logger.info("Invalid sort_by correctly rejected with 400")

    def test_invalid_sort_order_value(self, create_session, base_url):
        """Invalid sort_order value should return 400."""
        session = create_session

        resp = session.get(
            f"{base_url}api/{ORG_ID}/alerts/history?sort_order=invalid"
        )
        assert resp.status_code == 400, (
            f"Expected 400 for invalid sort_order, got {resp.status_code}: {resp.text}"
        )
        logger.info("Invalid sort_order correctly rejected with 400")

    def test_unauthorized_access(self, base_url):
        """Verify 401 for unauthenticated requests."""
        # Use raw requests without auth
        resp = requests.get(f"{base_url}api/{ORG_ID}/alerts/history")
        assert resp.status_code == 401, (
            f"Expected 401 for unauthenticated request, got {resp.status_code}"
        )
        logger.info("Unauthorized request correctly rejected with 401")

    def test_negative_from_parameter(self, create_session, base_url):
        """Negative from parameter should be treated as 0."""
        session = create_session

        resp = session.get(f"{base_url}api/{ORG_ID}/alerts/history?from=-10&size=5")
        assert resp.status_code == 200, (
            f"Expected 200 (negative from clamped), got {resp.status_code}: {resp.text}"
        )

        body = resp.json()
        # From should be clamped to 0
        assert body["from"] == 0, f"Expected from=0 (clamped), got {body['from']}"
        logger.info("Negative from parameter correctly clamped to 0")

    def test_zero_size_parameter(self, create_session, base_url):
        """Zero size parameter should be clamped to minimum (1)."""
        session = create_session

        resp = session.get(f"{base_url}api/{ORG_ID}/alerts/history?size=0")
        assert resp.status_code == 200, (
            f"Expected 200 (zero size clamped), got {resp.status_code}: {resp.text}"
        )

        body = resp.json()
        # Size should be clamped to at least 1
        assert body["size"] >= 1, f"Expected size>=1 (clamped), got {body['size']}"
        logger.info(f"Zero size parameter clamped to {body['size']}")


class TestAlertHistoryPaginationEdgeCases:
    """Edge case tests for pagination parameters."""

    def test_offset_beyond_total(self, create_session, base_url):
        """Offset beyond total should return empty hits."""
        session = create_session

        # First get total count
        resp = session.get(f"{base_url}api/{ORG_ID}/alerts/history?size=1")
        assert resp.status_code == 200
        total = resp.json()["total"]

        # Request with offset beyond total
        resp = session.get(f"{base_url}api/{ORG_ID}/alerts/history?from={total + 100}&size=10")
        assert resp.status_code == 200, f"Expected 200, got {resp.status_code}: {resp.text}"

        body = resp.json()
        assert len(body["hits"]) == 0, f"Expected empty hits, got {len(body['hits'])}"
        logger.info(f"Offset beyond total ({total + 100}) correctly returned empty hits")

    def test_combined_sort_and_pagination(self, create_session, base_url):
        """Test sort_by and pagination work together correctly."""
        session = create_session

        resp = session.get(
            f"{base_url}api/{ORG_ID}/alerts/history?sort_by=timestamp&sort_order=desc&from=0&size=5"
        )
        assert resp.status_code == 200, f"Expected 200, got {resp.status_code}: {resp.text}"

        body = resp.json()
        assert body["from"] == 0, f"Expected from=0, got {body['from']}"
        assert body["size"] == 5, f"Expected size=5, got {body['size']}"
        assert len(body["hits"]) <= 5, f"Expected at most 5 hits, got {len(body['hits'])}"
        logger.info("Combined sort and pagination working correctly")

    def test_time_range_with_sorting(self, create_session, base_url):
        """Test time range filtering with sort parameters."""
        session = create_session

        end_time = int(datetime.utcnow().timestamp() * 1_000_000)
        start_time = int((datetime.utcnow() - timedelta(days=1)).timestamp() * 1_000_000)

        resp = session.get(
            f"{base_url}api/{ORG_ID}/alerts/history"
            f"?start_time={start_time}&end_time={end_time}"
            f"&sort_by=timestamp&sort_order=asc&size=10"
        )
        assert resp.status_code == 200, f"Expected 200, got {resp.status_code}: {resp.text}"

        body = resp.json()
        logger.info(f"Time range + sort: {body['total']} total, {len(body['hits'])} returned")
