"""
Alert History API Tests - Generated by The Gatekeeper
Covers: Contract validation, Sort parameters, Error paths

API Endpoint: GET /api/v2/{org_id}/alerts/history

These tests complement the E2E test in test_alerts.py by covering:
- Response schema contract validation
- Sort parameter variations (sort_by, sort_order)
- Error path tests for invalid parameters
- Unauthorized access

The tests create an alert that triggers to populate the 'triggers' stream,
ensuring tests can run in fresh CI environments.
"""

import pytest
import time
import requests
import logging
from datetime import datetime, timedelta, timezone

logger = logging.getLogger(__name__)


def triggers_stream_exists(session, base_url, org_id):
    """Check if the triggers stream exists (alert history is available)."""
    resp = session.get(f"{base_url}api/v2/{org_id}/alerts/history?size=1")
    if resp.status_code == 500 and "stream not found" in resp.text.lower():
        return False
    return resp.status_code == 200


@pytest.fixture(scope="module")
def setup_alert_history(create_session, base_url, org_id):
    """
    Setup fixture that creates an alert and triggers it to populate the triggers stream.
    This ensures alert history tests can run in fresh CI environments.
    """
    session = create_session

    # Check if triggers stream already exists
    if triggers_stream_exists(session, base_url, org_id):
        logger.info("Triggers stream already exists, skipping setup")
        yield
        return

    logger.info("Triggers stream does not exist, creating alert to populate it...")

    timestamp = int(time.time() * 1000)
    template_name = f"history_setup_template_{timestamp}"
    destination_name = f"history_setup_dest_{timestamp}"
    alert_name = f"history_setup_alert_{timestamp}"
    stream_name = f"history_setup_stream_{timestamp}"

    headers = {"Content-Type": "application/json"}
    alert_id = None

    try:
        # Step 1: Create template
        template_payload = {
            "name": template_name,
            "body": '{"text": "Alert triggered"}',
            "isDefault": False,
        }
        resp = session.post(
            f"{base_url}api/{org_id}/alerts/templates",
            json=template_payload,
            headers=headers,
        )
        assert resp.status_code == 200, f"Failed to create template: {resp.text}"
        logger.info(f"Created template: {template_name}")

        # Step 2: Create destination
        destination_payload = {
            "url": "http://localhost:9999/webhook",
            "method": "post",
            "skip_tls_verify": True,
            "template": template_name,
            "name": destination_name,
        }
        resp = session.post(
            f"{base_url}api/{org_id}/alerts/destinations",
            json=destination_payload,
            headers=headers,
        )
        assert resp.status_code == 200, f"Failed to create destination: {resp.text}"
        logger.info(f"Created destination: {destination_name}")

        # Step 3: Ingest logs that will trigger the alert
        log_payload = [
            {"level": "ERROR", "message": "Test error for alert history setup"},
            {"level": "ERROR", "message": "Another test error for alert history setup"},
            {"level": "ERROR", "message": "Third error to ensure threshold is met"},
        ]
        resp = session.post(
            f"{base_url}api/{org_id}/{stream_name}/_json",
            json=log_payload,
            headers=headers,
        )
        assert resp.status_code == 200, f"Failed to ingest logs: {resp.text}"
        logger.info(f"Ingested {len(log_payload)} logs to stream: {stream_name}")

        # Wait for data to be indexed
        time.sleep(3)

        # Step 4: Create an alert using v2 API with SQL query type
        alert_payload = {
            "name": alert_name,
            "stream_type": "logs",
            "stream_name": stream_name,
            "is_real_time": False,
            "query_condition": {
                "type": "sql",
                "conditions": None,
                "sql": f"SELECT count(*) as error_count FROM \"{stream_name}\" WHERE level='ERROR'",
                "promql": None,
                "aggregation": None,
            },
            "trigger_condition": {
                "period": 1,
                "operator": ">=",
                "threshold": 1,
                "silence": 1,
                "frequency": 1,
                "frequency_type": "minutes",
            },
            "destinations": [destination_name],
            "enabled": True,
            "description": "Setup alert for history tests",
        }
        resp = session.post(
            f"{base_url}api/v2/{org_id}/alerts",
            json=alert_payload,
            headers=headers,
        )
        assert resp.status_code == 200, f"Failed to create alert: {resp.text}"
        logger.info(f"Created alert: {alert_name}")

        # Get alert ID for cleanup
        resp_list = session.get(f"{base_url}api/v2/{org_id}/alerts")
        if resp_list.status_code == 200:
            for alert in resp_list.json().get("list", []):
                if alert["name"] == alert_name:
                    alert_id = alert["alert_id"]
                    logger.info(f"Alert ID: {alert_id}")
                    break

        # Step 5: Wait for alert to be evaluated and trigger
        logger.info("Waiting for alert to be evaluated (35 seconds)...")
        time.sleep(35)

        # Verify triggers stream now exists
        max_retries = 3
        for attempt in range(max_retries):
            if triggers_stream_exists(session, base_url):
                logger.info("Triggers stream created successfully!")
                break
            logger.info(f"Triggers stream not yet available, waiting (attempt {attempt + 1}/{max_retries})...")
            time.sleep(10)

        yield

    finally:
        # Cleanup
        logger.info("Cleaning up alert history setup resources...")

        # Delete alert using v2 API with alert_id
        if alert_id:
            resp = session.delete(f"{base_url}api/v2/{org_id}/alerts/{alert_id}")
            logger.info(f"Deleted alert: {resp.status_code}")

        time.sleep(2)

        # Delete destination
        resp = session.delete(f"{base_url}api/{org_id}/alerts/destinations/{destination_name}")
        logger.info(f"Deleted destination: {resp.status_code}")

        # Delete template
        resp = session.delete(f"{base_url}api/{org_id}/alerts/templates/{template_name}")
        logger.info(f"Deleted template: {resp.status_code}")

        # Delete stream
        resp = session.delete(f"{base_url}api/{org_id}/streams/{stream_name}?type=logs")
        logger.info(f"Deleted stream: {resp.status_code}")


@pytest.fixture(scope="module")
def ensure_triggers_stream(setup_alert_history, create_session, base_url, org_id):
    """
    Fixture that ensures triggers stream exists before tests run.
    Uses setup_alert_history to create the stream if needed, then skips if still not available.
    """
    if not triggers_stream_exists(create_session, base_url, org_id):
        pytest.skip("Triggers stream could not be created - alert may not have triggered")


@pytest.mark.usefixtures("ensure_triggers_stream")
class TestAlertHistoryContract:
    """Contract tests for Alert History API - validates response schemas."""

    def test_response_schema_structure(self, create_session, base_url, org_id):
        """Validate GET /api/v2/{org_id}/alerts/history response has required fields."""
        session = create_session

        resp = session.get(f"{base_url}api/v2/{org_id}/alerts/history?size=5")
        assert resp.status_code == 200, f"Expected 200, got {resp.status_code}: {resp.text}"

        body = resp.json()

        # Top-level schema validation
        required_fields = ["total", "from", "size", "hits"]
        for field in required_fields:
            assert field in body, f"Response missing required field: {field}"

        assert isinstance(body["total"], int), f"'total' should be int, got {type(body['total'])}"
        assert isinstance(body["from"], int), f"'from' should be int, got {type(body['from'])}"
        assert isinstance(body["size"], int), f"'size' should be int, got {type(body['size'])}"
        assert isinstance(body["hits"], list), f"'hits' should be list, got {type(body['hits'])}"

        logger.info(f"Contract validation passed: total={body['total']}, size={body['size']}")

    def test_history_entry_schema(self, create_session, base_url, org_id):
        """Validate individual history entry has all required fields."""
        session = create_session

        resp = session.get(f"{base_url}api/v2/{org_id}/alerts/history?size=1")
        assert resp.status_code == 200, f"Expected 200, got {resp.status_code}: {resp.text}"

        body = resp.json()

        if body["hits"]:
            entry = body["hits"][0]

            # Required fields per AlertHistoryEntry schema
            required_fields = [
                "timestamp", "alert_name", "org", "status",
                "is_realtime", "is_silenced", "start_time", "end_time", "retries"
            ]

            for field in required_fields:
                assert field in entry, f"Entry missing required field: {field}"

            # Type validations
            assert isinstance(entry["timestamp"], int), "timestamp should be int"
            assert isinstance(entry["alert_name"], str), "alert_name should be string"
            assert isinstance(entry["org"], str), "org should be string"
            assert isinstance(entry["status"], str), "status should be string"
            assert isinstance(entry["is_realtime"], bool), "is_realtime should be bool"
            assert isinstance(entry["is_silenced"], bool), "is_silenced should be bool"
            assert isinstance(entry["start_time"], int), "start_time should be int"
            assert isinstance(entry["end_time"], int), "end_time should be int"
            assert isinstance(entry["retries"], int), "retries should be int"

            logger.info(f"Entry schema validated: alert_name={entry['alert_name']}, status={entry['status']}")
        else:
            logger.warning("No history entries found - skipping entry schema validation")


@pytest.mark.usefixtures("ensure_triggers_stream")
class TestAlertHistorySorting:
    """Tests for sort_by and sort_order parameters."""

    @pytest.mark.parametrize("sort_field", [
        "timestamp",
        "alert_name",
        "status",
        "is_realtime",
        "is_silenced",
        "start_time",
        "end_time",
        "duration",
        "retries",
        "delay_in_secs",
        "evaluation_took_in_secs",
        "source_node",
        "query_took",
    ])
    def test_sort_by_valid_fields(self, create_session, base_url, org_id, sort_field):
        """Validate all documented sort_by fields are accepted."""
        session = create_session

        resp = session.get(f"{base_url}api/v2/{org_id}/alerts/history?sort_by={sort_field}&size=5")
        assert resp.status_code == 200, (
            f"Expected 200 for sort_by={sort_field}, got {resp.status_code}: {resp.text}"
        )

        body = resp.json()
        assert "hits" in body, f"Response missing 'hits' for sort_by={sort_field}"
        logger.info(f"sort_by={sort_field}: returned {len(body['hits'])} entries")

    @pytest.mark.parametrize("sort_order", ["asc", "desc", "ASC", "DESC"])
    def test_sort_order_valid_values(self, create_session, base_url, org_id, sort_order):
        """Validate asc/desc sort_order values (case-insensitive)."""
        session = create_session

        resp = session.get(
            f"{base_url}api/v2/{org_id}/alerts/history?sort_by=timestamp&sort_order={sort_order}&size=5"
        )
        assert resp.status_code == 200, (
            f"Expected 200 for sort_order={sort_order}, got {resp.status_code}: {resp.text}"
        )

        body = resp.json()
        assert "hits" in body, f"Response missing 'hits' for sort_order={sort_order}"
        logger.info(f"sort_order={sort_order}: returned {len(body['hits'])} entries")

    def test_sort_by_timestamp_desc_ordering(self, create_session, base_url, org_id):
        """Verify descending sort by timestamp returns entries in correct order."""
        session = create_session

        resp = session.get(
            f"{base_url}api/v2/{org_id}/alerts/history?sort_by=timestamp&sort_order=desc&size=10"
        )
        assert resp.status_code == 200, f"Expected 200, got {resp.status_code}: {resp.text}"

        body = resp.json()
        hits = body.get("hits", [])

        if len(hits) >= 2:
            timestamps = [entry["timestamp"] for entry in hits]
            for i in range(len(timestamps) - 1):
                assert timestamps[i] >= timestamps[i + 1], (
                    f"Entries not in descending order: {timestamps[i]} < {timestamps[i+1]}"
                )
            logger.info(f"Descending order verified for {len(hits)} entries")
        else:
            logger.warning("Not enough entries to verify ordering")

    def test_sort_by_timestamp_asc_ordering(self, create_session, base_url, org_id):
        """Verify ascending sort by timestamp returns entries in correct order."""
        session = create_session

        resp = session.get(
            f"{base_url}api/v2/{org_id}/alerts/history?sort_by=timestamp&sort_order=asc&size=10"
        )
        assert resp.status_code == 200, f"Expected 200, got {resp.status_code}: {resp.text}"

        body = resp.json()
        hits = body.get("hits", [])

        if len(hits) >= 2:
            timestamps = [entry["timestamp"] for entry in hits]
            for i in range(len(timestamps) - 1):
                assert timestamps[i] <= timestamps[i + 1], (
                    f"Entries not in ascending order: {timestamps[i]} > {timestamps[i+1]}"
                )
            logger.info(f"Ascending order verified for {len(hits)} entries")
        else:
            logger.warning("Not enough entries to verify ordering")


@pytest.mark.usefixtures("ensure_triggers_stream")
class TestAlertHistoryErrors:
    """Error path tests for Alert History API."""

    def test_invalid_sort_by_field(self, create_session, base_url, org_id):
        """Invalid sort_by field should return 400."""
        session = create_session

        resp = session.get(
            f"{base_url}api/v2/{org_id}/alerts/history?sort_by=invalid_field"
        )
        assert resp.status_code == 400, (
            f"Expected 400 for invalid sort_by, got {resp.status_code}: {resp.text}"
        )
        logger.info("Invalid sort_by correctly rejected with 400")

    def test_invalid_sort_order_value(self, create_session, base_url, org_id):
        """Invalid sort_order value should return 400."""
        session = create_session

        resp = session.get(
            f"{base_url}api/v2/{org_id}/alerts/history?sort_order=invalid"
        )
        assert resp.status_code == 400, (
            f"Expected 400 for invalid sort_order, got {resp.status_code}: {resp.text}"
        )
        logger.info("Invalid sort_order correctly rejected with 400")

    def test_unauthorized_access(self, base_url, org_id):
        """Verify 401 for unauthenticated requests."""
        # Use raw requests without auth
        resp = requests.get(f"{base_url}api/v2/{org_id}/alerts/history")
        assert resp.status_code == 401, (
            f"Expected 401 for unauthenticated request, got {resp.status_code}"
        )
        logger.info("Unauthorized request correctly rejected with 401")

    def test_negative_from_parameter(self, create_session, base_url, org_id):
        """Negative from parameter should be treated as 0."""
        session = create_session

        resp = session.get(f"{base_url}api/v2/{org_id}/alerts/history?from=-10&size=5")
        assert resp.status_code == 200, (
            f"Expected 200 (negative from clamped), got {resp.status_code}: {resp.text}"
        )

        body = resp.json()
        assert body["from"] == 0, f"Expected from=0 (clamped), got {body['from']}"
        logger.info("Negative from parameter correctly clamped to 0")

    def test_zero_size_parameter(self, create_session, base_url, org_id):
        """Zero size parameter should be clamped to minimum (1)."""
        session = create_session

        resp = session.get(f"{base_url}api/v2/{org_id}/alerts/history?size=0")
        assert resp.status_code == 200, (
            f"Expected 200 (zero size clamped), got {resp.status_code}: {resp.text}"
        )

        body = resp.json()
        assert body["size"] >= 1, f"Expected size>=1 (clamped), got {body['size']}"
        logger.info(f"Zero size parameter clamped to {body['size']}")


@pytest.mark.usefixtures("ensure_triggers_stream")
class TestAlertHistoryPaginationEdgeCases:
    """Edge case tests for pagination parameters."""

    def test_offset_beyond_total(self, create_session, base_url, org_id):
        """Offset beyond total should return empty hits."""
        session = create_session

        # First get total count
        resp = session.get(f"{base_url}api/v2/{org_id}/alerts/history?size=1")
        assert resp.status_code == 200
        total = resp.json()["total"]

        # Request with offset beyond total
        resp = session.get(f"{base_url}api/v2/{org_id}/alerts/history?from={total + 100}&size=10")
        assert resp.status_code == 200, f"Expected 200, got {resp.status_code}: {resp.text}"

        body = resp.json()
        assert len(body["hits"]) == 0, f"Expected empty hits, got {len(body['hits'])}"
        logger.info(f"Offset beyond total ({total + 100}) correctly returned empty hits")

    def test_combined_sort_and_pagination(self, create_session, base_url, org_id):
        """Test sort_by and pagination work together correctly."""
        session = create_session

        resp = session.get(
            f"{base_url}api/v2/{org_id}/alerts/history?sort_by=timestamp&sort_order=desc&from=0&size=5"
        )
        assert resp.status_code == 200, f"Expected 200, got {resp.status_code}: {resp.text}"

        body = resp.json()
        assert body["from"] == 0, f"Expected from=0, got {body['from']}"
        assert body["size"] == 5, f"Expected size=5, got {body['size']}"
        assert len(body["hits"]) <= 5, f"Expected at most 5 hits, got {len(body['hits'])}"
        logger.info("Combined sort and pagination working correctly")

    def test_time_range_with_sorting(self, create_session, base_url, org_id):
        """Test time range filtering with sort parameters."""
        session = create_session

        end_time = int(datetime.now(timezone.utc).timestamp() * 1_000_000)
        start_time = int((datetime.now(timezone.utc) - timedelta(days=1)).timestamp() * 1_000_000)

        resp = session.get(
            f"{base_url}api/v2/{org_id}/alerts/history"
            f"?start_time={start_time}&end_time={end_time}"
            f"&sort_by=timestamp&sort_order=asc&size=10"
        )
        assert resp.status_code == 200, f"Expected 200, got {resp.status_code}: {resp.text}"

        body = resp.json()
        logger.info(f"Time range + sort: {body['total']} total, {len(body['hits'])} returned")
