// Copyright 2026 OpenObserve Inc.
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.

/**
 * The exceptions to the contrast rule, and the debt that rule has not paid off.
 *
 * `contrast.spec.ts` judges every foreground token against `--color-surface-base`,
 * because that is what the page is painted with. This file names the pairs where
 * that default is wrong — a badge label sits on the badge, not on the page — the
 * pairs a success criterion does not reach, and the ones that fail today.
 *
 * There is deliberately no entry per token. A token the default rule already
 * judges correctly, on a background it is really painted on, does not belong
 * here; nor does one that passes.
 *
 * `exempt` claims a success criterion does not apply, so its `why` names the
 * criterion. `pending` is a colour that fails today and that this change does
 * not fix; the spec ratchets the count so it can only fall.
 *
 * Token names only, never a literal colour: `scripts/check-design-consistency.mjs`
 * fails the build on a hex in a non-spec `.ts`, and a copied hex would silently
 * stop tracking the token it came from.
 */

export type Category = "text" | "large-text" | "non-text" | "exempt" | "pending";

export interface ContrastPair {
  /** Token drawn on top. */
  fg: string;
  /** Token painted beneath `fg`; the page surface when omitted. */
  bg?: string;
  /** Opaque backdrop chain under a translucent `bg`, nearest first. */
  under?: string[];
  category: Category;
  /** For `exempt`, this must name the success criterion or the reason. */
  why: string;
  /** Required for `pending`. */
  issue?: string;
  /** Both themes when omitted; a theme-scoped entry wins over an unscoped one. */
  themes?: ("light" | "dark")[];
}

export const CONTRAST_PAIRS: readonly ContrastPair[] = [
  {
    fg: "--color-banner-error-soft-border",
    category: "exempt",
    why: "SC 1.4.11 decorative: a container hairline, not information required to identify a component or its state",
  },
  {
    fg: "--color-banner-info-border",
    category: "exempt",
    why: "SC 1.4.11 decorative: a container hairline, not information required to identify a component or its state",
  },
  {
    fg: "--color-banner-success-border",
    category: "exempt",
    why: "SC 1.4.11 decorative: a container hairline, not information required to identify a component or its state",
  },
  {
    fg: "--color-banner-warning-border",
    category: "exempt",
    why: "SC 1.4.11 decorative: a container hairline, not information required to identify a component or its state",
  },
  {
    fg: "--color-border-tint-error",
    category: "exempt",
    why: "SC 1.4.11 decorative: the hairline of a tinted chip whose danger state is already carried by its fill (bg-surface-tint-error) and its text, so the border is not the sole state indicator",
  },
  {
    fg: "--color-border-tint-neutral",
    category: "exempt",
    why: "SC 1.4.11 decorative: the hairline of a tinted chip whose state is already carried by its fill and text, so the border is not the sole state indicator",
  },
  {
    fg: "--color-border-default",
    category: "exempt",
    why: "SC 1.4.11 decorative: a container hairline, not information required to identify a component or its state",
  },
  {
    fg: "--color-border-subtle",
    category: "exempt",
    why: "SC 1.4.11 decorative: a container hairline, not information required to identify a component or its state",
  },
  {
    fg: "--color-brand-msg-border",
    category: "exempt",
    why: "SC 1.4.11 decorative: a container hairline, not information required to identify a component or its state",
  },
  {
    fg: "--color-brand-msg-border-2",
    category: "exempt",
    why: "SC 1.4.11 decorative: a container hairline, not information required to identify a component or its state",
  },
  {
    fg: "--color-brand-msg-divider",
    category: "exempt",
    why: "SC 1.4.11 decorative: a container hairline, not information required to identify a component or its state",
  },
  {
    fg: "--color-card-glass-border",
    category: "exempt",
    why: "SC 1.4.11 decorative: a container hairline, not information required to identify a component or its state",
  },
  {
    fg: "--color-chat-bubble-user-border",
    category: "exempt",
    why: "SC 1.4.11 decorative: a container hairline, not information required to identify a component or its state",
  },
  {
    fg: "--color-datepicker-inner-border",
    category: "exempt",
    why: "SC 1.4.11 decorative: a container hairline, not information required to identify a component or its state",
  },
  {
    fg: "--color-dialog-border",
    category: "exempt",
    why: "SC 1.4.11 decorative: a container hairline, not information required to identify a component or its state",
  },
  {
    fg: "--color-dialog-footer-border",
    category: "exempt",
    why: "SC 1.4.11 decorative: a container hairline, not information required to identify a component or its state",
  },
  {
    fg: "--color-dialog-header-border",
    category: "exempt",
    why: "SC 1.4.11 decorative: a container hairline, not information required to identify a component or its state",
  },
  {
    fg: "--color-dialog-header-border-accent",
    category: "exempt",
    why: "SC 1.4.11 decorative: a container hairline, not information required to identify a component or its state",
  },
  {
    fg: "--color-input-label-text-disabled",
    category: "exempt",
    why: "SC 1.4.3 exempts text and boundaries that belong to a disabled, inactive control",
  },
  {
    fg: "--color-log-table-row-border",
    category: "exempt",
    why: "SC 1.4.11 decorative: a container hairline, not information required to identify a component or its state",
  },
  {
    fg: "--color-menu-badge-ring",
    bg: "--color-surface-chrome",
    category: "exempt",
    why: "SC 1.4.11 decorative: a ring offset is the gap that separates the badge from the chrome behind it, and is meant to match that chrome",
  },
  {
    fg: "--color-panel-bar-border",
    category: "exempt",
    why: "SC 1.4.11 decorative: a container hairline, not information required to identify a component or its state",
  },
  {
    fg: "--color-pivot-header-border",
    category: "exempt",
    why: "SC 1.4.11 decorative: a container hairline, not information required to identify a component or its state",
  },
  {
    fg: "--color-radio-disabled-border",
    category: "exempt",
    why: "SC 1.4.3 exempts text and boundaries that belong to a disabled, inactive control",
  },
  {
    fg: "--color-switch-disabled-border",
    category: "exempt",
    why: "SC 1.4.3 exempts text and boundaries that belong to a disabled, inactive control",
  },
  {
    fg: "--color-table-row-divider",
    category: "exempt",
    why: "SC 1.4.11 decorative: a container hairline, not information required to identify a component or its state",
  },
  {
    fg: "--color-tabs-bar-border",
    category: "exempt",
    why: "SC 1.4.11 decorative: a container hairline, not information required to identify a component or its state",
  },
  {
    fg: "--color-text-disabled",
    category: "exempt",
    why: "SC 1.4.3 exempts text and boundaries that belong to a disabled, inactive control",
  },
  {
    fg: "--color-thread-bubble-border-dark",
    category: "exempt",
    why: "SC 1.4.11 decorative: a container hairline, not information required to identify a component or its state",
  },
  {
    fg: "--color-toast-error-border",
    category: "exempt",
    why: "SC 1.4.11 decorative: a container hairline, not information required to identify a component or its state",
  },
  {
    fg: "--color-toast-info-border",
    category: "exempt",
    why: "SC 1.4.11 decorative: a container hairline, not information required to identify a component or its state",
  },
  {
    fg: "--color-toast-success-border",
    category: "exempt",
    why: "SC 1.4.11 decorative: a container hairline, not information required to identify a component or its state",
  },
  {
    fg: "--color-toast-warning-border",
    category: "exempt",
    why: "SC 1.4.11 decorative: a container hairline, not information required to identify a component or its state",
  },
  {
    fg: "--color-tooltip-border",
    category: "exempt",
    why: "SC 1.4.11 decorative: a container hairline, not information required to identify a component or its state",
  },
  {
    fg: "--color-trace-border",
    category: "exempt",
    why: "SC 1.4.11 decorative: a container hairline, not information required to identify a component or its state",
  },
  {
    fg: "--color-usage-banner-error-border",
    category: "exempt",
    why: "SC 1.4.11 decorative: a container hairline, not information required to identify a component or its state",
  },
  {
    fg: "--color-usage-banner-warning-border",
    category: "exempt",
    why: "SC 1.4.11 decorative: a container hairline, not information required to identify a component or its state",
  },
  {
    fg: "--color-slider-thumb-border",
    bg: "--color-slider-track-fill",
    category: "non-text",
    why: "the thumb rides on the filled part of its own track",
  },
  {
    fg: "--color-stepper-indicator-fg",
    bg: "--color-stepper-indicator-active",
    category: "non-text",
    why: "the step number is drawn inside the indicator",
  },
  {
    fg: "--color-timeline-dot-fg",
    bg: "--color-timeline-dot-primary",
    category: "non-text",
    why: "the glyph is drawn inside the timeline dot",
  },
  {
    fg: "--color-badge-amber-ol-border",
    category: "pending",
    why: "fails the threshold against the page surface it is painted on",
    issue: "WCAG-AA colour remediation (follow-up PR)",
    themes: ["light"],
  },
  {
    fg: "--color-badge-amber-solid-text",
    bg: "--color-badge-amber-solid-bg",
    category: "pending",
    why: "a badge label is painted on the badge's own solid fill, never on the page",
    issue: "WCAG-AA colour remediation (follow-up PR)",
  },
  {
    fg: "--color-badge-blue-solid-text",
    bg: "--color-badge-blue-solid-bg",
    category: "pending",
    why: "a badge label is painted on the badge's own solid fill, never on the page",
    issue: "WCAG-AA colour remediation (follow-up PR)",
    themes: ["dark"],
  },
  {
    fg: "--color-badge-cyan-ol-border",
    category: "pending",
    why: "fails the threshold against the page surface it is painted on",
    issue: "WCAG-AA colour remediation (follow-up PR)",
    themes: ["light"],
  },
  {
    fg: "--color-badge-cyan-solid-text",
    bg: "--color-badge-cyan-solid-bg",
    category: "pending",
    why: "a badge label is painted on the badge's own solid fill, never on the page",
    issue: "WCAG-AA colour remediation (follow-up PR)",
  },
  {
    fg: "--color-badge-default-ol-border",
    category: "pending",
    why: "fails the threshold against the page surface it is painted on",
    issue: "WCAG-AA colour remediation (follow-up PR)",
    themes: ["light"],
  },
  {
    fg: "--color-badge-default-solid-text",
    bg: "--color-badge-default-solid-bg",
    category: "pending",
    why: "a badge label is painted on the badge's own solid fill, never on the page",
    issue: "WCAG-AA colour remediation (follow-up PR)",
    themes: ["dark"],
  },
  {
    fg: "--color-badge-indigo-solid-text",
    bg: "--color-badge-indigo-solid-bg",
    category: "pending",
    why: "a badge label is painted on the badge's own solid fill, never on the page",
    issue: "WCAG-AA colour remediation (follow-up PR)",
    themes: ["dark"],
  },
  {
    fg: "--color-badge-lime-ol-border",
    category: "pending",
    why: "fails the threshold against the page surface it is painted on",
    issue: "WCAG-AA colour remediation (follow-up PR)",
    themes: ["light"],
  },
  {
    fg: "--color-badge-lime-solid-text",
    bg: "--color-badge-lime-solid-bg",
    category: "pending",
    why: "a badge label is painted on the badge's own solid fill, never on the page",
    issue: "WCAG-AA colour remediation (follow-up PR)",
  },
  {
    fg: "--color-badge-orange-ol-border",
    category: "pending",
    why: "fails the threshold against the page surface it is painted on",
    issue: "WCAG-AA colour remediation (follow-up PR)",
    themes: ["light"],
  },
  {
    fg: "--color-badge-orange-solid-text",
    bg: "--color-badge-orange-solid-bg",
    category: "pending",
    why: "a badge label is painted on the badge's own solid fill, never on the page",
    issue: "WCAG-AA colour remediation (follow-up PR)",
  },
  {
    fg: "--color-badge-primary-ol-border",
    category: "pending",
    why: "fails the threshold against the page surface it is painted on",
    issue: "WCAG-AA colour remediation (follow-up PR)",
    themes: ["light"],
  },
  {
    fg: "--color-badge-primary-solid-text",
    bg: "--color-badge-primary-solid-bg",
    category: "pending",
    why: "a badge label is painted on the badge's own solid fill, never on the page",
    issue: "WCAG-AA colour remediation (follow-up PR)",
    themes: ["dark"],
  },
  {
    fg: "--color-badge-purple-solid-text",
    bg: "--color-badge-purple-solid-bg",
    category: "pending",
    why: "a badge label is painted on the badge's own solid fill, never on the page",
    issue: "WCAG-AA colour remediation (follow-up PR)",
    themes: ["dark"],
  },
  {
    fg: "--color-badge-success-ol-border",
    category: "pending",
    why: "fails the threshold against the page surface it is painted on",
    issue: "WCAG-AA colour remediation (follow-up PR)",
    themes: ["light"],
  },
  {
    fg: "--color-badge-success-solid-text",
    bg: "--color-badge-success-solid-bg",
    category: "pending",
    why: "a badge label is painted on the badge's own solid fill, never on the page",
    issue: "WCAG-AA colour remediation (follow-up PR)",
  },
  {
    fg: "--color-badge-teal-ol-border",
    category: "pending",
    why: "fails the threshold against the page surface it is painted on",
    issue: "WCAG-AA colour remediation (follow-up PR)",
    themes: ["light"],
  },
  {
    fg: "--color-badge-teal-solid-text",
    bg: "--color-badge-teal-solid-bg",
    category: "pending",
    why: "a badge label is painted on the badge's own solid fill, never on the page",
    issue: "WCAG-AA colour remediation (follow-up PR)",
  },
  {
    fg: "--color-badge-warning-ol-border",
    category: "pending",
    why: "fails the threshold against the page surface it is painted on",
    issue: "WCAG-AA colour remediation (follow-up PR)",
    themes: ["light"],
  },
  {
    fg: "--color-badge-warning-quiet-border",
    category: "pending",
    why: "fails the threshold against the page surface it is painted on",
    issue: "WCAG-AA colour remediation (follow-up PR)",
  },
  {
    fg: "--color-border-strong",
    category: "pending",
    why: "fails the threshold against the page surface it is painted on",
    issue: "WCAG-AA colour remediation (follow-up PR)",
    themes: ["light"],
  },
  {
    fg: "--color-button-ghost-hover-ring",
    category: "pending",
    why: "fails the threshold against the page surface it is painted on",
    issue: "WCAG-AA colour remediation (follow-up PR)",
    themes: ["light"],
  },
  {
    fg: "--color-button-ghost-success-text",
    category: "pending",
    why: "fails the threshold against the page surface it is painted on",
    issue: "WCAG-AA colour remediation (follow-up PR)",
    themes: ["light"],
  },
  {
    fg: "--color-button-ghost-warning-text",
    category: "pending",
    why: "fails the threshold against the page surface it is painted on",
    issue: "WCAG-AA colour remediation (follow-up PR)",
    themes: ["light"],
  },
  {
    fg: "--color-button-on-dark-primary-text",
    category: "pending",
    why: "fails the threshold against the page surface it is painted on",
    issue: "WCAG-AA colour remediation (follow-up PR)",
    themes: ["dark"],
  },
  {
    fg: "--color-button-outline-hover-border",
    category: "pending",
    why: "fails the threshold against the page surface it is painted on",
    issue: "WCAG-AA colour remediation (follow-up PR)",
    themes: ["light"],
  },
  {
    fg: "--color-button-outline-warning-border",
    category: "pending",
    why: "fails the threshold against the page surface it is painted on",
    issue: "WCAG-AA colour remediation (follow-up PR)",
    themes: ["light"],
  },
  {
    fg: "--color-button-outline-warning-text",
    category: "pending",
    why: "fails the threshold against the page surface it is painted on",
    issue: "WCAG-AA colour remediation (follow-up PR)",
    themes: ["light"],
  },
  {
    fg: "--color-button-secondary-border",
    category: "pending",
    why: "fails the threshold against the page surface it is painted on",
    issue: "WCAG-AA colour remediation (follow-up PR)",
  },
  {
    fg: "--color-button-warning-border",
    category: "pending",
    why: "fails the threshold against the page surface it is painted on",
    issue: "WCAG-AA colour remediation (follow-up PR)",
    themes: ["light"],
  },
  {
    fg: "--color-checkbox-checked-fg",
    bg: "--color-checkbox-checked-bg",
    category: "pending",
    why: "the tick is drawn inside the checked box",
    issue: "WCAG-AA colour remediation (follow-up PR)",
    themes: ["dark"],
  },
  {
    fg: "--color-checkbox-hover-border",
    category: "pending",
    why: "fails the threshold against the page surface it is painted on",
    issue: "WCAG-AA colour remediation (follow-up PR)",
    themes: ["light"],
  },
  {
    fg: "--color-dag-node-default-text",
    bg: "--color-dag-node-default-bg",
    category: "pending",
    why: "a DAG node's label is painted on that node's fill inside the graph",
    issue: "WCAG-AA colour remediation (follow-up PR)",
    themes: ["light"],
  },
  {
    fg: "--color-dag-node-embedding-text",
    bg: "--color-dag-node-embedding-bg",
    category: "pending",
    why: "a DAG node's label is painted on that node's fill inside the graph",
    issue: "WCAG-AA colour remediation (follow-up PR)",
    themes: ["light"],
  },
  {
    fg: "--color-dag-node-event-text",
    bg: "--color-dag-node-event-bg",
    category: "pending",
    why: "a DAG node's label is painted on that node's fill inside the graph",
    issue: "WCAG-AA colour remediation (follow-up PR)",
    themes: ["light"],
  },
  {
    fg: "--color-dag-node-generation-text",
    bg: "--color-dag-node-generation-bg",
    category: "pending",
    why: "a DAG node's label is painted on that node's fill inside the graph",
    issue: "WCAG-AA colour remediation (follow-up PR)",
    themes: ["light"],
  },
  {
    fg: "--color-dag-node-rerank-text",
    bg: "--color-dag-node-rerank-bg",
    category: "pending",
    why: "a DAG node's label is painted on that node's fill inside the graph",
    issue: "WCAG-AA colour remediation (follow-up PR)",
    themes: ["light"],
  },
  {
    fg: "--color-dag-node-retriever-text",
    bg: "--color-dag-node-retriever-bg",
    category: "pending",
    why: "a DAG node's label is painted on that node's fill inside the graph",
    issue: "WCAG-AA colour remediation (follow-up PR)",
    themes: ["light"],
  },
  {
    fg: "--color-dag-node-tool-text",
    bg: "--color-dag-node-tool-bg",
    category: "pending",
    why: "a DAG node's label is painted on that node's fill inside the graph",
    issue: "WCAG-AA colour remediation (follow-up PR)",
    themes: ["light"],
  },
  {
    fg: "--color-datepicker-clock-selected-text",
    bg: "--color-datepicker-clock-selected-bg",
    category: "pending",
    why: "a selected clock number sits on the selection fill",
    issue: "WCAG-AA colour remediation (follow-up PR)",
    themes: ["dark"],
  },
  {
    fg: "--color-datepicker-day-selected-text",
    bg: "--color-datepicker-day-selected-bg",
    category: "pending",
    why: "a selected day sits on the selection fill",
    issue: "WCAG-AA colour remediation (follow-up PR)",
    themes: ["dark"],
  },
  {
    fg: "--color-datepicker-day-today-border",
    category: "pending",
    why: "fails the threshold against the page surface it is painted on",
    issue: "WCAG-AA colour remediation (follow-up PR)",
    themes: ["light"],
  },
  {
    fg: "--color-datepicker-error-text",
    category: "pending",
    why: "fails the threshold against the page surface it is painted on",
    issue: "WCAG-AA colour remediation (follow-up PR)",
    themes: ["dark"],
  },
  {
    fg: "--color-datepicker-focus-border",
    category: "pending",
    why: "fails the threshold against the page surface it is painted on",
    issue: "WCAG-AA colour remediation (follow-up PR)",
    themes: ["light"],
  },
  {
    fg: "--color-datepicker-hover-border",
    category: "pending",
    why: "fails the threshold against the page surface it is painted on",
    issue: "WCAG-AA colour remediation (follow-up PR)",
    themes: ["light"],
  },
  {
    fg: "--color-datepicker-relative-btn-selected-text",
    bg: "--color-datepicker-relative-btn-selected-bg",
    category: "pending",
    why: "a selected preset sits on the selection fill",
    issue: "WCAG-AA colour remediation (follow-up PR)",
    themes: ["dark"],
  },
  {
    fg: "--color-datepicker-segment-focus-text",
    bg: "--color-datepicker-segment-focus-bg",
    category: "pending",
    why: "a focused date segment is highlighted behind the digits",
    issue: "WCAG-AA colour remediation (follow-up PR)",
    themes: ["dark"],
  },
  {
    fg: "--color-error-tag-text",
    bg: "--color-error-tag-bg",
    category: "pending",
    why: "an error tag is a filled pill",
    issue: "WCAG-AA colour remediation (follow-up PR)",
    themes: ["light"],
  },
  {
    fg: "--color-field-type-boolean-text",
    bg: "--color-field-type-boolean-bg",
    category: "pending",
    why: "a field-type tag is a filled chip in the field list",
    issue: "WCAG-AA colour remediation (follow-up PR)",
    themes: ["light"],
  },
  {
    fg: "--color-field-type-float-text",
    bg: "--color-field-type-float-bg",
    category: "pending",
    why: "a field-type tag is a filled chip in the field list",
    issue: "WCAG-AA colour remediation (follow-up PR)",
    themes: ["dark"],
  },
  {
    fg: "--color-field-type-number-text",
    bg: "--color-field-type-number-bg",
    category: "pending",
    why: "a field-type tag is a filled chip in the field list",
    issue: "WCAG-AA colour remediation (follow-up PR)",
    themes: ["light"],
  },
  {
    fg: "--color-field-type-string-text",
    bg: "--color-field-type-string-bg",
    category: "pending",
    why: "a field-type tag is a filled chip in the field list",
    issue: "WCAG-AA colour remediation (follow-up PR)",
    themes: ["light"],
  },
  {
    fg: "--color-field-type-timestamp-text",
    bg: "--color-field-type-timestamp-bg",
    category: "pending",
    why: "a field-type tag is a filled chip in the field list",
    issue: "WCAG-AA colour remediation (follow-up PR)",
    themes: ["light"],
  },
  {
    fg: "--color-file-hover-border",
    category: "pending",
    why: "fails the threshold against the page surface it is painted on",
    issue: "WCAG-AA colour remediation (follow-up PR)",
    themes: ["light"],
  },
  {
    fg: "--color-flame-tooltip-label",
    category: "pending",
    why: "fails the threshold against the page surface it is painted on",
    issue: "WCAG-AA colour remediation (follow-up PR)",
    themes: ["light"],
  },
  {
    fg: "--color-focus-ring",
    category: "pending",
    why: "fails the threshold against the page surface it is painted on",
    issue: "WCAG-AA colour remediation (follow-up PR)",
    themes: ["dark"],
  },
  {
    fg: "--color-icon-chip-error-text",
    bg: "--color-icon-chip-error-bg",
    under: ["--color-surface-base"],
    category: "pending",
    why: "an icon chip's glyph is painted on the chip's fill",
    issue: "WCAG-AA colour remediation (follow-up PR)",
    themes: ["light"],
  },
  {
    fg: "--color-icon-chip-success-text",
    bg: "--color-icon-chip-success-bg",
    under: ["--color-surface-base"],
    category: "pending",
    why: "an icon chip's glyph is painted on the chip's fill",
    issue: "WCAG-AA colour remediation (follow-up PR)",
    themes: ["light"],
  },
  {
    fg: "--color-icon-color",
    category: "pending",
    why: "fails the threshold against the page surface it is painted on",
    issue: "WCAG-AA colour remediation (follow-up PR)",
    themes: ["dark"],
  },
  {
    fg: "--color-input-border-focus",
    category: "pending",
    why: "fails the threshold against the page surface it is painted on",
    issue: "WCAG-AA colour remediation (follow-up PR)",
    themes: ["light"],
  },
  {
    fg: "--color-input-border-hover",
    category: "pending",
    why: "fails the threshold against the page surface it is painted on",
    issue: "WCAG-AA colour remediation (follow-up PR)",
    themes: ["light"],
  },
  {
    fg: "--color-label-chip-email-text",
    bg: "--color-label-chip-email-bg",
    category: "pending",
    why: "a value chip's label is painted on the chip",
    issue: "WCAG-AA colour remediation (follow-up PR)",
    themes: ["light"],
  },
  {
    fg: "--color-label-chip-hex-text",
    bg: "--color-label-chip-hex-bg",
    category: "pending",
    why: "a value chip's label is painted on the chip",
    issue: "WCAG-AA colour remediation (follow-up PR)",
    themes: ["light"],
  },
  {
    fg: "--color-label-chip-ip-text",
    bg: "--color-label-chip-ip-bg",
    category: "pending",
    why: "a value chip's label is painted on the chip",
    issue: "WCAG-AA colour remediation (follow-up PR)",
    themes: ["light"],
  },
  {
    fg: "--color-label-chip-ts-text",
    bg: "--color-label-chip-ts-bg",
    category: "pending",
    why: "a value chip's label is painted on the chip",
    issue: "WCAG-AA colour remediation (follow-up PR)",
    themes: ["dark"],
  },
  {
    fg: "--color-lang-promql-text",
    bg: "--color-lang-promql-bg",
    under: ["--color-surface-base"],
    category: "pending",
    why: "a language pill's label is painted on the translucent pill",
    issue: "WCAG-AA colour remediation (follow-up PR)",
    themes: ["light"],
  },
  {
    fg: "--color-lang-sql-text",
    bg: "--color-lang-sql-bg",
    under: ["--color-surface-base"],
    category: "pending",
    why: "a language pill's label is painted on the translucent pill",
    issue: "WCAG-AA colour remediation (follow-up PR)",
  },
  {
    fg: "--color-lang-vrl-text",
    bg: "--color-lang-vrl-bg",
    under: ["--color-surface-base"],
    category: "pending",
    why: "a language pill's label is painted on the translucent pill",
    issue: "WCAG-AA colour remediation (follow-up PR)",
    themes: ["light"],
  },
  {
    fg: "--color-option-group-error-text",
    category: "pending",
    why: "fails the threshold against the page surface it is painted on",
    issue: "WCAG-AA colour remediation (follow-up PR)",
    themes: ["dark"],
  },
  {
    fg: "--color-pagination-item-active-text",
    bg: "--color-pagination-item-active-bg",
    category: "pending",
    why: "the current page number sits on the active fill",
    issue: "WCAG-AA colour remediation (follow-up PR)",
    themes: ["dark"],
  },
  {
    fg: "--color-progress-bar-label",
    bg: "--color-progress-bar-track",
    category: "pending",
    why: "the percentage is drawn inside the bar's track",
    issue: "WCAG-AA colour remediation (follow-up PR)",
    themes: ["light"],
  },
  {
    fg: "--color-promo-webinar-accent-text",
    category: "pending",
    why: "fails the threshold against the page surface it is painted on",
    issue: "WCAG-AA colour remediation (follow-up PR)",
    themes: ["dark"],
  },
  {
    fg: "--color-promo-webinar-link",
    category: "pending",
    why: "fails the threshold against the page surface it is painted on",
    issue: "WCAG-AA colour remediation (follow-up PR)",
    themes: ["dark"],
  },
  {
    fg: "--color-promo-webinar-link-hover",
    category: "pending",
    why: "fails the threshold against the page surface it is painted on",
    issue: "WCAG-AA colour remediation (follow-up PR)",
    themes: ["dark"],
  },
  {
    fg: "--color-radio-hover-border",
    category: "pending",
    why: "fails the threshold against the page surface it is painted on",
    issue: "WCAG-AA colour remediation (follow-up PR)",
    themes: ["dark"],
  },
  {
    fg: "--color-refresh-dot-fresh",
    category: "pending",
    why: "fails the threshold against the page surface it is painted on",
    issue: "WCAG-AA colour remediation (follow-up PR)",
    themes: ["light"],
  },
  {
    fg: "--color-refresh-dot-stale",
    category: "pending",
    why: "fails the threshold against the page surface it is painted on",
    issue: "WCAG-AA colour remediation (follow-up PR)",
    themes: ["light"],
  },
  {
    fg: "--color-select-border-focus",
    category: "pending",
    why: "fails the threshold against the page surface it is painted on",
    issue: "WCAG-AA colour remediation (follow-up PR)",
    themes: ["light"],
  },
  {
    fg: "--color-select-border-hover",
    category: "pending",
    why: "fails the threshold against the page surface it is painted on",
    issue: "WCAG-AA colour remediation (follow-up PR)",
    themes: ["light"],
  },
  {
    fg: "--color-slider-error-text",
    category: "pending",
    why: "fails the threshold against the page surface it is painted on",
    issue: "WCAG-AA colour remediation (follow-up PR)",
    themes: ["dark"],
  },
  {
    fg: "--color-status-info-text",
    bg: "--color-status-info-bg",
    category: "text",
    why: "a chip/badge label painted on its own -bg sibling (AlertInsights.vue filter chips, TraceTree.vue HTTP-status legend), not the page — the real backdrop is darker than --color-surface-base, so it is the pair that must clear 4.5:1",
  },
  {
    fg: "--color-stepper-indicator-default",
    category: "pending",
    why: "fails the threshold against the page surface it is painted on",
    issue: "WCAG-AA colour remediation (follow-up PR)",
  },
  {
    fg: "--color-syntax-builtin",
    bg: "--color-syntax-bg",
    category: "pending",
    why: "syntax colours are painted on the code block, not the page",
    issue: "WCAG-AA colour remediation (follow-up PR)",
    themes: ["light"],
  },
  {
    fg: "--color-text-inverse",
    bg: "--color-button-primary",
    category: "pending",
    why: "the inverse foreground exists for filled controls, and the primary button is the fill it is sized against",
    issue: "WCAG-AA colour remediation (follow-up PR)",
    themes: ["dark"],
  },
  {
    fg: "--color-text-label",
    category: "pending",
    why: "fails the threshold against the page surface it is painted on",
    issue: "WCAG-AA colour remediation (follow-up PR)",
  },
  {
    fg: "--color-text-muted",
    category: "pending",
    why: "fails the threshold against the page surface it is painted on",
    issue: "WCAG-AA colour remediation (follow-up PR)",
  },
  {
    fg: "--color-text-placeholder",
    category: "pending",
    why: "fails the threshold against the page surface it is painted on",
    issue: "WCAG-AA colour remediation (follow-up PR)",
  },
  {
    fg: "--color-thread-tool-link",
    category: "pending",
    why: "fails the threshold against the page surface it is painted on",
    issue: "WCAG-AA colour remediation (follow-up PR)",
    themes: ["light"],
  },
  {
    fg: "--color-timeline-dot-muted",
    category: "pending",
    why: "fails the threshold against the page surface it is painted on",
    issue: "WCAG-AA colour remediation (follow-up PR)",
    themes: ["light"],
  },
  {
    fg: "--color-timeline-dot-success",
    category: "pending",
    why: "fails the threshold against the page surface it is painted on",
    issue: "WCAG-AA colour remediation (follow-up PR)",
    themes: ["light"],
  },
  {
    fg: "--color-toast-warning-icon",
    category: "pending",
    why: "fails the threshold against the page surface it is painted on",
    issue: "WCAG-AA colour remediation (follow-up PR)",
    themes: ["light"],
  },
  {
    fg: "--color-toggle-border",
    category: "pending",
    why: "fails the threshold against the page surface it is painted on",
    issue: "WCAG-AA colour remediation (follow-up PR)",
    themes: ["dark"],
  },
  {
    fg: "--color-badge-blue-solid-text",
    bg: "--color-badge-blue-solid-bg",
    category: "text",
    why: "a badge label is painted on the badge's own solid fill, never on the page",
  },
  {
    fg: "--color-badge-default-solid-text",
    bg: "--color-badge-default-solid-bg",
    category: "text",
    why: "a badge label is painted on the badge's own solid fill, never on the page",
  },
  {
    fg: "--color-badge-error-solid-text",
    bg: "--color-badge-error-solid-bg",
    category: "text",
    why: "a badge label is painted on the badge's own solid fill, never on the page",
  },
  {
    fg: "--color-badge-indigo-solid-text",
    bg: "--color-badge-indigo-solid-bg",
    category: "text",
    why: "a badge label is painted on the badge's own solid fill, never on the page",
  },
  {
    fg: "--color-badge-primary-solid-text",
    bg: "--color-badge-primary-solid-bg",
    category: "text",
    why: "a badge label is painted on the badge's own solid fill, never on the page",
  },
  {
    fg: "--color-badge-purple-solid-text",
    bg: "--color-badge-purple-solid-bg",
    category: "text",
    why: "a badge label is painted on the badge's own solid fill, never on the page",
  },
  {
    fg: "--color-badge-warning-solid-text",
    bg: "--color-badge-warning-solid-bg",
    category: "text",
    why: "a badge label is painted on the badge's own solid fill, never on the page",
  },
  {
    fg: "--color-banner-error-text",
    bg: "--color-banner-error-bg",
    category: "text",
    why: "an error banner paints its text on the banner fill",
  },
  {
    fg: "--color-brand-msg-text",
    bg: "--color-brand-msg-bg",
    category: "text",
    why: "a chat-preview message renders on the mock message surface",
  },
  {
    fg: "--color-brand-msg-text-dark",
    bg: "--color-brand-msg-bg",
    category: "text",
    why: "a chat-preview message renders on the mock message surface",
  },
  {
    fg: "--color-brand-msg-text-strong",
    bg: "--color-brand-msg-bg",
    category: "text",
    why: "a chat-preview message renders on the mock message surface",
  },
  {
    fg: "--color-brand-slack-link",
    bg: "--color-brand-msg-bg",
    category: "text",
    why: "the Slack preview renders on the mock message surface",
  },
  {
    fg: "--color-brand-slack-text",
    bg: "--color-brand-msg-bg",
    category: "text",
    why: "the Slack preview renders on the mock message surface",
  },
  {
    fg: "--color-brand-teams-text",
    bg: "--color-brand-teams-bg",
    category: "text",
    why: "the Teams preview renders on the Teams surface",
  },
  {
    fg: "--color-button-destructive-foreground",
    bg: "--color-button-destructive",
    category: "text",
    why: "a filled button's label sits on the button",
  },
  {
    fg: "--color-button-primary-foreground",
    bg: "--color-button-primary",
    category: "text",
    why: "a filled button's label sits on the button",
  },
  {
    fg: "--color-button-warning-foreground",
    bg: "--color-button-warning",
    category: "text",
    why: "a filled button's label sits on the button",
  },
  {
    fg: "--color-checkbox-checked-fg",
    bg: "--color-checkbox-checked-bg",
    category: "text",
    why: "the tick is drawn inside the checked box",
  },
  {
    fg: "--color-dag-node-agent-text",
    bg: "--color-dag-node-agent-bg",
    category: "text",
    why: "a DAG node's label is painted on that node's fill inside the graph",
  },
  {
    fg: "--color-dag-node-chain-text",
    bg: "--color-dag-node-chain-bg",
    category: "text",
    why: "a DAG node's label is painted on that node's fill inside the graph",
  },
  {
    fg: "--color-dag-node-default-text",
    bg: "--color-dag-node-default-bg",
    category: "text",
    why: "a DAG node's label is painted on that node's fill inside the graph",
  },
  {
    fg: "--color-dag-node-embedding-text",
    bg: "--color-dag-node-embedding-bg",
    category: "text",
    why: "a DAG node's label is painted on that node's fill inside the graph",
  },
  {
    fg: "--color-dag-node-evaluator-text",
    bg: "--color-dag-node-evaluator-bg",
    category: "text",
    why: "a DAG node's label is painted on that node's fill inside the graph",
  },
  {
    fg: "--color-dag-node-event-text",
    bg: "--color-dag-node-event-bg",
    category: "text",
    why: "a DAG node's label is painted on that node's fill inside the graph",
  },
  {
    fg: "--color-dag-node-generation-text",
    bg: "--color-dag-node-generation-bg",
    category: "text",
    why: "a DAG node's label is painted on that node's fill inside the graph",
  },
  {
    fg: "--color-dag-node-guardrail-text",
    bg: "--color-dag-node-guardrail-bg",
    category: "text",
    why: "a DAG node's label is painted on that node's fill inside the graph",
  },
  {
    fg: "--color-dag-node-rerank-text",
    bg: "--color-dag-node-rerank-bg",
    category: "text",
    why: "a DAG node's label is painted on that node's fill inside the graph",
  },
  {
    fg: "--color-dag-node-retriever-text",
    bg: "--color-dag-node-retriever-bg",
    category: "text",
    why: "a DAG node's label is painted on that node's fill inside the graph",
  },
  {
    fg: "--color-dag-node-task-text",
    bg: "--color-dag-node-task-bg",
    category: "text",
    why: "a DAG node's label is painted on that node's fill inside the graph",
  },
  {
    fg: "--color-dag-node-tool-text",
    bg: "--color-dag-node-tool-bg",
    category: "text",
    why: "a DAG node's label is painted on that node's fill inside the graph",
  },
  {
    fg: "--color-dag-node-workflow-text",
    bg: "--color-dag-node-workflow-bg",
    category: "text",
    why: "a DAG node's label is painted on that node's fill inside the graph",
  },
  {
    fg: "--color-datepicker-clock-header-text",
    bg: "--color-datepicker-clock-header-bg",
    category: "text",
    why: "the clock header carries its own fill",
  },
  {
    fg: "--color-datepicker-clock-selected-text",
    bg: "--color-datepicker-clock-selected-bg",
    category: "text",
    why: "a selected clock number sits on the selection fill",
  },
  {
    fg: "--color-datepicker-day-selected-text",
    bg: "--color-datepicker-day-selected-bg",
    category: "text",
    why: "a selected day sits on the selection fill",
  },
  {
    fg: "--color-datepicker-relative-btn-selected-text",
    bg: "--color-datepicker-relative-btn-selected-bg",
    category: "text",
    why: "a selected preset sits on the selection fill",
  },
  {
    fg: "--color-datepicker-segment-focus-text",
    bg: "--color-datepicker-segment-focus-bg",
    category: "text",
    why: "a focused date segment is highlighted behind the digits",
  },
  {
    fg: "--color-error-tag-text",
    bg: "--color-error-tag-bg",
    category: "text",
    why: "an error tag is a filled pill",
  },
  {
    fg: "--color-field-type-boolean-text",
    bg: "--color-field-type-boolean-bg",
    category: "text",
    why: "a field-type tag is a filled chip in the field list",
  },
  {
    fg: "--color-field-type-float-text",
    bg: "--color-field-type-float-bg",
    category: "text",
    why: "a field-type tag is a filled chip in the field list",
  },
  {
    fg: "--color-field-type-number-text",
    bg: "--color-field-type-number-bg",
    category: "text",
    why: "a field-type tag is a filled chip in the field list",
  },
  {
    fg: "--color-field-type-string-text",
    bg: "--color-field-type-string-bg",
    category: "text",
    why: "a field-type tag is a filled chip in the field list",
  },
  {
    fg: "--color-field-type-timestamp-text",
    bg: "--color-field-type-timestamp-bg",
    category: "text",
    why: "a field-type tag is a filled chip in the field list",
  },
  {
    fg: "--color-icon-chip-error-text",
    bg: "--color-icon-chip-error-bg",
    under: ["--color-surface-base"],
    category: "text",
    why: "an icon chip's glyph is painted on the chip's fill",
  },
  {
    fg: "--color-icon-chip-info-text",
    bg: "--color-icon-chip-info-bg",
    under: ["--color-surface-base"],
    category: "text",
    why: "an icon chip's glyph is painted on the chip's fill",
  },
  {
    fg: "--color-icon-chip-orange-text",
    bg: "--color-icon-chip-orange-bg",
    under: ["--color-surface-base"],
    category: "text",
    why: "an icon chip's glyph is painted on the chip's fill",
  },
  {
    fg: "--color-icon-chip-primary-text",
    bg: "--color-icon-chip-primary-bg",
    under: ["--color-surface-base"],
    category: "text",
    why: "an icon chip's glyph is painted on the chip's fill",
  },
  {
    fg: "--color-icon-chip-success-text",
    bg: "--color-icon-chip-success-bg",
    under: ["--color-surface-base"],
    category: "text",
    why: "an icon chip's glyph is painted on the chip's fill",
  },
  {
    fg: "--color-icon-chip-warning-text",
    bg: "--color-icon-chip-warning-bg",
    under: ["--color-surface-base"],
    category: "text",
    why: "an icon chip's glyph is painted on the chip's fill",
  },
  {
    fg: "--color-label-chip-default-text",
    bg: "--color-label-chip-default-bg",
    category: "text",
    why: "a value chip's label is painted on the chip",
  },
  {
    fg: "--color-label-chip-email-text",
    bg: "--color-label-chip-email-bg",
    category: "text",
    why: "a value chip's label is painted on the chip",
  },
  {
    fg: "--color-label-chip-float-text",
    bg: "--color-label-chip-float-bg",
    category: "text",
    why: "a value chip's label is painted on the chip",
  },
  {
    fg: "--color-label-chip-hex-text",
    bg: "--color-label-chip-hex-bg",
    category: "text",
    why: "a value chip's label is painted on the chip",
  },
  {
    fg: "--color-label-chip-id-text",
    bg: "--color-label-chip-id-bg",
    category: "text",
    why: "a value chip's label is painted on the chip",
  },
  {
    fg: "--color-label-chip-ip-text",
    bg: "--color-label-chip-ip-bg",
    category: "text",
    why: "a value chip's label is painted on the chip",
  },
  {
    fg: "--color-label-chip-method-text",
    bg: "--color-label-chip-method-bg",
    category: "text",
    why: "a value chip's label is painted on the chip",
  },
  {
    fg: "--color-label-chip-num-text",
    bg: "--color-label-chip-num-bg",
    category: "text",
    why: "a value chip's label is painted on the chip",
  },
  {
    fg: "--color-label-chip-pattern-text",
    bg: "--color-label-chip-pattern-bg",
    category: "text",
    why: "a value chip's label is painted on the chip",
  },
  {
    fg: "--color-label-chip-str-text",
    bg: "--color-label-chip-str-bg",
    category: "text",
    why: "a value chip's label is painted on the chip",
  },
  {
    fg: "--color-label-chip-ts-text",
    bg: "--color-label-chip-ts-bg",
    category: "text",
    why: "a value chip's label is painted on the chip",
  },
  {
    fg: "--color-label-chip-url-text",
    bg: "--color-label-chip-url-bg",
    category: "text",
    why: "a value chip's label is painted on the chip",
  },
  {
    fg: "--color-lang-promql-text",
    bg: "--color-lang-promql-bg",
    under: ["--color-surface-base"],
    category: "text",
    why: "a language pill's label is painted on the translucent pill",
  },
  {
    fg: "--color-lang-vrl-text",
    bg: "--color-lang-vrl-bg",
    under: ["--color-surface-base"],
    category: "text",
    why: "a language pill's label is painted on the translucent pill",
  },
  {
    fg: "--color-pagination-item-active-text",
    bg: "--color-pagination-item-active-bg",
    category: "text",
    why: "the current page number sits on the active fill",
  },
  {
    fg: "--color-progress-bar-label",
    bg: "--color-progress-bar-track",
    category: "text",
    why: "the percentage is drawn inside the bar's track",
  },
  {
    fg: "--color-promo-webinar-text",
    bg: "--color-promo-webinar-accent",
    category: "text",
    why: "the promo bar paints its text on the accent fill",
  },
  {
    fg: "--color-syntax-builtin",
    bg: "--color-syntax-bg",
    category: "text",
    why: "syntax colours are painted on the code block, not the page",
  },
  {
    fg: "--color-text-inverse",
    bg: "--color-button-primary",
    category: "text",
    why: "the inverse foreground exists for filled controls, and the primary button is the fill it is sized against",
  },
];
