version: v1
labels:
  -   label: '📒 Documentation'
      matcher:
          title: '\b(docs|doc:|\[doc\]|README|typos|comment|documentation)\b'
  -   label: '☢️ Bug'
      matcher:
          title: '\b(bug|fix|race|bug|missing|correct)\b'
  -   label: '🧹 Updates'
      matcher:
          title: '\b(improve|update|refactor|deprecated|remove|unused|test)\b'
  -   label: '🤖 Dependencies'
      matcher:
          title: '\b(bumb|dependencies)\b'
  -   label: '✏️ Feature'
      matcher:
          title: '\b(feature|feat|create|implement|add)\b'