//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "action_scripts")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub name: String,
    pub file_path: String,
    pub file_name: String,
    pub org_id: String,
    pub created_by: String,
    pub origin_cluster_url: String,
    pub env: Json,
    pub execution_details: String,
    pub cron_expr: Option<String>,
    pub created_at: i64,
    pub last_modified_at: i64,
    pub last_executed_at: Option<i64>,
    pub last_successful_at: Option<i64>,
    pub description: Option<String>,
    pub status: String,
    pub service_account: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_model_construction() {
        let m = Model {
            id: "script-1".to_string(),
            name: "my_script".to_string(),
            file_path: "/scripts".to_string(),
            file_name: "run.sh".to_string(),
            org_id: "org".to_string(),
            created_by: "user1".to_string(),
            origin_cluster_url: "http://cluster".to_string(),
            env: serde_json::json!({}),
            execution_details: "{}".to_string(),
            cron_expr: None,
            created_at: 1000,
            last_modified_at: 2000,
            last_executed_at: None,
            last_successful_at: None,
            description: None,
            status: "active".to_string(),
            service_account: "sa1".to_string(),
        };
        assert_eq!(m.org_id, "org");
        assert_eq!(m.status, "active");
        assert!(m.cron_expr.is_none());
    }
}
