//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "action_scripts")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub name: String,
    pub file_path: String,
    pub file_name: String,
    pub org_id: String,
    pub created_by: String,
    pub origin_cluster_url: String,
    pub env: Json,
    pub execution_details: String,
    pub cron_expr: Option<String>,
    pub created_at: i64,
    pub last_modified_at: i64,
    pub last_executed_at: Option<i64>,
    pub last_successful_at: Option<i64>,
    pub description: Option<String>,
    pub status: String,
    pub service_account: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
