//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "alerts")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub org: String,
    pub folder_id: String,
    pub name: String,
    pub stream_type: String,
    pub stream_name: String,
    pub is_real_time: bool,
    pub destinations: Json,
    pub template: Option<String>,
    pub context_attributes: Option<Json>,
    pub row_template: Option<String>,
    pub row_template_type: i16,
    pub description: Option<String>,
    pub enabled: bool,
    pub tz_offset: i32,
    pub last_triggered_at: Option<i64>,
    pub last_satisfied_at: Option<i64>,
    pub query_type: i16,
    pub query_conditions: Option<Json>,
    pub query_sql: Option<String>,
    pub query_promql: Option<String>,
    pub query_promql_condition: Option<Json>,
    pub query_aggregation: Option<Json>,
    pub query_vrl_function: Option<String>,
    pub query_search_event_type: Option<i16>,
    pub query_multi_time_range: Option<Json>,
    pub trigger_threshold_operator: String,
    pub trigger_period_seconds: i64,
    pub trigger_threshold_count: i64,
    pub trigger_frequency_type: i16,
    pub trigger_frequency_seconds: i64,
    pub trigger_frequency_cron: Option<String>,
    pub trigger_frequency_cron_timezone: Option<String>,
    pub trigger_silence_seconds: i64,
    pub trigger_tolerance_seconds: Option<i64>,
    pub owner: Option<String>,
    pub last_edited_by: Option<String>,
    pub updated_at: Option<i64>,
    pub align_time: bool,
    pub dedup_enabled: bool,
    pub dedup_time_window_minutes: Option<i32>,
    pub dedup_config: Option<Json>,
    pub creates_incident: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::folders::Entity",
        from = "Column::FolderId",
        to = "super::folders::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Folders,
}

impl Related<super::folders::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Folders.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_model_construction() {
        let m = Model {
            id: "alert-1".to_string(),
            org: "myorg".to_string(),
            folder_id: "folder-1".to_string(),
            name: "High Error Rate".to_string(),
            stream_type: "logs".to_string(),
            stream_name: "default".to_string(),
            is_real_time: false,
            destinations: serde_json::json!(["dest-1"]),
            template: None,
            context_attributes: None,
            row_template: None,
            row_template_type: 0,
            description: Some("Alert on high error rate".to_string()),
            enabled: true,
            tz_offset: 0,
            last_triggered_at: None,
            last_satisfied_at: None,
            query_type: 0,
            query_conditions: None,
            query_sql: Some("SELECT count(*) FROM logs".to_string()),
            query_promql: None,
            query_promql_condition: None,
            query_aggregation: None,
            query_vrl_function: None,
            query_search_event_type: None,
            query_multi_time_range: None,
            trigger_threshold_operator: ">".to_string(),
            trigger_period_seconds: 60,
            trigger_threshold_count: 10,
            trigger_frequency_type: 0,
            trigger_frequency_seconds: 300,
            trigger_frequency_cron: None,
            trigger_frequency_cron_timezone: None,
            trigger_silence_seconds: 600,
            trigger_tolerance_seconds: None,
            owner: Some("admin@example.com".to_string()),
            last_edited_by: None,
            updated_at: Some(1000),
            align_time: false,
            dedup_enabled: false,
            dedup_time_window_minutes: None,
            dedup_config: None,
            creates_incident: false,
        };
        assert_eq!(m.id, "alert-1");
        assert_eq!(m.name, "High Error Rate");
        assert!(m.enabled);
        assert!(!m.creates_incident);
    }
}
