//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "compactor_manual_jobs")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub key: String,
    pub created_at: i64,
    pub ended_at: i64,
    pub status: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_model_construction() {
        let m = Model {
            id: "job-1".to_string(),
            key: "key-1".to_string(),
            created_at: 1000,
            ended_at: 2000,
            status: 0,
        };
        assert_eq!(m.id, "job-1");
        assert_eq!(m.status, 0);
        assert!(m.ended_at > m.created_at);
    }
}
