//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "dashboards")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub dashboard_id: String,
    pub folder_id: String,
    pub owner: String,
    pub role: Option<String>,
    pub title: String,
    pub description: Option<String>,
    pub data: Json,
    pub version: i32,
    pub created_at: i64,
    pub updated_at: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::folders::Entity",
        from = "Column::FolderId",
        to = "super::folders::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Folders,
    #[sea_orm(has_many = "super::report_dashboards::Entity")]
    ReportDashboards,
    #[sea_orm(has_many = "super::timed_annotations::Entity")]
    TimedAnnotations,
}

impl Related<super::folders::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Folders.def()
    }
}

impl Related<super::report_dashboards::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ReportDashboards.def()
    }
}

impl Related<super::timed_annotations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TimedAnnotations.def()
    }
}

impl Related<super::reports::Entity> for Entity {
    fn to() -> RelationDef {
        super::report_dashboards::Relation::Reports.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::report_dashboards::Relation::Dashboards.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_model_construction() {
        let m = Model {
            id: "d-1".to_string(),
            dashboard_id: "dash-001".to_string(),
            folder_id: "folder-1".to_string(),
            owner: "admin@example.com".to_string(),
            role: None,
            title: "My Dashboard".to_string(),
            description: Some("A test dashboard".to_string()),
            data: serde_json::json!({"panels": []}),
            version: 1,
            created_at: 1000,
            updated_at: 2000,
        };
        assert_eq!(m.id, "d-1");
        assert_eq!(m.title, "My Dashboard");
        assert_eq!(m.version, 1);
        assert!(m.role.is_none());
    }
}
