//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "distinct_value_fields")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub origin: String,
    #[sea_orm(primary_key, auto_increment = false)]
    pub origin_id: String,
    #[sea_orm(primary_key, auto_increment = false)]
    pub org_name: String,
    #[sea_orm(primary_key, auto_increment = false)]
    pub stream_name: String,
    #[sea_orm(primary_key, auto_increment = false)]
    pub stream_type: String,
    #[sea_orm(primary_key, auto_increment = false)]
    pub field_name: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_model_construction() {
        let m = Model {
            origin: "alert".to_string(),
            origin_id: "alert-1".to_string(),
            org_name: "myorg".to_string(),
            stream_name: "default".to_string(),
            stream_type: "logs".to_string(),
            field_name: "status".to_string(),
        };
        assert_eq!(m.origin, "alert");
        assert_eq!(m.origin_id, "alert-1");
        assert_eq!(m.stream_type, "logs");
        assert_eq!(m.field_name, "status");
    }
}
