//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "enrichment_table_urls")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String, // KSUID (27 chars)
    pub org: String,
    pub name: String,
    pub url: String,
    pub status: i16,
    pub error_message: Option<String>,
    pub created_at: i64,
    pub updated_at: i64,
    pub total_bytes_fetched: i64,
    pub total_records_processed: i64,
    pub retry_count: i32,
    pub append_data: bool,
    pub last_byte_position: i64,
    pub supports_range: bool,
    pub is_local_region: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_model_construction() {
        let m = Model {
            id: "ksuid-001".to_string(),
            org: "myorg".to_string(),
            name: "enrichment1".to_string(),
            url: "https://example.com/data.csv".to_string(),
            status: 1,
            error_message: None,
            created_at: 1000,
            updated_at: 2000,
            total_bytes_fetched: 512,
            total_records_processed: 10,
            retry_count: 0,
            append_data: false,
            last_byte_position: 512,
            supports_range: true,
            is_local_region: false,
        };
        assert_eq!(m.id, "ksuid-001");
        assert_eq!(m.total_records_processed, 10);
        assert!(m.error_message.is_none());
    }
}
