//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "enrichment_table_urls")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub org: String,
    pub name: String,
    pub url: String,
    pub status: i16,
    pub error_message: Option<String>,
    pub created_at: i64,
    pub updated_at: i64,
    pub total_bytes_fetched: i64,
    pub total_records_processed: i64,
    pub retry_count: i32,
    pub append_data: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
