//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "enrichment_tables")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub org: String,
    pub name: String,
    pub data: Vec<u8>,
    pub created_at: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_model_construction() {
        let m = Model {
            id: 1,
            org: "myorg".to_string(),
            name: "geo_lookup".to_string(),
            data: vec![1, 2, 3],
            created_at: 1000,
        };
        assert_eq!(m.id, 1);
        assert_eq!(m.name, "geo_lookup");
        assert_eq!(m.data.len(), 3);
    }
}
