//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "file_list_dump")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub org: String,
    pub stream: String,
    pub start_ts: i64,
    pub end_ts: i64,
    pub file: String,
    pub records: i64,
    pub original_size: i64,
    pub compressed_size: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
