//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "folders")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub org: String,
    pub folder_id: String,
    pub name: String,
    pub description: Option<String>,
    pub r#type: i16,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::alerts::Entity")]
    Alerts,
    #[sea_orm(has_many = "super::dashboards::Entity")]
    Dashboards,
    #[sea_orm(has_many = "super::reports::Entity")]
    Reports,
}

impl Related<super::alerts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Alerts.def()
    }
}

impl Related<super::dashboards::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Dashboards.def()
    }
}

impl Related<super::reports::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Reports.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_model_construction() {
        let m = Model {
            id: "folder-1".to_string(),
            org: "myorg".to_string(),
            folder_id: "fid-1".to_string(),
            name: "My Folder".to_string(),
            description: Some("test folder".to_string()),
            r#type: 1,
        };
        assert_eq!(m.id, "folder-1");
        assert_eq!(m.org, "myorg");
        assert_eq!(m.name, "My Folder");
        assert_eq!(m.r#type, 1);
        assert!(m.description.is_some());
    }
}
