//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

pub mod prelude;

pub mod background_job_partitions;
pub mod background_job_results;
pub mod background_jobs;
pub mod alerts;
pub mod dashboards;
pub mod distinct_value_fields;
pub mod folders;
pub mod search_queue;
