//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "org_users")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub email: String,
    pub org_id: String,
    pub role: i16,
    pub token: String,
    pub rum_token: Option<String>,
    pub created_at: i64,
    pub updated_at: i64,
    pub allow_static_token: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::organizations::Entity",
        from = "Column::OrgId",
        to = "super::organizations::Column::Identifier",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Organizations,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::Email",
        to = "super::users::Column::Email",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Users,
}

impl Related<super::organizations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Organizations.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_model_construction() {
        let m = Model {
            id: "id-1".to_string(),
            email: "user@example.com".to_string(),
            org_id: "org-1".to_string(),
            role: 1,
            token: "tok-abc".to_string(),
            rum_token: Some("rum-tok".to_string()),
            created_at: 1000,
            updated_at: 2000,
            allow_static_token: true,
        };
        assert_eq!(m.email, "user@example.com");
        assert_eq!(m.role, 1);
        assert!(m.allow_static_token);
    }
}
