//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "organizations")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub identifier: String,
    pub org_name: String,
    pub org_type: i16,
    pub created_at: i64,
    pub updated_at: i64,
    #[cfg(feature = "cloud")]
    pub trial_ends_at: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::org_users::Entity")]
    OrgUsers,
}

impl Related<super::org_users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::OrgUsers.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
