//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "organizations")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub identifier: String,
    pub org_name: String,
    pub org_type: i16,
    pub created_at: i64,
    pub updated_at: i64,
    #[cfg(feature = "cloud")]
    pub trial_ends_at: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::org_users::Entity")]
    OrgUsers,
}

impl Related<super::org_users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::OrgUsers.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    #[cfg(not(feature = "cloud"))]
    fn test_model_construction() {
        let m = Model {
            identifier: "myorg".to_string(),
            org_name: "My Organization".to_string(),
            org_type: 1,
            created_at: 1000,
            updated_at: 2000,
        };
        assert_eq!(m.identifier, "myorg");
        assert_eq!(m.org_name, "My Organization");
        assert_eq!(m.org_type, 1);
    }

    #[test]
    #[cfg(feature = "cloud")]
    fn test_model_construction_cloud() {
        let m = Model {
            identifier: "myorg".to_string(),
            org_name: "My Organization".to_string(),
            org_type: 1,
            created_at: 1000,
            updated_at: 2000,
            trial_ends_at: 3000,
        };
        assert_eq!(m.identifier, "myorg");
        assert_eq!(m.trial_ends_at, 3000);
    }
}
