//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

pub use super::{
    alerts::Entity as Alerts, dashboards::Entity as Dashboards,
    distinct_value_fields::Entity as DistinctValueFields, folders::Entity as Folders,
    search_job_partitions::Entity as SearchJobPartitions,
    search_job_results::Entity as SearchJobResults, search_jobs::Entity as SearchJobs,
    search_queue::Entity as SearchQueue,
};
