//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "rate_limit_rules")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub rule_id: String,
    pub org: String,
    pub rule_type: String,
    pub user_role: String,
    pub user_id: String,
    pub api_group_name: String,
    pub api_group_operation: String,
    pub threshold: i32,
    pub stat_interval_ms: i64,
    pub created_at: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
