//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "rate_limit_rules")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub rule_id: String,
    pub org: String,
    pub rule_type: String,
    pub user_role: String,
    pub user_id: String,
    pub api_group_name: String,
    pub api_group_operation: String,
    pub threshold: i32,
    pub stat_interval_ms: i64,
    pub created_at: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_model_construction() {
        let m = Model {
            rule_id: "rule-1".to_string(),
            org: "myorg".to_string(),
            rule_type: "user".to_string(),
            user_role: "admin".to_string(),
            user_id: "user@example.com".to_string(),
            api_group_name: "search".to_string(),
            api_group_operation: "read".to_string(),
            threshold: 100,
            stat_interval_ms: 60000,
            created_at: 1000,
        };
        assert_eq!(m.rule_id, "rule-1");
        assert_eq!(m.org, "myorg");
        assert_eq!(m.threshold, 100);
        assert_eq!(m.stat_interval_ms, 60000);
    }
}
