//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "rate_limit_rules")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub rule_id: String,
    pub org: String,
    pub rule_type: String,
    pub resource: String,
    #[sea_orm(column_type = "Double")]
    pub threshold: f64,
    pub created_at: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
