//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "re_patterns")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub org: String,
    pub name: String,
    #[sea_orm(column_type = "Text")]
    pub description: String,
    pub created_by: String,
    pub created_at: i64,
    pub updated_at: i64,
    #[sea_orm(column_type = "Text")]
    pub pattern: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::re_pattern_stream_map::Entity")]
    RePatternStreamMap,
}

impl Related<super::re_pattern_stream_map::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RePatternStreamMap.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
