//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "report_dashboards")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub report_id: String,
    #[sea_orm(primary_key, auto_increment = false)]
    pub dashboard_id: String,
    pub tab_names: Json,
    pub variables: Json,
    pub timerange: Json,
    /// 0 = PDF (default), 1 = PNG
    pub report_type: i16,
    /// 0 = Standard (default), 1 = Inline
    pub email_attachment_type: i16,
    /// Optional JSON object with `width` and `height` fields (u32).
    /// When NULL the report server uses its configured defaults.
    pub attachment_dimensions: Option<Json>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::dashboards::Entity",
        from = "Column::DashboardId",
        to = "super::dashboards::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Dashboards,
    #[sea_orm(
        belongs_to = "super::reports::Entity",
        from = "Column::ReportId",
        to = "super::reports::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Reports,
}

impl Related<super::dashboards::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Dashboards.def()
    }
}

impl Related<super::reports::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Reports.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_model_construction() {
        let m = Model {
            report_id: "r-1".to_string(),
            dashboard_id: "d-1".to_string(),
            tab_names: serde_json::json!(["tab1"]),
            variables: serde_json::json!({}),
            timerange: serde_json::json!({"from": "now-1h"}),
            report_type: 0,
            email_attachment_type: 0,
            attachment_dimensions: None,
        };
        assert_eq!(m.report_id, "r-1");
        assert_eq!(m.report_type, 0);
        assert!(m.attachment_dimensions.is_none());
    }
}
