//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "reports")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub org: String,
    pub folder_id: String,
    pub name: String,
    pub title: String,
    pub description: Option<String>,
    pub enabled: bool,
    pub frequency: Json,
    pub destinations: Json,
    pub message: Option<String>,
    pub timezone: String,
    pub tz_offset: i32,
    pub owner: Option<String>,
    pub last_edited_by: Option<String>,
    pub created_at: i64,
    pub updated_at: Option<i64>,
    pub start_at: i64,
    pub image_preview: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::folders::Entity",
        from = "Column::FolderId",
        to = "super::folders::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Folders,
    #[sea_orm(has_many = "super::report_dashboards::Entity")]
    ReportDashboards,
}

impl Related<super::folders::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Folders.def()
    }
}

impl Related<super::report_dashboards::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ReportDashboards.def()
    }
}

impl Related<super::dashboards::Entity> for Entity {
    fn to() -> RelationDef {
        super::report_dashboards::Relation::Dashboards.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::report_dashboards::Relation::Reports.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_model_construction() {
        let m = Model {
            id: "report-1".to_string(),
            org: "myorg".to_string(),
            folder_id: "folder-1".to_string(),
            name: "Weekly Report".to_string(),
            title: "Weekly Summary".to_string(),
            description: Some("A weekly report".to_string()),
            enabled: true,
            frequency: serde_json::json!({"type": "weekly", "day": "Monday"}),
            destinations: serde_json::json!(["email@example.com"]),
            message: None,
            timezone: "UTC".to_string(),
            tz_offset: 0,
            owner: Some("admin@example.com".to_string()),
            last_edited_by: None,
            created_at: 1000,
            updated_at: Some(2000),
            start_at: 1000,
            image_preview: false,
        };
        assert_eq!(m.id, "report-1");
        assert_eq!(m.org, "myorg");
        assert!(m.enabled);
        assert!(!m.image_preview);
        assert!(m.message.is_none());
    }
}
