//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "search_job_partitions")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub job_id: String,
    #[sea_orm(primary_key, auto_increment = false)]
    pub partition_id: i64,
    pub start_time: i64,
    pub end_time: i64,
    pub created_at: i64,
    pub started_at: Option<i64>,
    pub ended_at: Option<i64>,
    pub cluster: Option<String>,
    pub status: i64,
    pub result_path: Option<String>,
    pub error_message: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_model_construction() {
        let m = Model {
            job_id: "job-1".to_string(),
            partition_id: 0,
            start_time: 0,
            end_time: 1000,
            created_at: 100,
            started_at: None,
            ended_at: None,
            cluster: None,
            status: 0,
            result_path: None,
            error_message: None,
        };
        assert_eq!(m.job_id, "job-1");
        assert_eq!(m.partition_id, 0);
        assert!(m.started_at.is_none());
    }
}
