//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "search_queue")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub work_group: String,
    pub org_id: String,
    pub user_id: String,
    pub trace_id: String,
    pub created_at: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_model_construction() {
        let m = Model {
            id: 42,
            work_group: "global".to_string(),
            org_id: "org".to_string(),
            user_id: "user".to_string(),
            trace_id: "trace-1".to_string(),
            created_at: 1000,
        };
        assert_eq!(m.id, 42);
        assert_eq!(m.work_group, "global");
        assert_eq!(m.org_id, "org");
    }
}
