//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "search_jobs")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub trace_id: String,
    pub org_id: String,
    pub user_id: String,
    pub stream_type: String,
    pub stream_names: String,
    pub payload: String,
    pub start_time: i64,
    pub end_time: i64,
    pub created_at: i64,
    pub updated_at: i64,
    pub started_at: Option<i64>,
    pub ended_at: Option<i64>,
    pub cluster: Option<String>,
    pub node: Option<String>,
    pub status: i64,
    pub result_path: Option<String>,
    pub error_message: Option<String>,
    pub partition_num: Option<i64>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_model_construction() {
        let m = Model {
            id: "job-1".to_string(),
            trace_id: "trace-1".to_string(),
            org_id: "org".to_string(),
            user_id: "user".to_string(),
            stream_type: "logs".to_string(),
            stream_names: "stream1".to_string(),
            payload: "{}".to_string(),
            start_time: 0,
            end_time: 1000,
            created_at: 100,
            updated_at: 200,
            started_at: None,
            ended_at: None,
            cluster: None,
            node: None,
            status: 0,
            result_path: None,
            error_message: None,
            partition_num: None,
        };
        assert_eq!(m.org_id, "org");
        assert_eq!(m.status, 0);
        assert!(m.started_at.is_none());
    }
}
