//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "source_maps")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub org: String,
    pub service: Option<String>,
    pub env: Option<String>,
    pub version: Option<String>,
    pub source_file_name: String,
    pub source_map_file_name: String,
    pub file_store_id: String,
    pub file_type: i32,
    pub created_at: i64,
    pub is_local: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
