//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.4

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "system_prompts")]
pub struct Model {
    #[sea_orm(primary_key, column_type = "Text", unique, not_null)]
    pub r#type: String,
    #[sea_orm(column_type = "Text", not_null)]
    pub content: String,
    pub updated_at: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
