//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "templates")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub org: String,
    pub name: String,
    pub is_default: bool,
    pub r#type: String,
    pub body: String,
    pub title: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::destinations::Entity")]
    Destinations,
}

impl Related<super::destinations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Destinations.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_model_construction() {
        let m = Model {
            id: "tmpl-1".to_string(),
            org: "myorg".to_string(),
            name: "slack-template".to_string(),
            is_default: false,
            r#type: "slack".to_string(),
            body: r#"{"text": "Alert: {{.Name}}"}"#.to_string(),
            title: None,
        };
        assert_eq!(m.id, "tmpl-1");
        assert_eq!(m.org, "myorg");
        assert_eq!(m.r#type, "slack");
        assert!(!m.is_default);
        assert!(m.title.is_none());
    }
}
