//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "templates")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub org: String,
    pub name: String,
    pub is_default: bool,
    pub r#type: String,
    pub body: String,
    pub title: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::destinations::Entity")]
    Destinations,
}

impl Related<super::destinations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Destinations.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
