//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "timed_annotations")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub dashboard_id: String,
    pub start_time: i64,
    pub end_time: Option<i64>,
    pub title: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub text: Option<String>,
    pub tags: Json,
    pub created_at: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::dashboards::Entity",
        from = "Column::DashboardId",
        to = "super::dashboards::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Dashboards,
    #[sea_orm(has_many = "super::timed_annotation_panels::Entity")]
    TimedAnnotationPanels,
}

impl Related<super::dashboards::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Dashboards.def()
    }
}

impl Related<super::timed_annotation_panels::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TimedAnnotationPanels.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_model_construction() {
        let m = Model {
            id: "ann-1".to_string(),
            dashboard_id: "dash-1".to_string(),
            start_time: 1000,
            end_time: Some(2000),
            title: "Deploy v2.0".to_string(),
            text: Some("Production deployment".to_string()),
            tags: serde_json::json!(["deploy", "production"]),
            created_at: 1000,
        };
        assert_eq!(m.id, "ann-1");
        assert_eq!(m.dashboard_id, "dash-1");
        assert_eq!(m.start_time, 1000);
        assert_eq!(m.end_time, Some(2000));
        assert_eq!(m.title, "Deploy v2.0");
        assert!(m.text.is_some());
    }
}
