//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "users")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    #[sea_orm(unique)]
    pub email: String,
    pub first_name: String,
    pub last_name: String,
    pub password: String,
    pub salt: String,
    pub is_root: bool,
    pub password_ext: Option<String>,
    pub user_type: i16,
    pub created_at: i64,
    pub updated_at: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::org_users::Entity")]
    OrgUsers,
}

impl Related<super::org_users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::OrgUsers.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_model_construction() {
        let m = Model {
            id: "u-1".to_string(),
            email: "test@example.com".to_string(),
            first_name: "Test".to_string(),
            last_name: "User".to_string(),
            password: "hashed_pw".to_string(),
            salt: "salt_val".to_string(),
            is_root: false,
            password_ext: None,
            user_type: 0,
            created_at: 1000,
            updated_at: 2000,
        };
        assert_eq!(m.email, "test@example.com");
        assert!(!m.is_root);
        assert!(m.password_ext.is_none());
    }
}
