//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "users")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    #[sea_orm(unique)]
    pub email: String,
    pub first_name: String,
    pub last_name: String,
    pub password: String,
    pub salt: String,
    pub is_root: bool,
    pub password_ext: Option<String>,
    pub user_type: i16,
    pub created_at: i64,
    pub updated_at: i64,
    #[sea_orm(default_value = false)]
    pub must_reset_password: bool,
    #[sea_orm(nullable)]
    pub password_reset_reason: Option<String>,
    #[sea_orm(nullable)]
    pub flagged_at: Option<i64>,
    /// NULL only for rows written between the schema migration and the first password change;
    /// the rotation check treats it as never-expired rather than as the epoch.
    #[sea_orm(nullable)]
    pub password_updated_at: Option<i64>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::org_users::Entity")]
    OrgUsers,
    #[sea_orm(has_many = "super::user_password_history::Entity")]
    UserPasswordHistory,
    #[sea_orm(has_one = "super::user_auth_state::Entity")]
    UserAuthState,
}

impl Related<super::org_users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::OrgUsers.def()
    }
}

impl Related<super::user_password_history::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserPasswordHistory.def()
    }
}

impl Related<super::user_auth_state::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserAuthState.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
