//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "workflow_errors")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub cluster: String,
    pub org_id: String,
    pub workflow_id: String,
    pub run_id: String,
    pub ran_at: i64,
    pub data: String,
    pub input_data: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
