//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "workflow_associations")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub org_id: String,
    pub entity_id: String,
    pub entity_type: String,
    pub workflow_id: String,
    pub trigger_type: String,
    pub created_at: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
