/**
 * RUM Page Data Flow — Sessions & Performance
 *
 * Proves that RUM data generated by the real SDK surfaces on the RUM product
 * pages (beyond Error Tracking, which the CDN/NPM specs already cover):
 *   - The session recorded in this run lands in _sessionreplay (recording)
 *     and is listed on the Sessions page (row opens its session viewer)
 *   - Performance page renders its summary without a stuck loading state
 *
 * Self-contained: generates a session via the shared CDN sample fixture in
 * beforeAll, then verifies through the authenticated UI.
 *
 * Prerequisites:
 *   - OpenObserve ENTERPRISE build on ZO_BASE_URL (default http://localhost:5080)
 *   - Network access to the live CDN bundle; cross-origin RUM ingestion allowed
 */

const { test, expect } = require('../utils/enhanced-baseFixtures.js');
const testLogger = require('../utils/test-logger.js');
const { startFixtureServer } = require('../../fixtures/rum/serve.js');
const { getOrCreateRumToken } = require('../utils/rum-token-api.js');
const { resolveCdnSdkVersion } = require('../utils/rum-sdk-version.js');
const { driveRumSampleInteractions } = require('../utils/rum-traffic.js');
const { waitForStreamRows } = require('../utils/rum-stream-verify.js');

const ORG = process.env.ORGNAME || 'default';
const BASE = process.env.ZO_BASE_URL || 'http://localhost:5080';
const SITE = BASE.replace(/^https?:\/\//, '').replace(/\/$/, '');
const INSECURE = BASE.startsWith('http://');

const RUN_ID = Date.now();
const SERVICE = `e2e-rum-page-${RUN_ID}`;
// The SDK session generated for this run — captured in beforeAll and used to
// assert the Sessions page lists exactly this recording.
let sessionId = null;

test.describe('RUM Page Data Flow', { tag: '@enterprise' }, () => {
  test.describe.configure({ mode: 'serial' });

  test.beforeAll(async ({ browser }) => {
    // 1) token + CDN SDK version (browser-sdk README → RUM_SDK_VERSION → pinned)
    const tokenPage = await browser.newPage();
    const rumToken = await getOrCreateRumToken(tokenPage);
    const sdkVersion = await resolveCdnSdkVersion(tokenPage);
    await tokenPage.close();
    expect(rumToken, 'RUM token should be available').toBeTruthy();

    // 2) serve fixture + generate one real session (fixture app needs no OO auth)
    const server = await startFixtureServer({
      clientToken: rumToken,
      org: ORG,
      site: SITE,
      insecureHTTP: INSECURE,
      service: SERVICE,
      env: 'e2e',
      version: '1.0.0',
      applicationId: `e2e-rum-page-app-${RUN_ID}`,
      sdkVersion,
    });

    const genContext = await browser.newContext();
    const app = await genContext.newPage();
    await app.goto(server.url, { waitUntil: 'domcontentloaded' });
    await app
      .waitForResponse((r) => r.url().includes('browsersdk.openobserve.ai') && r.url().includes('openobserve-rum'), { timeout: 30000 })
      .catch(() => testLogger.warn('CDN rum bundle response not observed'));
    await app.waitForLoadState('networkidle', { timeout: 15000 }).catch(() => {});
    await driveRumSampleInteractions(app);
    await genContext.close();
    await server.close();

    // 3) wait for the data to be searchable before hitting the UI
    const tokenPage2 = await browser.newPage();
    const hits = await waitForStreamRows(tokenPage2, {
      sql: `SELECT * FROM "_rumdata" WHERE service = '${SERVICE}'`,
      minRows: 1,
      timeoutMs: 45000,
    });
    sessionId = hits[0]?.session_id || null;
    expect(sessionId, 'generated RUM events should carry a session_id').toBeTruthy();

    // 4) the session RECORDING must land too: replay segments in _sessionreplay.
    // The Sessions page only lists sessions with session_has_replay set, so
    // this is the precondition for the UI assertion below.
    const replayRows = await waitForStreamRows(tokenPage2, {
      sql: `SELECT * FROM "_sessionreplay" WHERE session_id = '${sessionId}'`,
      minRows: 1,
      timeoutMs: 45000,
    });
    await tokenPage2.close();
    expect(replayRows.length, `_sessionreplay should contain segments for session ${sessionId}`)
      .toBeGreaterThan(0);
    testLogger.info('RUM page dataflow setup complete', {
      service: SERVICE,
      sessionId,
      rumRows: hits.length,
      replayRows: replayRows.length,
    });
  });

  test('Sessions page lists the session recorded in this run', {
    tag: ['@rum', '@dataflow', '@ui', '@P0'],
  }, async ({ page }) => {
    // Scope the list to THIS run's session — the filter is applied to the
    // _rumdata sessions query, so any row that comes back is our recording.
    // Passed via the URL (?query= is base64, restored on mount) instead of
    // typing into the Monaco editor, which is racy while the editor boots.
    const filter = Buffer.from(`service='${SERVICE}'`).toString('base64');
    await page.goto(
      `${BASE}/web/rum/sessions?period=1h&query=${encodeURIComponent(filter)}&org_identifier=${ORG}`,
    );
    await page.waitForLoadState('networkidle', { timeout: 30000 }).catch(() => {});

    await expect(page.locator('[data-test="rum-sessions-table"]')).toBeVisible({ timeout: 15000 });
    // Session aggregation can lag ingestion; poll for the filtered row.
    await expect
      .poll(async () => page.locator('[data-test^="o2-table-row-"]').count(), {
        timeout: 60000,
        intervals: [2000, 3000, 5000],
      })
      .toBeGreaterThan(0);

    // Opening the row must land on the session viewer for the exact session
    // captured during generation — proves the listed row IS the new recording.
    await page.locator('[data-test^="o2-table-row-"]').first().click();
    await expect(page).toHaveURL(new RegExp(`/rum/sessions/view/${sessionId}`), { timeout: 15000 });
  });

  test('Performance page renders its summary without a stuck loading state', {
    tag: ['@rum', '@dataflow', '@ui', '@P1'],
  }, async ({ page }) => {
    await page.goto(`${BASE}/web/rum/performance?org_identifier=${ORG}`);
    await page.waitForLoadState('networkidle', { timeout: 30000 }).catch(() => {});

    await expect(page.locator('[data-test="rum-performance-refresh"]')).toBeVisible({ timeout: 15000 });
    await page.locator('[data-test="rum-performance-refresh"]').click();

    // The loading indicator must resolve (not hang) after refresh.
    await expect(page.locator('[data-test="performance-summary-loading-indicator"]')).toBeHidden({
      timeout: 30000,
    });
  });
});
