/**
 * RUM Page Data Flow — Sessions & Performance
 *
 * Proves that RUM data generated by the real SDK surfaces on the RUM product
 * pages (beyond Error Tracking, which the CDN/NPM specs already cover):
 *   - The session recorded in this run lands in _sessionreplay (recording)
 *     and is listed on the Sessions page (row opens its session viewer)
 *   - Performance page renders its summary without a stuck loading state
 *
 * Self-contained: generates a session via the shared CDN sample fixture in
 * beforeAll, then verifies through the authenticated UI.
 *
 * Prerequisites:
 *   - OpenObserve build on ZO_BASE_URL (default http://localhost:5080); the
 *     RUM ingest/token/search routes are part of the standard (OSS) router.
 *   - Network access to the CDN bundle; cross-origin RUM ingestion allowed
 *
 * Data cleanup: rows are written to the shared _rumdata/_rumlog/_sessionreplay
 * streams. OpenObserve exposes NO predicate-scoped delete — the only
 * stream-data delete API removes an entire hour-aligned time window
 * regardless of `service` — so this run's rows cannot be deleted individually
 * or in-place. Instead: every row is namespaced with a unique per-run
 * `service` so reruns never cross-assert, stream retention ages rows out, and
 * a long-lived test instance can bound accumulation with the opt-in
 * `ZO_RUM_PURGE_STREAM_DATA=true` old-data purge that runs once in global
 * teardown (see utils/global-teardown.js + purgeOldRumStreamData).
 */

const { test, expect } = require('../utils/enhanced-baseFixtures.js');
const testLogger = require('../utils/test-logger.js');
const PageManager = require('../../pages/page-manager.js');
const { startFixtureServer } = require('../../fixtures/rum/serve.js');
const { getOrCreateRumToken } = require('../utils/rum-token-api.js');
const { resolveCdnSdkVersion } = require('../utils/rum-sdk-version.js');
const {
  driveRumSampleInteractions,
  attachCdnAssetTracker,
  waitForRumSdkReady,
} = require('../utils/rum-traffic.js');
const { waitForStreamRows } = require('../utils/rum-stream-verify.js');

const ORG = process.env.ORGNAME || 'default';
const BASE = process.env.ZO_BASE_URL || 'http://localhost:5080';
const SITE = BASE.replace(/^https?:\/\//, '').replace(/\/$/, '');
const INSECURE = BASE.startsWith('http://');

const RUN_ID = Date.now();
const SERVICE = `e2e-rum-page-${RUN_ID}`;
// The SDK session generated for this run — captured in beforeAll and used to
// assert the Sessions page lists exactly this recording.
let sessionId = null;
// False when the live CDN never delivered the lazy recorder chunk — without
// it the SDK cannot record replay, events never carry session_has_replay, and
// the Sessions page (which filters on that flag) can never list the session.
// That is a CDN provisioning issue, not an OpenObserve regression → skip.
let replayCapable = false;

test.describe('RUM Page Data Flow', () => {
  // SERIAL IS REQUIRED: beforeAll generates ONE session whose id (module
  // state) both tests assert against; with fullyParallel workers each test
  // would re-run beforeAll in its own process, regenerating data and losing
  // the shared sessionId.
  test.describe.configure({ mode: 'serial' });

  test.beforeEach(async ({}, testInfo) => {
    testLogger.testStart(testInfo.title, testInfo.file);
  });

  test.beforeAll(async ({ browser }) => {
    // 1) token + CDN SDK version (probed best-effort; falls back to the pin)
    const tokenPage = await browser.newPage();
    const rumToken = await getOrCreateRumToken(tokenPage);
    const sdkVersion = await resolveCdnSdkVersion(tokenPage);
    await tokenPage.close();
    expect(rumToken, 'RUM token should be available').toBeTruthy();

    // 2) serve fixture + generate one real session (fixture app needs no OO auth)
    const server = await startFixtureServer({
      clientToken: rumToken,
      org: ORG,
      site: SITE,
      insecureHTTP: INSECURE,
      service: SERVICE,
      env: 'e2e',
      version: '1.0.0',
      applicationId: `e2e-rum-page-app-${RUN_ID}`,
      sdkVersion,
    });

    const genContext = await browser.newContext();
    const app = await genContext.newPage();
    const cdn = attachCdnAssetTracker(app);
    await app.goto(server.url, { waitUntil: 'domcontentloaded' });
    await app
      .waitForResponse((r) => r.url().includes('browsersdk.openobserve.ai') && r.url().includes('openobserve-rum'), { timeout: 30000 })
      .catch(() => testLogger.warn('CDN rum bundle response not observed'));
    // Explicit SDK readiness (real SDK objects replace the loader stubs).
    await waitForRumSdkReady(app);
    // Replay recording only starts once the LAZY recorder chunk arrives from
    // the CDN — and only events emitted after that carry session_has_replay,
    // which the Sessions page filters on. Wait for it BEFORE interacting.
    await expect
      .poll(() => cdn.chunkLoaded('recorder'), { timeout: 20000, intervals: [1000, 2000] })
      .toBe(true)
      .catch(() => {});
    replayCapable = cdn.chunkLoaded('recorder');
    if (!replayCapable) {
      testLogger.warn('CDN recorder chunk unavailable — Sessions page assertions will be skipped', {
        failures: cdn.failures,
      });
    }
    await driveRumSampleInteractions(app);

    // 3) wait for the data to be searchable — while the app (and the SDK's
    // retry loop) is still alive, mirroring the CDN/NPM dataflow specs.
    const hits = await waitForStreamRows(app, {
      sql: `SELECT * FROM "_rumdata" WHERE service = '${SERVICE}'`,
      minRows: 1,
      timeoutMs: 45000,
    });
    // Wait for a row that actually CARRIES a session, rather than reading
    // hits[0]. _rumdata also receives the SDK's own telemetry events (same
    // /rum intake) and telemetry is deliberately session-independent, so it
    // can be emitted before the session manager resolves. Those rows still
    // match the query above because the backend stamps `service` onto every
    // record from the `ootags` query string, not from the event body — so the
    // first queryable row can legitimately have no session_id.
    const sessionRows = await waitForStreamRows(app, {
      sql: `SELECT * FROM "_rumdata" WHERE service = '${SERVICE}' AND session_id IS NOT NULL`,
      minRows: 1,
      timeoutMs: 30000,
    });
    sessionId = sessionRows[0]?.session_id || null;

    // 4) the session RECORDING must land too: replay segments in
    // _sessionreplay. The Sessions page only lists sessions with
    // session_has_replay set, so this is the precondition for the UI
    // assertion below.
    const replayRows = replayCapable && sessionId
      ? await waitForStreamRows(app, {
          sql: `SELECT * FROM "_sessionreplay" WHERE session_id = '${sessionId}'`,
          minRows: 1,
          timeoutMs: 45000,
        })
      : [];

    await genContext.close();
    await server.close();

    expect(sessionId, 'generated RUM events should carry a session_id').toBeTruthy();
    if (replayCapable) {
      expect(replayRows.length, `_sessionreplay should contain segments for session ${sessionId}`)
        .toBeGreaterThan(0);
    }
    testLogger.info('RUM page dataflow setup complete', {
      service: SERVICE,
      sessionId,
      replayCapable,
      rumRows: hits.length,
      replayRows: replayRows.length,
    });
  });

  test('Sessions page lists the session recorded in this run', {
    tag: ['@rum', '@rumPageDataflow', '@dataflow', '@ui', '@P0'],
  }, async ({ page }) => {
    // Sessions are listed only when their events carry session_has_replay —
    // impossible when the CDN never served the recorder chunk (external).
    test.skip(!replayCapable, 'CDN recorder chunk unavailable this run (external dependency)');

    const pm = new PageManager(page);

    // Scope the list to THIS run's session — the filter is applied to the
    // _rumdata sessions query, so any row that comes back is our recording.
    await pm.rumSessionsPage.gotoSessionsList({ service: SERVICE, period: '1h' });
    await pm.rumSessionsPage.expectSessionsTableVisible();
    // Session aggregation can lag ingestion; poll for the filtered row.
    await pm.rumSessionsPage.waitForSessionRowsPresent();

    // Opening the row must land on the session viewer for the exact session
    // captured during generation — proves the listed row IS the new recording.
    await pm.rumSessionsPage.openFirstSession();
    await pm.rumSessionsPage.expectSessionViewerFor(sessionId);
  });

  test('Performance page renders its summary without a stuck loading state', {
    tag: ['@rum', '@rumPageDataflow', '@dataflow', '@ui', '@P1'],
  }, async ({ page }) => {
    const pm = new PageManager(page);

    await pm.rumPerformancePage.gotoPerformance();
    await pm.rumPerformancePage.clickRefresh();

    // The loading indicator must resolve (not hang) after refresh.
    await pm.rumPerformancePage.expectSummaryLoadingResolved();
  });
});
