/**
 * RUM Page Data Flow — Sessions & Performance
 *
 * Proves that RUM data generated by the real SDK surfaces on the RUM product
 * pages (beyond Error Tracking, which the CDN/NPM specs already cover):
 *   - Sessions page lists a session from this run
 *   - Performance page renders its summary without a stuck loading state
 *
 * Self-contained: generates a session via the shared CDN sample fixture in
 * beforeAll, then verifies through the authenticated UI.
 *
 * Prerequisites:
 *   - OpenObserve ENTERPRISE build on ZO_BASE_URL (default http://localhost:5080)
 *   - Network access to the live CDN bundle; cross-origin RUM ingestion allowed
 */

const { test, expect } = require('../utils/enhanced-baseFixtures.js');
const testLogger = require('../utils/test-logger.js');
const PageManager = require('../../pages/page-manager.js');
const { startFixtureServer } = require('../../fixtures/rum/serve.js');
const { getOrCreateRumToken } = require('../utils/rum-token-api.js');
const { driveRumSampleInteractions } = require('../utils/rum-traffic.js');
const { waitForStreamRows } = require('../utils/rum-stream-verify.js');

const ORG = process.env.ORGNAME || 'default';
const BASE = process.env.ZO_BASE_URL || 'http://localhost:5080';
const SITE = BASE.replace(/^https?:\/\//, '').replace(/\/$/, '');
const INSECURE = BASE.startsWith('http://');

const RUN_ID = Date.now();
const SERVICE = `e2e-rum-page-${RUN_ID}`;

test.describe('RUM Page Data Flow', { tag: '@enterprise' }, () => {
  test.describe.configure({ mode: 'serial' });

  test.beforeAll(async ({ browser }) => {
    // 1) token
    const tokenPage = await browser.newPage();
    const rumToken = await getOrCreateRumToken(tokenPage);
    await tokenPage.close();
    expect(rumToken, 'RUM token should be available').toBeTruthy();

    // 2) serve fixture + generate one real session (fixture app needs no OO auth)
    const server = await startFixtureServer({
      clientToken: rumToken,
      org: ORG,
      site: SITE,
      insecureHTTP: INSECURE,
      service: SERVICE,
      env: 'e2e',
      version: '1.0.0',
      applicationId: `e2e-rum-page-app-${RUN_ID}`,
    });

    const genContext = await browser.newContext();
    const app = await genContext.newPage();
    await app.goto(server.url, { waitUntil: 'domcontentloaded' });
    await app
      .waitForResponse((r) => r.url().includes('browsersdk.openobserve.ai') && r.url().includes('openobserve-rum'), { timeout: 30000 })
      .catch(() => testLogger.warn('CDN rum bundle response not observed'));
    await app.waitForLoadState('networkidle', { timeout: 15000 }).catch(() => {});
    await driveRumSampleInteractions(app);
    await genContext.close();
    await server.close();

    // 3) wait for the data to be searchable before hitting the UI
    const tokenPage2 = await browser.newPage();
    const hits = await waitForStreamRows(tokenPage2, {
      sql: `SELECT * FROM "_rumdata" WHERE service = '${SERVICE}'`,
      minRows: 1,
      timeoutMs: 45000,
    });
    await tokenPage2.close();
    testLogger.info('RUM page dataflow setup complete', { service: SERVICE, rows: hits.length });
  });

  test('Sessions page lists a session and renders the table', {
    tag: ['@rum', '@dataflow', '@ui', '@P0'],
  }, async ({ page }) => {
    const pm = new PageManager(page);

    await page.goto(`${BASE}/web/rum/sessions?org_identifier=${ORG}`);
    await page.waitForLoadState('networkidle', { timeout: 30000 }).catch(() => {});

    await pm.rumPage.openDateTimePicker();
    await pm.rumPage.selectPastOneHour();
    await page.locator('[data-test="sessions-run-query-button"]').click();
    await page.waitForLoadState('networkidle', { timeout: 20000 }).catch(() => {});

    await expect(page.locator('[data-test="rum-sessions-table"]')).toBeVisible({ timeout: 15000 });
    // Session aggregation can lag ingestion; poll for at least one row.
    await expect
      .poll(async () => page.locator('[data-test^="o2-table-row-"]').count(), {
        timeout: 60000,
        intervals: [2000, 3000, 5000],
      })
      .toBeGreaterThan(0);
  });

  test('Performance page renders its summary without a stuck loading state', {
    tag: ['@rum', '@dataflow', '@ui', '@P1'],
  }, async ({ page }) => {
    await page.goto(`${BASE}/web/rum/performance?org_identifier=${ORG}`);
    await page.waitForLoadState('networkidle', { timeout: 30000 }).catch(() => {});

    await expect(page.locator('[data-test="rum-performance-refresh"]')).toBeVisible({ timeout: 15000 });
    await page.locator('[data-test="rum-performance-refresh"]').click();

    // The loading indicator must resolve (not hang) after refresh.
    await expect(page.locator('[data-test="performance-summary-loading-indicator"]')).toBeHidden({
      timeout: 30000,
    });
  });
});
