export default {
  org_users: {
    data: [
      {
        id: 1,
        email: "john@gmail.com",
        cognito_sub: "NA",
        created_at: 1678089178215,
        member_created: 1678089178225,
        member_updated: 1678089178,
        role: "admin",
        org_member_id: 210,
        first_name: "John",
        last_name: "Doe",
      },
      {
        id: 2,
        email: "example@gmail.com",
        cognito_sub: "NA",
        created_at: 1678089178215,
        member_created: 1678089178225,
        member_updated: 1678089178,
        role: "admin",
        org_member_id: 211,
        first_name: "example",
      },
      {
        id: 3,
        email: "test@gmail.com",
        cognito_sub: "NA",
        created_at: 1678089178215,
        member_created: 1678089178225,
        member_updated: 1678089178,
        role: "member",
        org_member_id: 212,
        first_name: "test",
      },
    ],
  },
  users: {
    data: [
      {
        id: 11,
        email: "root@example.com",
        first_name: "root",
        last_name: "",
        role: "root",
      },
      {
        id: 1,
        email: "john@gmail.com",
        role: "admin",
        first_name: "John",
        last_name: "Doe",
      },
      {
        id: 2,
        email: "example@gmail.com",
        role: "admin",
        first_name: "example",
      },
      {
        id: 3,
        email: "test@gmail.com",
        role: "member",
        first_name: "test",
      },
    ],
  },
};
