// Copyright 2026 OpenObserve Inc.
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.

use config::{get_config, meta::stream::StreamType};
#[cfg(feature = "enterprise")]
use o2_ratelimit::dataresource::default_rules::OpenapiInfo;
use openobserve_api_ingest::request::{clusters, logs, metrics, rum};
use openobserve_api_management::request::{
    actions, gen_ai, keys, kv, service_accounts, service_streams, short_url, status, stream,
    synthetics,
};
use openobserve_api_pipelines::request::{enrichment_table, functions, pipeline, pipelines};
use openobserve_api_search::search::patterns;
use utoipa::{
    Modify, OpenApi,
    openapi::security::{Http, HttpAuthScheme, SecurityScheme},
};

use crate::{
    common::meta,
    handler::http::request::{mcp, ratelimit},
};

#[derive(OpenApi)]
#[openapi(
    paths(
        status::healthz,
        openobserve_api_management::request::users::list,
        openobserve_api_management::request::users::save,
        openobserve_api_management::request::users::update,
        openobserve_api_management::request::users::delete,
        openobserve_api_management::request::users::add_user_to_org,
        openobserve_api_management::request::organization::org::organizations,
        openobserve_api_management::request::organization::org::create_org,
        openobserve_api_management::request::organization::org::rename_org,
        openobserve_api_management::request::organization::assume_service_account::assume_service_account,
        openobserve_api_management::request::organization::org::org_summary,
        openobserve_api_management::request::organization::org::get_user_passcode,
        openobserve_api_management::request::organization::org::update_user_passcode,
        openobserve_api_management::request::organization::org::get_user_rumtoken,
        openobserve_api_management::request::organization::org::update_user_rumtoken,
        openobserve_api_management::request::organization::org::create_user_rumtoken,
        openobserve_api_management::request::organization::settings::get,
        openobserve_api_management::request::organization::settings::create,
        openobserve_api_management::request::organization::system_settings::get_setting,
        openobserve_api_management::request::organization::system_settings::list_settings,
        openobserve_api_management::request::organization::system_settings::set_org_setting,
        openobserve_api_management::request::organization::system_settings::set_user_setting,
        openobserve_api_management::request::organization::system_settings::delete_org_setting,
        openobserve_api_management::request::organization::system_settings::delete_user_setting,
        stream::list,
        stream::schema,
        stream::create,
        stream::update_settings,
        stream::delete_fields,
        stream::delete,
        logs::ingest::bulk,
        logs::ingest::multi,
        logs::ingest::json,
        logs::loki::loki_push,
        openobserve_api_search::traces::traces_write,
        openobserve_api_search::traces::get_latest_traces,
        openobserve_api_search::traces::session::get_latest_sessions,
        openobserve_api_search::traces::session::get_session_details,
        openobserve_api_search::traces::user::get_latest_users,
        openobserve_api_search::traces::dag::get_trace_dag,
        metrics::ingest::json,
        openobserve_api_search::promql::remote_write,
        openobserve_api_search::promql::query_get,
        openobserve_api_search::promql::query_range_get,
        openobserve_api_search::promql::metadata,
        openobserve_api_search::promql::series_get,
        openobserve_api_search::promql::labels_get,
        openobserve_api_search::promql::label_values,
        openobserve_api_search::promql::format_query_get,
        enrichment_table::save_enrichment_table,
        enrichment_table::save_enrichment_table_from_url,
        rum::ingest::log,
        rum::ingest::data,
        rum::ingest::sessionreplay,
        openobserve_api_search::search::search,
        openobserve_api_search::search::search_partition,
        openobserve_api_search::search::around_v1,
        openobserve_api_search::search::around_v2,
        openobserve_api_search::search::values,
        openobserve_api_search::search::search_history,
        openobserve_api_search::search::saved_view::create_view,
        openobserve_api_search::search::saved_view::delete_view,
        openobserve_api_search::search::saved_view::get_view,
        openobserve_api_search::search::saved_view::get_views,
        openobserve_api_search::search::saved_view::update_view,
        openobserve_api_management::request::folders::delete_folder,
        openobserve_api_management::request::folders::create_folder,
        openobserve_api_management::request::folders::list_folders,
        openobserve_api_management::request::folders::get_folder,
        openobserve_api_management::request::folders::get_folder_by_name,
        openobserve_api_management::request::folders::update_folder,
        openobserve_api_management::request::folders::deprecated::delete_folder,
        openobserve_api_management::request::folders::deprecated::create_folder,
        openobserve_api_management::request::folders::deprecated::list_folders,
        openobserve_api_management::request::folders::deprecated::get_folder,
        openobserve_api_management::request::folders::deprecated::get_folder_by_name,
        openobserve_api_management::request::folders::deprecated::update_folder,
        functions::list_functions,
        functions::update_function,
        functions::save_function,
        functions::delete_function,
        functions::list_pipeline_dependencies,
        functions::test_function,
        openobserve_api_management::request::dashboards::create_dashboard,
        openobserve_api_management::request::dashboards::update_dashboard,
        openobserve_api_management::request::dashboards::list_dashboards,
        openobserve_api_management::request::dashboards::get_dashboard,
        openobserve_api_management::request::dashboards::delete_dashboard,
        openobserve_api_management::request::dashboards::move_dashboard,
        openobserve_api_management::request::dashboards::move_dashboards,
        openobserve_api_management::request::dashboards::add_panel,
        openobserve_api_management::request::dashboards::update_panel,
        openobserve_api_management::request::dashboards::delete_panel,
        openobserve_api_management::request::dashboards::timed_annotations::create_annotations,
        openobserve_api_management::request::dashboards::timed_annotations::get_annotations,
        openobserve_api_management::request::dashboards::timed_annotations::delete_annotations,
        openobserve_api_management::request::dashboards::timed_annotations::update_annotations,
        openobserve_api_management::request::dashboards::timed_annotations::delete_annotation_panels,
        openobserve_api_management::request::alerts::create_alert,
        openobserve_api_management::request::alerts::get_alert,
        openobserve_api_management::request::alerts::export_alert,
        openobserve_api_management::request::alerts::update_alert,
        openobserve_api_management::request::alerts::delete_alert,
        openobserve_api_management::request::alerts::list_alerts,
        openobserve_api_management::request::alerts::enable_alert,
        openobserve_api_management::request::alerts::enable_alert_bulk,
        openobserve_api_management::request::alerts::trigger_alert,
        openobserve_api_management::request::alerts::retrain_alert,
        openobserve_api_management::request::alerts::clone_alert,
        openobserve_api_management::request::alerts::generate_sql,
        openobserve_api_management::request::alerts::move_alerts,
        openobserve_api_management::request::alerts::history::get_alert_history,
        openobserve_api_management::request::alerts::incidents::list_incidents,
        openobserve_api_management::request::alerts::incidents::get_incident,
        openobserve_api_management::request::alerts::incidents::update_incident,
        openobserve_api_management::request::alerts::incidents::get_incident_stats,
        openobserve_api_management::request::alerts::incidents::trigger_incident_rca,
        openobserve_api_management::request::alerts::incidents::cancel_incident_rca,
        openobserve_api_management::request::alerts::incidents::get_incident_rca_history,
        openobserve_api_management::request::alerts::templates::list_templates,
        openobserve_api_management::request::alerts::templates::get_template,
        openobserve_api_management::request::alerts::templates::save_template,
        openobserve_api_management::request::alerts::templates::update_template,
        openobserve_api_management::request::alerts::templates::delete_template,
        openobserve_api_management::request::alerts::templates::get_system_templates,
        openobserve_api_management::request::alerts::destinations::list_destinations,
        openobserve_api_management::request::alerts::destinations::get_destination,
        openobserve_api_management::request::alerts::destinations::save_destination,
        openobserve_api_management::request::alerts::destinations::update_destination,
        openobserve_api_management::request::alerts::destinations::delete_destination,
        kv::get,
        kv::set,
        kv::delete,
        kv::list,
        clusters::list_clusters,
        short_url::shorten,
        short_url::retrieve,
        ratelimit::list_module_ratelimit,
        ratelimit::list_role_ratelimit,
        ratelimit::update_ratelimit,
        service_accounts::list,
        service_accounts::save,
        service_accounts::update,
        service_accounts::delete,
        mcp::handle_mcp_post,
        mcp::handle_mcp_get,
        mcp::oauth_authorization_server_metadata,
        pipeline::save_pipeline,
        pipeline::list_pipelines,
        pipeline::get_pipeline,
        pipeline::list_streams_with_pipeline,
        pipeline::delete_pipeline,
        pipeline::update_pipeline,
        pipeline::enable_pipeline,
        pipeline::enable_pipeline_bulk,
        pipelines::history::get_pipeline_history,
        pipelines::backfill::create_backfill,
        pipelines::backfill::list_backfills,
        pipelines::backfill::get_backfill,
        pipelines::backfill::enable_backfill,
        pipelines::backfill::update_backfill,
        pipelines::backfill::delete_backfill,
        openobserve_api_management::request::dashboards::reports::create_report,
        openobserve_api_management::request::dashboards::reports::update_report,
        openobserve_api_management::request::dashboards::reports::list_reports,
        openobserve_api_management::request::dashboards::reports::get_report,
        openobserve_api_management::request::dashboards::reports::delete_report,
        openobserve_api_management::request::dashboards::reports::enable_report,
        openobserve_api_management::request::dashboards::reports::trigger_report,
        openobserve_api_management::request::dashboards::reports::create_report_v2,
        openobserve_api_management::request::dashboards::reports::list_reports_v2,
        openobserve_api_management::request::dashboards::reports::get_report_v2,
        openobserve_api_management::request::dashboards::reports::update_report_v2,
        openobserve_api_management::request::dashboards::reports::delete_report_v2,
        openobserve_api_management::request::dashboards::reports::delete_report_bulk_v2,
        openobserve_api_management::request::dashboards::reports::enable_report_v2,
        openobserve_api_management::request::dashboards::reports::trigger_report_v2,
        openobserve_api_management::request::dashboards::reports::move_reports,
        actions::action::upload_zipped_action,
        actions::action::delete_action,
        actions::action::serve_action_zip,
        actions::action::update_action_details,
        actions::action::list_actions,
        actions::action::get_action_from_id,
        openobserve_api_management::request::authz::fga::create_role,
        openobserve_api_management::request::authz::fga::delete_role,
        openobserve_api_management::request::authz::fga::get_roles,
        openobserve_api_management::request::authz::fga::update_role,
        openobserve_api_management::request::authz::fga::get_role_permissions,
        openobserve_api_management::request::authz::fga::get_all_role_permissions,
        openobserve_api_management::request::authz::fga::get_roles_for_all_users,
        openobserve_api_management::request::authz::fga::get_users_with_role,
        openobserve_api_management::request::authz::fga::create_group,
        openobserve_api_management::request::authz::fga::update_group,
        openobserve_api_management::request::authz::fga::get_groups,
        openobserve_api_management::request::authz::fga::get_group_details,
        openobserve_api_management::request::authz::fga::delete_group,
        keys::save,
        keys::get,
        keys::list,
        keys::delete,
        keys::update,
        openobserve_api_search::search::search_job::submit_job,
        openobserve_api_search::search::search_job::list_status,
        openobserve_api_search::search::search_job::get_status,
        openobserve_api_search::search::search_job::cancel_job,
        openobserve_api_search::search::search_job::get_job_result,
        openobserve_api_search::search::search_job::delete_job,
        openobserve_api_search::search::search_job::retry_job,
        openobserve_api_search::search::search_stream::search_http2_stream,
        openobserve_api_search::search::search_stream::values_http2_stream,
        patterns::extract_patterns,
        openobserve_core::traces::service_graph::api::get_current_topology,
        service_streams::list_services,
        service_streams::get_dimension_analytics,
        service_streams::correlate_streams,
        service_streams::get_identity_config,
        service_streams::save_identity_config,
        gen_ai::clear_agent_registry,
        gen_ai::get_agent_mapping,
        gen_ai::list_scored_agents,
        gen_ai::save_agent_mapping,
        openobserve_api_management::request::alerts::deduplication::get_config,
        openobserve_api_management::request::alerts::deduplication::set_config,
        openobserve_api_management::request::alerts::deduplication::delete_config,
        openobserve_api_management::request::alerts::deduplication::get_semantic_groups,
        openobserve_api_management::request::alerts::deduplication::preview_semantic_groups_diff,
        openobserve_api_management::request::alerts::deduplication::save_semantic_groups,
        openobserve_api_management::request::alerts::dedup_stats::get_dedup_summary,
        synthetics::list_synthetics,
        synthetics::create_synthetic,
        synthetics::get_synthetic,
        synthetics::update_synthetic,
        synthetics::delete_synthetic,
        synthetics::set_synthetic_enabled,
        synthetics::run_synthetic_now,
        synthetics::list_locations,
        synthetics::list_runs,
        synthetics::get_run_detail,
        synthetics::job_resolve,
        synthetics::job_lease,
        synthetics::job_ack,
    ),
    components(
        schemas(
            meta::http::HttpResponse,
            StreamType,
            meta::stream::Stream,
            meta::stream::StreamDeleteFields,
            meta::stream::StreamCreate,
            meta::stream::ListStream,
            config::meta::stream::StreamField,
            config::meta::stream::StreamSettings,
            config::meta::stream::StreamPartition,
            config::meta::stream::StreamPartitionType,
            config::meta::stream::StreamStats,
            config::meta::stream::UpdateStreamSettings,
            config::meta::gen_ai::GenAiAgentMappingConfig,
            gen_ai::GenAiAgentListItem,
            gen_ai::GenAiAgentListResponse,
            config::meta::dashboards::Dashboard,
            config::meta::dashboards::v1::AxisItem,
            config::meta::dashboards::v1::Dashboard,
            config::meta::dashboards::v1::AggregationFunc,
            config::meta::dashboards::v1::Layout,
            config::meta::dashboards::v1::Panel,
            config::meta::dashboards::v1::PanelConfig,
            config::meta::dashboards::v1::PanelFields,
            config::meta::dashboards::v1::PanelFilter,
            config::meta::dashboards::v1::Variables,
            config::meta::dashboards::v1::QueryData,
            config::meta::dashboards::v1::CustomFieldsOption,
            config::meta::dashboards::v1::VariableList,
            config::meta::alerts::alert::Alert,
            config::meta::alerts::Aggregation,
            config::meta::alerts::AggFunction,
            config::meta::alerts::Condition,
            config::meta::alerts::CompareHistoricData,
            config::meta::alerts::FrequencyType,
            config::meta::alerts::Operator,
            config::meta::alerts::QueryType,
            config::meta::alerts::QueryCondition,
            config::meta::alerts::TriggerCondition,
            config::meta::destinations::HTTPType,
            config::meta::timed_annotations::TimedAnnotation,
            config::meta::timed_annotations::TimedAnnotationReq,
            config::meta::timed_annotations::TimedAnnotationDelete,
            config::meta::timed_annotations::TimedAnnotationUpdate,
            // Enrichment Tables
            config::meta::enrichment_table::EnrichmentTableStatus,
            config::meta::enrichment_table::EnrichmentTableUrlJob,
            enrichment_table::EnrichmentTableUrlRequest,
            // Dashboards
            openobserve_api_management::models::dashboards::DashboardRequestBody,
            openobserve_api_management::models::dashboards::DashboardResponseBody,
            openobserve_api_management::models::dashboards::ListDashboardsResponseBody,
            openobserve_api_management::models::dashboards::ListDashboardsResponseBodyItem,
            openobserve_api_management::models::dashboards::MoveDashboardRequestBody,
            openobserve_api_management::models::dashboards::MoveDashboardsRequestBody,
            // Destinations
            openobserve_api_management::models::destinations::Destination,
            openobserve_api_management::models::destinations::DestinationType,
            openobserve_api_management::models::destinations::Template,
            // Alerts
            openobserve_api_management::models::alerts::requests::CreateAlertRequestBody,
            openobserve_api_management::models::alerts::requests::UpdateAlertRequestBody,
            openobserve_api_management::models::alerts::requests::MoveAlertsRequestBody,
            openobserve_api_management::models::alerts::responses::GetAlertResponseBody,
            openobserve_api_management::models::alerts::responses::ListAlertsResponseBody,
            openobserve_api_management::models::alerts::responses::ListAlertsResponseBodyItem,
            openobserve_api_management::models::alerts::responses::EnableAlertResponseBody,
            openobserve_api_management::models::alerts::Alert,
            openobserve_api_management::models::alerts::TriggerCondition,
            openobserve_api_management::models::alerts::CompareHistoricData,
            openobserve_api_management::models::alerts::FrequencyType,
            openobserve_api_management::models::alerts::QueryCondition,
            openobserve_api_management::models::alerts::Aggregation,
            openobserve_api_management::models::alerts::AggFunction,
            openobserve_api_management::models::alerts::QueryType,
            openobserve_api_management::models::alerts::Condition,
            openobserve_api_management::models::alerts::Operator,
            // Incidents
            openobserve_api_management::request::alerts::incidents::ListIncidentsQuery,
            openobserve_api_management::request::alerts::incidents::ListIncidentsResponse,
            openobserve_api_management::request::alerts::incidents::UpdatePayload,
            openobserve_api_management::request::alerts::incidents::IncidentSeverity,
            openobserve_api_management::request::alerts::incidents::IncidentStatus,
            config::meta::alerts::incidents::Incident,
            config::meta::alerts::incidents::IncidentWithAlerts,
            config::meta::alerts::incidents::IncidentAlert,
            config::meta::alerts::incidents::IncidentStats,
            config::meta::alerts::incidents::CorrelationReason,
            config::meta::alerts::incidents::AlertNode,
            config::meta::alerts::incidents::AlertEdge,
            config::meta::alerts::incidents::EdgeType,
            // Folders
            openobserve_api_management::models::folders::CreateFolderRequestBody,
            openobserve_api_management::models::folders::CreateFolderResponseBody,
            openobserve_api_management::models::folders::GetFolderResponseBody,
            openobserve_api_management::models::folders::ListFoldersResponseBody,
            openobserve_api_management::models::folders::UpdateFolderRequestBody,
            openobserve_api_management::models::folders::FolderType,
            config::meta::function::Transform,
            config::meta::function::FunctionList,
            config::meta::function::StreamOrder,
            config::meta::function::TestVRLRequest,
            config::meta::sql::OrderBy,
            config::meta::search::Query,
            config::meta::search::Request,
            config::meta::search::RequestEncoding,
            config::meta::search::Response,
            config::meta::search::ResponseTook,
            config::meta::search::SearchEventType,
            config::meta::search::SearchEventContext,
            config::meta::search::SearchPartitionRequest,
            config::meta::search::SearchPartitionResponse,
            config::meta::search::SearchHistoryRequest,
            config::meta::search::CancelQueryResponse,
            config::meta::search::QueryStatusResponse,
            config::meta::search::QueryStatus,
            config::meta::search::QueryInfo,
            config::meta::search::ScanStats,
            config::meta::short_url::ShortenUrlRequest,
            config::meta::short_url::ShortenUrlResponse,
            config::meta::user::UserRole,
            ingestion_common::RecordStatus,
            ingestion_common::StreamStatus,
            ingestion_common::IngestionResponse,
            meta::loki::LokiPushResponse,
            meta::loki::LokiPushRequest,
            meta::loki::LokiStream,
            meta::loki::LokiEntry,
            meta::saved_view::View,
            meta::saved_view::ViewWithoutData,
            meta::saved_view::ViewsWithoutData,
            meta::saved_view::CreateViewRequest,
            meta::saved_view::DeleteViewResponse,
            meta::saved_view::CreateViewResponse,
            meta::saved_view::UpdateViewRequest,
            meta::user::UpdateUser,
            meta::user::UserRoleRequest,
            meta::user::PostUserRequest,
            meta::user::UserOrgRole,
            meta::user::UserList,
            meta::user::UserResponse,
            meta::user::SignInResponse,
            meta::organization::OrgSummary,
            meta::organization::StreamSummary,
            meta::organization::PipelineSummary,
            meta::organization::AlertSummary,
            meta::organization::OrganizationResponse,
            meta::organization::OrgDetails,
            meta::organization::OrgUser,
            meta::organization::IngestionPasscode,
            meta::organization::PasscodeResponse,
            meta::organization::Organization,
            meta::organization::OrgRenameBody,
            meta::organization::OrganizationSetting,
            meta::organization::OrganizationSettingResponse,
            meta::organization::RumIngestionResponse,
            meta::organization::RumIngestionToken,
            openobserve_api_management::request::organization::assume_service_account::AssumeServiceAccountRequest,
            openobserve_api_management::request::organization::assume_service_account::AssumeServiceAccountResponse,
            status::HealthzResponse,
            ingestion_common::BulkResponse,
            ingestion_common::BulkResponseItem,
            ingestion_common::ShardResponse,
            ingestion_common::BulkResponseError,
            config::meta::promql::Metadata,
            config::meta::promql::MetricType,
            // Service Streams (enterprise)
            service_streams::CorrelationRequest,
            config::meta::service_streams::CorrelationResponse,
            config::meta::service_streams::DimensionAnalytics,
            config::meta::service_streams::DimensionAnalyticsSummary,
            config::meta::service_streams::CardinalityClass,
            config::meta::service_streams::RelatedStreams,
            config::meta::service_streams::StreamInfo,
            config::meta::correlation::IdentitySet,
            config::meta::correlation::ServiceIdentityConfig,
            // Alert Deduplication (enterprise)
            config::meta::alerts::deduplication::GlobalDeduplicationConfig,
            config::meta::correlation::FieldAlias,
            config::meta::alerts::deduplication::DeduplicationConfig,
            config::meta::alerts::deduplication::GroupingConfig,
            config::meta::alerts::deduplication::SendStrategy,
            openobserve_api_management::request::alerts::dedup_stats::DedupSummaryResponse,
            // Backfill
            pipelines::backfill::BackfillRequest,
            pipelines::backfill::BackfillResponse,
            openobserve_core::alerts::backfill::BackfillJobStatus,
            // Synthetics
            config::meta::synthetics::Synthetic,
            config::meta::synthetics::SyntheticType,
            config::meta::synthetics::SyntheticStatus,
            config::meta::synthetics::SyntheticFrequency,
            config::meta::synthetics::SyntheticFrequencyType,
            config::meta::synthetics::SyntheticAuth,
            config::meta::synthetics::SyntheticVariable,
            config::meta::synthetics::SyntheticListItem,
            config::meta::synthetics::SyntheticListResponse,
         ),
    ),
    modifiers(&SecurityAddon),
    tags(
        (name = "Meta", description = "Meta details about the OpenObserve state itself. e.g. healthz"),
        (name = "Auth", description = "User login authentication"),
        (name = "Logs", description = "Logs data ingestion operations"),
        (name = "Dashboards", description = "Dashboard operations"),
        (name = "Search", description = "Search/Query operations"),
        (name = "Saved Views", description = "Collection of saved search views for easy retrieval"),
        (name = "Alerts", description = "Alerts retrieval & management operations"),
        (name = "Incidents", description = "Alert incident correlation & management operations"),
        (name = "AI", description = "AI agent chat analysis and SRE agent operations (enterprise)"),
        (name = "Functions", description = "Functions retrieval & management operations"),
        (name = "Organizations", description = "Organizations retrieval & management operations"),
        (name = "Streams", description = "Stream retrieval & management operations"),
        (name = "Users", description = "Users retrieval & management operations"),
        (name = "KV", description = "Key Value retrieval & management operations"),
        (name = "Metrics", description = "Metrics data ingestion operations"),
        (name = "Traces", description = "Traces data ingestion operations"),
        (name = "Clusters", description = "Super cluster operations"),
        (name = "Short Url", description = "Short Url Service"),
        (name = "Ratelimit", description = "Ratelimit operations"),
        (name = "Patterns", description = "Log pattern extraction operations (enterprise)"),
        (name = "Service Streams", description = "Multi-signal correlation across logs, traces, and metrics (enterprise)"),
        (name = "Synthetics", description = "Synthetic monitoring — uptime and browser checks (enterprise)"),
    ),
    info(
        description = "OpenObserve API documents [https://openobserve.ai/docs/](https://openobserve.ai/docs/)",
        contact(name = "OpenObserve", email = "hello@zinclabs.io", url = "https://openobserve.ai/"),
    ),
)]
pub struct ApiDoc;

pub struct SecurityAddon;

impl Modify for SecurityAddon {
    fn modify(&self, openapi: &mut utoipa::openapi::OpenApi) {
        let cfg = get_config();
        if !cfg.common.base_uri.is_empty() {
            openapi.servers = Some(vec![utoipa::openapi::Server::new(&cfg.common.base_uri)]);
        }
        let components = openapi.components.as_mut().unwrap();
        components.add_security_scheme(
            "Authorization",
            SecurityScheme::ApiKey(utoipa::openapi::security::ApiKey::Header(
                utoipa::openapi::security::ApiKeyValue::new("Authorization"),
            )),
        );
        components.add_security_scheme(
            "BasicAuth",
            SecurityScheme::Http(Http::new(HttpAuthScheme::Basic)),
        );
    }
}

#[cfg(feature = "enterprise")]
pub async fn openapi_info() -> OpenapiInfo {
    let api = ApiDoc::openapi();

    // Group endpoints by tags with full operation details
    let mut tag_operations: OpenapiInfo = std::collections::HashMap::new();

    for (path, path_item) in &api.paths.paths {
        for (method, operation) in [
            (utoipa::openapi::HttpMethod::Get, path_item.get.as_ref()),
            (utoipa::openapi::HttpMethod::Post, path_item.post.as_ref()),
            (utoipa::openapi::HttpMethod::Put, path_item.put.as_ref()),
            (
                utoipa::openapi::HttpMethod::Delete,
                path_item.delete.as_ref(),
            ),
            (utoipa::openapi::HttpMethod::Patch, path_item.patch.as_ref()),
            (utoipa::openapi::HttpMethod::Head, path_item.head.as_ref()),
            (
                utoipa::openapi::HttpMethod::Options,
                path_item.options.as_ref(),
            ),
            (utoipa::openapi::HttpMethod::Trace, path_item.trace.as_ref()),
        ]
        .into_iter()
        .filter_map(|(method, op)| op.map(|operation| (method, operation)))
        {
            let tags = operation
                .tags
                .clone()
                .unwrap_or_else(|| vec!["untagged".to_string()]);

            let method = match method {
                utoipa::openapi::HttpMethod::Get => "GET",
                utoipa::openapi::HttpMethod::Post => "POST",
                utoipa::openapi::HttpMethod::Put => "PUT",
                utoipa::openapi::HttpMethod::Delete => "DELETE",
                utoipa::openapi::HttpMethod::Patch => "PATCH",
                utoipa::openapi::HttpMethod::Head => "HEAD",
                utoipa::openapi::HttpMethod::Options => "OPTIONS",
                utoipa::openapi::HttpMethod::Trace => "TRACE",
            };

            let extensions: std::collections::HashMap<String, serde_json::Value> = operation
                .extensions
                .as_ref()
                .map(|ext| ext.iter().map(|(k, v)| (k.clone(), v.clone())).collect())
                .unwrap_or_default();

            let operation_info = (
                method.to_string(),
                path.clone(),
                operation.clone().description,
                tags.clone(),
                extensions,
            );

            for tag in tags {
                tag_operations
                    .entry(tag)
                    .or_default()
                    .push(operation_info.clone());
            }
        }
    }

    tag_operations
}
