import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.locator('body').click();
  await page.goto('https://monitor.dev.zinclabs.dev/web/login');
  await page.getByText('Login as internal user').click();
  await page.locator('[data-test="login-user-id"]').click();
  await page.locator('[data-test="login-user-id"]').fill('shyam@openobserve.ai');
  await page.locator('[data-test="login-password"]').click();
  await page.locator('[data-test="login-password"]').fill('Gurudev@108O');
  await page.getByRole('button', { name: 'Login', exact: true }).click();
  await page.locator('[data-test="login-password"]').click();
  await page.locator('[data-test="login-password"]').fill('Gurudev@108o');
  await page.getByRole('button', { name: 'Login', exact: true }).click();
  await page.locator('[data-test="sso-login-btn"]').click();
  await page.getByLabel('Enter your email').fill('shyam');
  await page.getByRole('button', { name: 'Next' }).click();
  await page.getByLabel('Enter your password').fill('Gurudev@108O');
  await page.getByRole('button', { name: 'Next' }).click();
  await page.getByRole('button', { name: 'Continue' }).click();
  await page.locator('[data-test="navbar-organizations-select"]').getByText('arrow_drop_down').click();
  await page.locator('[data-test="navbar-organizations-select"]').getByText('otlp-production').click();
  await expect(page.locator('[data-test="navbar-organizations-select"] span')).toContainText('otlp-production');
  await expect(page.getByRole('toolbar')).toContainText('shyam@openobserve.ai');
  await page.locator('button').filter({ hasText: 'shyam@openobserve.' }).click();
  await page.getByText('Sign Out').click();
  await page.getByText('Login as internal user').click();
  await page.locator('[data-test="login-user-id"]').click();
  await page.locator('[data-test="login-user-id"]').fill('shyam@openobserve.ai');
  await page.locator('[data-test="login-password"]').click();
  await page.locator('[data-test="login-password"]').fill('Gurudev@108O');
  await page.getByRole('button', { name: 'Login', exact: true }).click();
  await page.locator('[data-test="login-password"]').click();
  await page.goto('https://monitor.dev.zinclabs.dev/web/login');
  await page.goto('https://monitor.dev.zinclabs.dev/web/?org_identifier=otlp-production');
  await page.goto('https://monitor.dev.zinclabs.dev/web/login');
  await page.getByText('Login as internal user').click();
  await page.locator('[data-test="login-user-id"]').click();
  await page.locator('[data-test="login-user-id"]').fill('shyam@openobserve.ai');
  await page.locator('[data-test="login-password"]').click();
  await page.locator('[data-test="login-password"]').fill('O2pass#123');
  await page.getByRole('button', { name: 'Login', exact: true }).click();
});