// Copyright 2026 OpenObserve Inc.
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.

import { raw } from "@/types/i18n";

/**
 * Country code to name mapping for map charts
 * Supports ISO 3166-1 alpha-2 and alpha-3 codes
 *
 * The `name` values are ECharts GeoJSON join keys — `getCountryName()` feeds them
 * into the `type: "map"` series, where ECharts matches them against the world map's
 * region names (hence the Natural-Earth spellings "W. Sahara", "Bosnia and Herz.").
 * They are `raw()` because translating one would break the match and drop that
 * country off the map.
 */
export interface Country {
  name: string;
  alpha2: string;
  alpha3: string;
}

export const countries: Country[] = [
  { name: raw("Afghanistan"), alpha2: "AF", alpha3: "AFG" },
  { name: raw("Aland"), alpha2: "AX", alpha3: "ALA" },
  { name: raw("Albania"), alpha2: "AL", alpha3: "ALB" },
  { name: raw("Algeria"), alpha2: "DZ", alpha3: "DZA" },
  { name: raw("American Samoa"), alpha2: "AS", alpha3: "ASM" },
  { name: raw("Andorra"), alpha2: "AD", alpha3: "AND" },
  { name: raw("Angola"), alpha2: "AO", alpha3: "AGO" },
  { name: raw("Antigua and Barb."), alpha2: "AG", alpha3: "ATG" },
  { name: raw("Argentina"), alpha2: "AR", alpha3: "ARG" },
  { name: raw("Armenia"), alpha2: "AM", alpha3: "ARM" },
  { name: raw("Australia"), alpha2: "AU", alpha3: "AUS" },
  { name: raw("Austria"), alpha2: "AT", alpha3: "AUT" },
  { name: raw("Azerbaijan"), alpha2: "AZ", alpha3: "AZE" },
  { name: raw("Bahamas"), alpha2: "BS", alpha3: "BHS" },
  { name: raw("Bahrain"), alpha2: "BH", alpha3: "BHR" },
  { name: raw("Bangladesh"), alpha2: "BD", alpha3: "BGD" },
  { name: raw("Barbados"), alpha2: "BB", alpha3: "BRB" },
  { name: raw("Belarus"), alpha2: "BY", alpha3: "BLR" },
  { name: raw("Belgium"), alpha2: "BE", alpha3: "BEL" },
  { name: raw("Belize"), alpha2: "BZ", alpha3: "BLZ" },
  { name: raw("Benin"), alpha2: "BJ", alpha3: "BEN" },
  { name: raw("Bermuda"), alpha2: "BM", alpha3: "BMU" },
  { name: raw("Bhutan"), alpha2: "BT", alpha3: "BTN" },
  { name: raw("Bolivia"), alpha2: "BO", alpha3: "BOL" },
  { name: raw("Bosnia and Herz."), alpha2: "BA", alpha3: "BIH" },
  { name: raw("Botswana"), alpha2: "BW", alpha3: "BWA" },
  { name: raw("Br. Indian Ocean Ter."), alpha2: "IO", alpha3: "IOT" },
  { name: raw("Brazil"), alpha2: "BR", alpha3: "BRA" },
  { name: raw("Brunei"), alpha2: "BN", alpha3: "BRN" },
  { name: raw("Bulgaria"), alpha2: "BG", alpha3: "BGR" },
  { name: raw("Burkina Faso"), alpha2: "BF", alpha3: "BFA" },
  { name: raw("Burundi"), alpha2: "BI", alpha3: "BDI" },
  { name: raw("Cambodia"), alpha2: "KH", alpha3: "KHM" },
  { name: raw("Cameroon"), alpha2: "CM", alpha3: "CMR" },
  { name: raw("Canada"), alpha2: "CA", alpha3: "CAN" },
  { name: raw("Cape Verde"), alpha2: "CV", alpha3: "CPV" },
  { name: raw("Cayman Is."), alpha2: "KY", alpha3: "CYM" },
  { name: raw("Central African Rep."), alpha2: "CF", alpha3: "CAF" },
  { name: raw("Chad"), alpha2: "TD", alpha3: "TCD" },
  { name: raw("Chile"), alpha2: "CL", alpha3: "CHL" },
  { name: raw("China"), alpha2: "CN", alpha3: "CHN" },
  { name: raw("Colombia"), alpha2: "CO", alpha3: "COL" },
  { name: raw("Comoros"), alpha2: "KM", alpha3: "COM" },
  { name: raw("Congo"), alpha2: "CG", alpha3: "COG" },
  { name: raw("Costa Rica"), alpha2: "CR", alpha3: "CRI" },
  { name: raw("Croatia"), alpha2: "HR", alpha3: "HRV" },
  { name: raw("Cuba"), alpha2: "CU", alpha3: "CUB" },
  { name: raw("Curaçao"), alpha2: "CW", alpha3: "CUW" },
  { name: raw("Cyprus"), alpha2: "CY", alpha3: "CYP" },
  { name: raw("Czech Rep."), alpha2: "CZ", alpha3: "CZE" },
  { name: raw("Côte d'Ivoire"), alpha2: "CI", alpha3: "CIV" },
  { name: raw("Dem. Rep. Congo"), alpha2: "CD", alpha3: "COD" },
  { name: raw("Dem. Rep. Korea"), alpha2: "KP", alpha3: "PRK" },
  { name: raw("Denmark"), alpha2: "DK", alpha3: "DNK" },
  { name: raw("Djibouti"), alpha2: "DJ", alpha3: "DJI" },
  { name: raw("Dominica"), alpha2: "DM", alpha3: "DMA" },
  { name: raw("Dominican Rep."), alpha2: "DO", alpha3: "DOM" },
  { name: raw("Ecuador"), alpha2: "EC", alpha3: "ECU" },
  { name: raw("Egypt"), alpha2: "EG", alpha3: "EGY" },
  { name: raw("El Salvador"), alpha2: "SV", alpha3: "SLV" },
  { name: raw("Eq. Guinea"), alpha2: "GQ", alpha3: "GNQ" },
  { name: raw("Eritrea"), alpha2: "ER", alpha3: "ERI" },
  { name: raw("Estonia"), alpha2: "EE", alpha3: "EST" },
  { name: raw("Ethiopia"), alpha2: "ET", alpha3: "ETH" },
  { name: raw("Faeroe Is."), alpha2: "FO", alpha3: "FRO" },
  { name: raw("Falkland Is."), alpha2: "FK", alpha3: "FLK" },
  { name: raw("Fiji"), alpha2: "FJ", alpha3: "FJI" },
  { name: raw("Finland"), alpha2: "FI", alpha3: "FIN" },
  { name: raw("Fr. Polynesia"), alpha2: "PF", alpha3: "PYF" },
  { name: raw("Fr. S. Antarctic Lands"), alpha2: "TF", alpha3: "ATF" },
  { name: raw("France"), alpha2: "FR", alpha3: "FRA" },
  { name: raw("Gabon"), alpha2: "GA", alpha3: "GAB" },
  { name: raw("Gambia"), alpha2: "GM", alpha3: "GMB" },
  { name: raw("Georgia"), alpha2: "GE", alpha3: "GEO" },
  { name: raw("Germany"), alpha2: "DE", alpha3: "DEU" },
  { name: raw("Ghana"), alpha2: "GH", alpha3: "GHA" },
  { name: raw("Greece"), alpha2: "GR", alpha3: "GRC" },
  { name: raw("Greenland"), alpha2: "GL", alpha3: "GRL" },
  { name: raw("Grenada"), alpha2: "GD", alpha3: "GRD" },
  { name: raw("Guam"), alpha2: "GU", alpha3: "GUM" },
  { name: raw("Guatemala"), alpha2: "GT", alpha3: "GTM" },
  { name: raw("Guinea"), alpha2: "GN", alpha3: "GIN" },
  { name: raw("Guinea-Bissau"), alpha2: "GW", alpha3: "GNB" },
  { name: raw("Guyana"), alpha2: "GY", alpha3: "GUY" },
  { name: raw("Haiti"), alpha2: "HT", alpha3: "HTI" },
  { name: raw("Heard I. and McDonald Is."), alpha2: "HM", alpha3: "HMD" },
  { name: raw("Honduras"), alpha2: "HN", alpha3: "HND" },
  { name: raw("Hungary"), alpha2: "HU", alpha3: "HUN" },
  { name: raw("Iceland"), alpha2: "IS", alpha3: "ISL" },
  { name: raw("India"), alpha2: "IN", alpha3: "IND" },
  { name: raw("Indonesia"), alpha2: "ID", alpha3: "IDN" },
  { name: raw("Iran"), alpha2: "IR", alpha3: "IRN" },
  { name: raw("Iraq"), alpha2: "IQ", alpha3: "IRQ" },
  { name: raw("Ireland"), alpha2: "IE", alpha3: "IRL" },
  { name: raw("Isle of Man"), alpha2: "IM", alpha3: "IMN" },
  { name: raw("Israel"), alpha2: "IL", alpha3: "ISR" },
  { name: raw("Italy"), alpha2: "IT", alpha3: "ITA" },
  { name: raw("Jamaica"), alpha2: "JM", alpha3: "JAM" },
  { name: raw("Japan"), alpha2: "JP", alpha3: "JPN" },
  { name: raw("Jersey"), alpha2: "JE", alpha3: "JEY" },
  { name: raw("Jordan"), alpha2: "JO", alpha3: "JOR" },
  { name: raw("Kazakhstan"), alpha2: "KZ", alpha3: "KAZ" },
  { name: raw("Kenya"), alpha2: "KE", alpha3: "KEN" },
  { name: raw("Kiribati"), alpha2: "KI", alpha3: "KIR" },
  { name: raw("Korea"), alpha2: "KR", alpha3: "KOR" },
  { name: raw("Kuwait"), alpha2: "KW", alpha3: "KWT" },
  { name: raw("Kyrgyzstan"), alpha2: "KG", alpha3: "KGZ" },
  { name: raw("Lao PDR"), alpha2: "LA", alpha3: "LAO" },
  { name: raw("Latvia"), alpha2: "LV", alpha3: "LVA" },
  { name: raw("Lebanon"), alpha2: "LB", alpha3: "LBN" },
  { name: raw("Lesotho"), alpha2: "LS", alpha3: "LSO" },
  { name: raw("Liberia"), alpha2: "LR", alpha3: "LBR" },
  { name: raw("Libya"), alpha2: "LY", alpha3: "LBY" },
  { name: raw("Liechtenstein"), alpha2: "LI", alpha3: "LIE" },
  { name: raw("Lithuania"), alpha2: "LT", alpha3: "LTU" },
  { name: raw("Luxembourg"), alpha2: "LU", alpha3: "LUX" },
  { name: raw("Macedonia"), alpha2: "MK", alpha3: "MKD" },
  { name: raw("Madagascar"), alpha2: "MG", alpha3: "MDG" },
  { name: raw("Malawi"), alpha2: "MW", alpha3: "MWI" },
  { name: raw("Malaysia"), alpha2: "MY", alpha3: "MYS" },
  { name: raw("Mali"), alpha2: "ML", alpha3: "MLI" },
  { name: raw("Malta"), alpha2: "MT", alpha3: "MLT" },
  { name: raw("Mauritania"), alpha2: "MR", alpha3: "MRT" },
  { name: raw("Mauritius"), alpha2: "MU", alpha3: "MUS" },
  { name: raw("Mexico"), alpha2: "MX", alpha3: "MEX" },
  { name: raw("Micronesia"), alpha2: "FM", alpha3: "FSM" },
  { name: raw("Moldova"), alpha2: "MD", alpha3: "MDA" },
  { name: raw("Mongolia"), alpha2: "MN", alpha3: "MNG" },
  { name: raw("Montenegro"), alpha2: "ME", alpha3: "MNE" },
  { name: raw("Montserrat"), alpha2: "MS", alpha3: "MSR" },
  { name: raw("Morocco"), alpha2: "MA", alpha3: "MAR" },
  { name: raw("Mozambique"), alpha2: "MZ", alpha3: "MOZ" },
  { name: raw("Myanmar"), alpha2: "MM", alpha3: "MMR" },
  { name: raw("N. Cyprus"), alpha2: "NCY", alpha3: "NCY" },
  { name: raw("N. Mariana Is."), alpha2: "MP", alpha3: "MNP" },
  { name: raw("Namibia"), alpha2: "NA", alpha3: "NAM" },
  { name: raw("Nepal"), alpha2: "NP", alpha3: "NPL" },
  { name: raw("Netherlands"), alpha2: "NL", alpha3: "NLD" },
  { name: raw("New Caledonia"), alpha2: "NC", alpha3: "NCL" },
  { name: raw("New Zealand"), alpha2: "NZ", alpha3: "NZL" },
  { name: raw("Nicaragua"), alpha2: "NI", alpha3: "NIC" },
  { name: raw("Niger"), alpha2: "NE", alpha3: "NER" },
  { name: raw("Nigeria"), alpha2: "NG", alpha3: "NGA" },
  { name: raw("Niue"), alpha2: "NU", alpha3: "NIU" },
  { name: raw("Norway"), alpha2: "NO", alpha3: "NOR" },
  { name: raw("Oman"), alpha2: "OM", alpha3: "OMN" },
  { name: raw("Pakistan"), alpha2: "PK", alpha3: "PAK" },
  { name: raw("Palau"), alpha2: "PW", alpha3: "PLW" },
  { name: raw("Palestine"), alpha2: "PS", alpha3: "PSE" },
  { name: raw("Panama"), alpha2: "PA", alpha3: "PAN" },
  { name: raw("Papua New Guinea"), alpha2: "PG", alpha3: "PNG" },
  { name: raw("Paraguay"), alpha2: "PY", alpha3: "PRY" },
  { name: raw("Peru"), alpha2: "PE", alpha3: "PER" },
  { name: raw("Philippines"), alpha2: "PH", alpha3: "PHL" },
  { name: raw("Poland"), alpha2: "PL", alpha3: "POL" },
  { name: raw("Portugal"), alpha2: "PT", alpha3: "PRT" },
  { name: raw("Puerto Rico"), alpha2: "PR", alpha3: "PRI" },
  { name: raw("Qatar"), alpha2: "QA", alpha3: "QAT" },
  { name: raw("Romania"), alpha2: "RO", alpha3: "ROU" },
  { name: raw("Russia"), alpha2: "RU", alpha3: "RUS" },
  { name: raw("Rwanda"), alpha2: "RW", alpha3: "RWA" },
  { name: raw("S. Geo. and S. Sandw. Is."), alpha2: "GS", alpha3: "SGS" },
  { name: raw("S. Sudan"), alpha2: "SS", alpha3: "SSD" },
  { name: raw("Saint Helena"), alpha2: "SH", alpha3: "SHN" },
  { name: raw("Saint Lucia"), alpha2: "LC", alpha3: "LCA" },
  { name: raw("Samoa"), alpha2: "WS", alpha3: "WSM" },
  { name: raw("Saudi Arabia"), alpha2: "SA", alpha3: "SAU" },
  { name: raw("Senegal"), alpha2: "SN", alpha3: "SEN" },
  { name: raw("Serbia"), alpha2: "RS", alpha3: "SRB" },
  { name: raw("Seychelles"), alpha2: "SC", alpha3: "SYC" },
  { name: raw("Siachen Glacier"), alpha2: "SGX", alpha3: "SGC" },
  { name: raw("Sierra Leone"), alpha2: "SL", alpha3: "SLE" },
  { name: raw("Singapore"), alpha2: "SG", alpha3: "SGP" },
  { name: raw("Slovakia"), alpha2: "SK", alpha3: "SVK" },
  { name: raw("Slovenia"), alpha2: "SI", alpha3: "SVN" },
  { name: raw("Solomon Is."), alpha2: "SB", alpha3: "SLB" },
  { name: raw("Somalia"), alpha2: "SO", alpha3: "SOM" },
  { name: raw("South Africa"), alpha2: "ZA", alpha3: "ZAF" },
  { name: raw("Spain"), alpha2: "ES", alpha3: "ESP" },
  { name: raw("Sri Lanka"), alpha2: "LK", alpha3: "LKA" },
  { name: raw("St. Pierre and Miquelon"), alpha2: "PM", alpha3: "SPM" },
  { name: raw("St. Vin. and Gren."), alpha2: "VC", alpha3: "VCT" },
  { name: raw("Sudan"), alpha2: "SD", alpha3: "SDN" },
  { name: raw("Suriname"), alpha2: "SR", alpha3: "SUR" },
  { name: raw("Swaziland"), alpha2: "SZ", alpha3: "SWZ" },
  { name: raw("Sweden"), alpha2: "SE", alpha3: "SWE" },
  { name: raw("Switzerland"), alpha2: "CH", alpha3: "CHE" },
  { name: raw("Syria"), alpha2: "SY", alpha3: "SYR" },
  { name: raw("São Tomé and Principe"), alpha2: "ST", alpha3: "STP" },
  { name: raw("Tajikistan"), alpha2: "TJ", alpha3: "TJK" },
  { name: raw("Tanzania"), alpha2: "TZ", alpha3: "TZA" },
  { name: raw("Thailand"), alpha2: "TH", alpha3: "THA" },
  { name: raw("Timor-Leste"), alpha2: "TL", alpha3: "TLS" },
  { name: raw("Togo"), alpha2: "TG", alpha3: "TGO" },
  { name: raw("Tonga"), alpha2: "TO", alpha3: "TON" },
  { name: raw("Trinidad and Tobago"), alpha2: "TT", alpha3: "TTO" },
  { name: raw("Tunisia"), alpha2: "TN", alpha3: "TUN" },
  { name: raw("Turkey"), alpha2: "TR", alpha3: "TUR" },
  { name: raw("Turkmenistan"), alpha2: "TM", alpha3: "TKM" },
  { name: raw("Turks and Caicos Is."), alpha2: "TC", alpha3: "TCA" },
  { name: raw("U.S. Virgin Is."), alpha2: "VI", alpha3: "VIR" },
  { name: raw("Uganda"), alpha2: "UG", alpha3: "UGA" },
  { name: raw("Ukraine"), alpha2: "UA", alpha3: "UKR" },
  { name: raw("United Arab Emirates"), alpha2: "AE", alpha3: "ARE" },
  { name: raw("United Kingdom"), alpha2: "GB", alpha3: "GBR" },
  { name: raw("United States"), alpha2: "US", alpha3: "USA" },
  { name: raw("Uruguay"), alpha2: "UY", alpha3: "URY" },
  { name: raw("Uzbekistan"), alpha2: "UZ", alpha3: "UZB" },
  { name: raw("Vanuatu"), alpha2: "VU", alpha3: "VUT" },
  { name: raw("Venezuela"), alpha2: "VE", alpha3: "VEN" },
  { name: raw("Vietnam"), alpha2: "VN", alpha3: "VNM" },
  { name: raw("W. Sahara"), alpha2: "EH", alpha3: "ESH" },
  { name: raw("Yemen"), alpha2: "YE", alpha3: "YEM" },
  { name: raw("Zambia"), alpha2: "ZM", alpha3: "ZMB" },
  { name: raw("Zimbabwe"), alpha2: "ZW", alpha3: "ZWE" },
];

/**
 * Get full country name by ISO code or return the input if already a full name
 * @param code - ISO alpha-2, alpha-3 code, or full country name
 * @returns Full country name
 */
export const getCountryName = (code: string): string => {
  const country = countries.find((c) => c.alpha2 === code || c.alpha3 === code || c.name === code);
  return country ? country.name : code;
};
