// Copyright 2026 OpenObserve Inc.

/**
 * Export Alerts as Terraform (Export Resource Dialog) — E2E Tests
 *
 * Covers the Alerts caller of the shared ExportResourceDialog: single and bulk
 * export, the JSON / Terraform tabs, copy, download, the Terraform banners, and
 * the registry links in the Alerts header. The SLO caller of the same dialog is
 * intentionally out of scope (one-spec-one-area) and lives in its own follow-up
 * SLO spec.
 *
 * Fixtures are seeded via the API (../utils/alerts-api-helpers.js) — no UI
 * creation, no destination/template dependency for *exporting* an existing
 * alert. Every selector lives in a page object (pm.alertsPage /
 * pm.exportResourceDialog); the spec carries no raw locators.
 */

const { test, expect, navigateToBase } = require('../utils/enhanced-baseFixtures.js');
const testLogger = require('../utils/test-logger.js');
const PageManager = require('../../pages/page-manager.js');
const logData = require('../../fixtures/log.json');
const { getOrgIdentifier } = require('../utils/cloud-auth.js');
const {
  seedAlertFixtures, createAlert, simpleAlert, findAlertId, deleteAlerts, uniq,
} = require('../utils/alerts-api-helpers.js');

test.describe('Export Alerts as Terraform (Export Resource Dialog)', () => {
  test.describe.configure({ mode: 'parallel', timeout: 120000 });

  let pm;
  const createdAlertNames = [];

  /**
   * Create a normal alert via the API and wait for its row to render in the list.
   * `mutate` optionally adjusts the payload (e.g. the P2-3 dropped-field case).
   */
  async function seedAlert(page, name, mutate) {
    const payload = simpleAlert(name);
    if (mutate) mutate(payload);
    const resp = await createAlert(page, payload);
    expect(resp.ok(), `create alert ${name} failed (status ${resp.status()})`).toBe(true);
    createdAlertNames.push(name);
    await pm.alertsPage.waitForAlertRow(name);
    testLogger.info('Seeded alert via API', { name });
    return name;
  }

  test.beforeEach(async ({ page }, testInfo) => {
    testLogger.testStart(testInfo.title, testInfo.file);
    await navigateToBase(page);
    pm = new PageManager(page);
    // Idempotently seed the dogfood destination + template + stream. Export only
    // needs a destination/template to *create* an alert, but seeding keeps the
    // fixture contract for the parallel shard's other specs too.
    await seedAlertFixtures(page);
    await page.goto(`${logData.alertUrl}?org_identifier=${getOrgIdentifier()}`);
    await page.waitForLoadState('networkidle', { timeout: 30000 }).catch(() => {});
    testLogger.info('Test setup completed');
  });

  test.afterEach(async ({ page }) => {
    // Guaranteed cleanup so repeat runs stay deterministic.
    const ids = [];
    for (const name of createdAlertNames) ids.push(await findAlertId(page, name));
    await deleteAlerts(page, ids);
    createdAlertNames.length = 0;
  });

  // ─────────────────────────────────────────────────────────────────────────
  // P0 — critical path
  // ─────────────────────────────────────────────────────────────────────────

  test('single alert export defaults to the JSON tab with a single object and downloads a .json', {
    tag: ['@resource-terraform-export', '@all', '@alerts'],
  }, async ({ page }) => {
    const alertName = await seedAlert(page, uniq('tf_single_json'));
    await pm.alertsPage.openSingleAlertExport(alertName);

    const dialog = pm.exportResourceDialog;
    await dialog.expectOpen();
    await dialog.expectJsonTabActive();

    const code = await dialog.waitForCodeContaining(alertName);
    const parsed = JSON.parse(code);
    expect(Array.isArray(parsed), 'single export JSON must be an object, not an array').toBe(false);
    expect(parsed.name, 'exported JSON must carry the alert name').toBe(alertName);

    const artifact = await dialog.download();
    expect(artifact.fileName).toBe(`${alertName}.json`);
    expect(artifact.content.length).toBeGreaterThan(0);
    await pm.alertsPage.expectExportSuccessToast();
    await dialog.expectClosed();
    testLogger.info('Single alert JSON export verified', { alertName });
  });

  test('single alert export Terraform tab renders openobserve_alert and downloads a .tf', {
    tag: ['@resource-terraform-export', '@all', '@alerts'],
  }, async ({ page }) => {
    const alertName = await seedAlert(page, uniq('tf_single_hcl'));
    await pm.alertsPage.openSingleAlertExport(alertName);

    const dialog = pm.exportResourceDialog;
    await dialog.expectOpen();
    await dialog.expectJsonTabActive();
    await dialog.switchToTerraform();

    const code = await dialog.waitForCodeContaining('resource "openobserve_alert"');
    expect(code).toContain('# Generated by OpenObserve.');
    expect(code, 'Terraform resource label must use the alert name').toContain(alertName);
    expect(code, 'enabled is always written so state is never implied').toContain('enabled = true');

    const artifact = await dialog.download();
    expect(artifact.fileName).toBe(`${alertName}.tf`);
    expect(artifact.content).toContain('resource "openobserve_alert"');
    await pm.alertsPage.expectExportSuccessToast();
    await dialog.expectClosed();
    testLogger.info('Single alert Terraform export verified', { alertName });
  });

  test('bulk export produces a JSON array and one Terraform resource per alert', {
    tag: ['@resource-terraform-export', '@all', '@alerts'],
  }, async ({ page }) => {
    await seedAlert(page, uniq('tf_bulk_a'));
    const nameB = await seedAlert(page, uniq('tf_bulk_b'));
    await pm.alertsPage.openBulkExport();

    const dialog = pm.exportResourceDialog;
    await dialog.expectOpen();
    await dialog.expectJsonTabActive();

    const jsonCode = await dialog.waitForCodeContaining(nameB);
    const parsed = JSON.parse(jsonCode);
    expect(Array.isArray(parsed), 'bulk export JSON must be an array').toBe(true);
    expect(parsed.length, 'bulk export must include every selected alert').toBeGreaterThanOrEqual(2);

    await dialog.switchToTerraform();
    const hclCode = await dialog.waitForCodeContaining('resource "openobserve_alert"');
    const resourceCount = (hclCode.match(/resource "openobserve_alert"/g) || []).length;
    expect(resourceCount, 'one openobserve_alert resource per convertible alert').toBeGreaterThanOrEqual(2);

    const artifact = await dialog.download();
    expect(artifact.fileName).toMatch(/^alerts-\d{4}-\d{2}-\d{2}\.tf$/);
    await pm.alertsPage.expectExportSuccessToast();
    await dialog.expectClosed();
    testLogger.info('Bulk alert Terraform export verified', { resourceCount });
  });

  // ─────────────────────────────────────────────────────────────────────────
  // P1 — important variations
  // ─────────────────────────────────────────────────────────────────────────

  test('copy button copies the active tab code to the clipboard', {
    tag: ['@resource-terraform-export', '@all', '@alerts'],
  }, async ({ page }) => {
    const alertName = await seedAlert(page, uniq('tf_copy'));
    await pm.alertsPage.openSingleAlertExport(alertName);

    const dialog = pm.exportResourceDialog;
    await dialog.expectOpen();
    await dialog.expectJsonTabActive();

    const jsonCode = await dialog.waitForCodeContaining(alertName);
    await dialog.copy();
    await dialog.expectSuccessToast('Copied to clipboard');
    const jsonClipboard = await dialog.waitForClipboardContaining(alertName);
    expect(jsonClipboard, 'clipboard must hold exactly the JSON tab code').toBe(jsonCode);

    await dialog.switchToTerraform();
    const hclCode = await dialog.waitForCodeContaining('resource "openobserve_alert"');
    await dialog.copy();
    const hclClipboard = await dialog.waitForClipboardContaining('resource "openobserve_alert"');
    expect(hclClipboard).toContain('resource "openobserve_alert"');
    expect(hclClipboard).toBe(hclCode);
    testLogger.info('Copy current tab verified for JSON and Terraform');
  });

  test('Terraform and OpenTofu registry links render in the Alerts header', {
    tag: ['@resource-terraform-export', '@all', '@alerts'],
  }, async () => {
    await pm.alertsPage.expectIacRegistryLinksVisible();
    testLogger.info('Registry links verified');
  });

  // ─────────────────────────────────────────────────────────────────────────
  // P2 — edge cases
  // ─────────────────────────────────────────────────────────────────────────

  test('dropped provider-incompatible field is reported while the resource still renders', {
    tag: ['@resource-terraform-export', '@all', '@alerts'],
  }, async ({ page }) => {
    const alertName = await seedAlert(page, uniq('tf_dropped'), (payload) => {
      payload.query_condition.aggregation = {
        group_by: ['city'],
        function: 'avg',
        having: { column: 'latency', operator: '>', value: 500, ignore_case: true },
      };
    });
    await pm.alertsPage.openSingleAlertExport(alertName);

    const dialog = pm.exportResourceDialog;
    await dialog.expectOpen();
    await dialog.switchToTerraform();

    await dialog.expectDroppedBanner(['having.ignore_case']);
    const code = await dialog.waitForCodeContaining('resource "openobserve_alert"');
    expect(code, 'the resource must still render despite the dropped field').toContain(
      'resource "openobserve_alert"',
    );
    testLogger.info('Dropped-field info banner verified', { alertName });
  });

  test('re-opening the dialog always lands back on the JSON tab', {
    tag: ['@resource-terraform-export', '@all', '@alerts'],
  }, async ({ page }) => {
    const alertName = await seedAlert(page, uniq('tf_tabreset'));
    await pm.alertsPage.openSingleAlertExport(alertName);

    const dialog = pm.exportResourceDialog;
    await dialog.expectOpen();
    await dialog.expectJsonTabActive();
    await dialog.switchToTerraform();
    await dialog.close();

    await pm.alertsPage.openSingleAlertExport(alertName);
    await dialog.expectOpen();
    await dialog.expectJsonTabActive();
    testLogger.info('Tab reset on reopen verified', { alertName });
  });
});
