apiVersion: batch/v1
kind: Job
metadata:
  name: user-script-job
spec:
  backoffLimit: 3  # Retry the Job up to 3 times if it fails
  template:
    metadata:
      name: user-script-runner
    spec:
      containers:
        - name: script-runner
          image: python-otel-executor:latest
          env:
            - name: USER_SCRIPT
              value: |
                print("Hello from the user script!")
                for i in range(5):
                    print(f"Processing item {i}")
                result = sum(range(10))
                print(f"The result is: {result}")
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
      restartPolicy: Never