#!/usr/bin/env python3
"""Generate collector/config.quad.yaml: ONE collector -> FOUR orgs on TWO servers.

WHY GENERATED, NOT HAND-WRITTEN
-------------------------------
The shared collector/config.yaml is 1,390 lines and is used by other work, so it
must not be edited in place. Everything upstream of the exporters (17 receivers,
the filter, the transforms) is identical for all four lanes -- the ONLY thing that
varies per lane is the exporter URL (org + endpoint) and, for the traces
dimension, whether a traces exporter exists at all.

config.matrix.yaml (a previous round) proved this design but HARDCODED its orgs
(o_traces/o_noTraces/e_traces/e_noTraces) and ports (5080/5090). This task needs
different orgs and different ports, and hardcoding blocks that. So instead of
copying a 1,390-line file a third time, this script DERIVES the lane config from
the shared config.yaml: it keeps the upstream 1,285 lines verbatim and rewrites
only the `exporters:` and `service:` sections from the LANES table below.

Re-run it after any edit to config.yaml to pick the change up in all four lanes.

THE MATRIX
----------
  rig4_oss_t   OSS  5082  spans YES
  rig4_oss_nt  OSS  5082  spans NO
  rig4_ent_t   ENT  5084  spans YES
  rig4_ent_nt  ENT  5084  spans NO

HOW THESE ORGS GET CREATED -- DO NOT USE THE ORG-CREATE API
-----------------------------------------------------------
Never call `POST /api/organizations` to make a rig org. That endpoint IGNORES a
supplied `identifier` and always mints a random ksuid, so it creates a NEW org
with a random id and a DUPLICATE display name on every call -- it is not
idempotent on name. (Proved: posting {"name":"x","identifier":"x"} returned
identifier=3I4avCofDhOQwoGFo5i9yzO0zBe.) An earlier round of this rig produced
five such ghost orgs that way, and org deletion is `#[cfg(feature = "cloud")]`-
gated (router mod.rs ~line 1278), so on an OSS/enterprise build they cannot be
removed -- every delete shape returns 404.

Instead, just INGEST to the identifier you want: the first ingest write as root
auto-creates the org with that EXACT identifier. See validator.rs:758
(`check_and_create_org` off the URL path, gated on ZO_CREATE_ORG_THROUGH_INGESTION,
default true) and organization.rs:756 (`identifier: org_id.to_owned()`). So these
four lanes need no provisioning step at all -- pointing the exporters here IS the
creation.

THE TRACES / NO-TRACES SPLIT is enforced STRUCTURALLY: a traces exporter is
emitted only for lanes with traces=True, and the traces pipeline lists only those.
No *_notrace traces exporter exists anywhere in the output, so a span has no route
to a no-trace org. That is a structural guarantee rather than a filter that could
be misconfigured or a network alias any stray OTLP client could defeat.
"""

import pathlib
import re

HERE = pathlib.Path(__file__).resolve().parent
SRC = HERE / "collector" / "config.yaml"
OUT = HERE / "collector" / "config.quad.yaml"

OSS = "http://host.docker.internal:5082"
ENT = "http://host.docker.internal:5084"

# (org, endpoint, traces?)  -- org ids are CASE-SENSITIVE in O2.
LANES = [
    ("rig4_oss_t", OSS, True),
    ("rig4_oss_nt", OSS, False),
    ("rig4_ent_t", ENT, True),
    ("rig4_ent_nt", ENT, False),
]

# Bounded queue + capped retry: the shared config leaves both at defaults, which
# let a collector buffer without limit against a backend that stops answering
# (measured previously at 2.06 GiB RSS vs 95 MiB for a healthy sibling). A test
# rig wants fresh data, so a dead backend should shed on a timer, not buffer.
QUEUE_LOGS = "sending_queue: { enabled: true, num_consumers: 8, queue_size: 5000 }"
QUEUE_SMALL = "sending_queue: { enabled: true, num_consumers: 2, queue_size: 200 }"
RETRY = "retry_on_failure: { enabled: true, max_elapsed_time: 300s }"


def exporters_block() -> str:
    out = ["exporters:"]
    out.append("  # ---- GENERATED BY gen-quad-config.py -- DO NOT EDIT BY HAND ----")
    out.append("  # One logs + one metrics exporter per lane; traces only for trace lanes.")

    for org, ep, _ in LANES:
        out += [
            f"  otlphttp/{org}_logs:",
            f"    logs_endpoint: {ep}/api/{org}/v1/logs",
            "    headers:",
            "      Authorization: Basic ${env:O2_AUTH}",
            "      stream-name: dbm_server",
            "    tls: { insecure: true }",
            f"    {QUEUE_LOGS}",
            f"    {RETRY}",
        ]

    for org, ep, _ in LANES:
        out += [
            f"  otlphttp/{org}_metrics:",
            f"    metrics_endpoint: {ep}/api/{org}/v1/metrics",
            '    headers: { Authorization: "Basic ${env:O2_AUTH}" }',
            "    tls: { insecure: true }",
            f"    {QUEUE_SMALL}",
            f"    {RETRY}",
        ]

    out.append("  # TRACES: emitted ONLY for traces=True lanes. The absence of a")
    out.append("  # *_notrace traces exporter IS the no-traces guarantee.")
    for org, ep, traces in LANES:
        if not traces:
            continue
        out += [
            f"  otlphttp/{org}_traces:",
            f"    traces_endpoint: {ep}/api/{org}/v1/traces",
            '    headers: { Authorization: "Basic ${env:O2_AUTH}" }',
            "    tls: { insecure: true }",
            f"    {QUEUE_SMALL}",
            f"    {RETRY}",
        ]

    out += [
        "  debug:",
        "    verbosity: basic",
        "  # Raw-evidence sink. The path is OPENED, never CREATED -- /rawout must",
        "  # exist on the host before start or the collector dies in seconds.",
        "  file/raw_events:",
        "    path: /rawout/receiver-events.jsonl",
        "  # DETACHED on purpose: no rotation, measured ~90 GB/hour. Do not re-attach.",
        "  file/raw_recipes:",
        "    path: /rawout/recipe-rows.jsonl",
        "",
    ]
    return "\n".join(out)


def service_block(recipe_receivers: str) -> str:
    logs = ",\n          ".join(f"otlphttp/{o}_logs" for o, _, _ in LANES)
    metrics = ",\n          ".join(f"otlphttp/{o}_metrics" for o, _, _ in LANES)
    traces = ", ".join(f"otlphttp/{o}_traces" for o, _, t in LANES if t)

    return f"""service:
  extensions: [health_check, file_storage/o2dbm]
  telemetry:
    logs:
      level: info
  pipelines:
    # Receivers/processors are IDENTICAL to the shared config; only the exporter
    # lists differ -- each now names one exporter per lane.
    logs/receiver_events:
      receivers: [postgresql, mysql]
      processors: [memory_limiter/quad, transform/tag_source, resource/ident, batch]
      exporters:
        [
          {logs},
          file/raw_events,
        ]
    # memory_limiter FIRST, then filter/dbm before the batcher: dropped records
    # must never reach the batcher.
    logs:
      receivers:
        [
          {recipe_receivers}
        ]
      processors: [memory_limiter/quad, filter/dbm, transform/tag_source, resource/ident, batch]
      exporters:
        [
          {logs},
        ]
    metrics:
      receivers: [postgresql, mysql, otlp]
      processors: [memory_limiter/quad, resource/ident, batch]
      exporters:
        [
          {metrics},
        ]
    # CLIENT VANTAGE: workload spans. THIS is where the traces/no-traces
    # dimension is enforced -- only trace-lane exporters are listed, and no
    # no-trace traces exporter is defined anywhere in this file.
    traces:
      receivers: [otlp]
      processors: [memory_limiter/quad, resource/ident, batch]
      exporters: [{traces}]
"""


def main() -> None:
    src = SRC.read_text()

    # Keep everything upstream of `exporters:` verbatim -- that is the whole
    # point: receivers/processors stay in lockstep with the shared config.
    idx = src.index("\nexporters:\n")
    upstream = src[: idx + 1]

    # Carry the shared config's extensions block through unchanged.
    ext_start = src.index("\nextensions:\n")
    svc_start = src.index("\nservice:\n")
    extensions = src[ext_start + 1 : svc_start + 1]

    # Reuse the shared config's recipe-receiver list rather than restating it,
    # so a receiver added there is picked up here on the next regeneration.
    svc = src[svc_start:]
    m = re.search(r"    logs:\n      receivers:\n      \[\n(.*?)\n      \]", svc, re.S)
    if m:
        recipe_receivers = m.group(1).strip()
    else:
        m = re.search(r"    logs:\n      receivers:\n(.*?)\n      processors:", svc, re.S)
        if not m:
            raise SystemExit("could not locate the logs pipeline receiver list in config.yaml")
        body = m.group(1)
        names = re.findall(r"[\w/]+", body)
        names = [n for n in names if n not in ("receivers",)]
        recipe_receivers = ",\n          ".join(names) + ","

    limiter = """
  # memory_limiter: the guard the shared config lacks. Without it a backend that
  # stops answering makes the collector buffer instead of shed. It MUST be first
  # in every pipeline's processor list -- a limiter after the batcher never sees
  # the data that is actually accumulating.
  memory_limiter/quad:
    check_interval: 1s
    limit_mib: 3072
    spike_limit_mib: 768
"""

    header = (
        "# GENERATED FILE -- edit gen-quad-config.py and re-run it, not this file.\n"
        "# Derived from collector/config.yaml (kept verbatim upstream of `exporters:`).\n"
        "# ONE collector -> FOUR orgs across TWO servers:\n"
        "#   oss_trace / oss_notrace          -> OSS 5082\n"
        "#   enterprise_trace / enterprise_notrace -> ENT 5084\n"
        "# Traces reach only the two *_trace orgs (no *_notrace traces exporter exists).\n"
    )

    OUT.write_text(
        header + upstream.rstrip("\n") + "\n" + limiter + "\n"
        + exporters_block() + "\n"
        + extensions.rstrip("\n") + "\n\n"
        + service_block(recipe_receivers)
    )
    print(f"wrote {OUT} ({len(OUT.read_text().splitlines())} lines)")
    for org, ep, t in LANES:
        print(f"  {org:<20} {ep}  traces={'YES' if t else 'NO'}")


if __name__ == "__main__":
    main()
