#!/usr/bin/env bash
# ONE rig -> FOUR orgs across TWO servers (OSS 5082 / enterprise 5084).
#
#   rig4_oss_t   OSS 5082  spans YES
#   rig4_oss_nt  OSS 5082  spans NO
#   rig4_ent_t   ENT 5084  spans YES
#   rig4_ent_nt  ENT 5084  spans NO
#
# The orgs need NO provisioning step: the first ingest write as root auto-creates
# an org with the exact identifier in the URL. Never call POST /api/organizations
# for a rig org -- it ignores a supplied identifier, mints a random ksuid, and is
# not idempotent on name, so it silently creates duplicate-named ghost orgs that
# cannot be deleted on a non-cloud build. See gen-quad-config.py's header.
#
# ONE set of databases, ONE workload, ONE collector. The collector's config is
# GENERATED by gen-quad-config.py from the shared collector/config.yaml, so the
# 1,390-line shared file is never edited. The org appears in exactly one place --
# the exporter URL -- and an OTel pipeline takes a LIST of exporters, so feeding
# four orgs is a config concern, not a process concern. Four collectors would run
# 4x the scrape load on the same five databases purely to vary that URL (and did
# previously OOM-kill each other on this 8 GiB Docker VM).
#
# TRACES SPLIT: the workload sends spans to ONE OTLP endpoint (collector:4318) and
# the collector's traces pipeline fans them out to the two *_trace orgs only. No
# *_notrace traces exporter exists, so a span has no route to a no-trace org. This
# is why the workload does not need to know about the matrix at all.
#
# The DATABASES and WORKLOAD come from the ORIGINAL docker-compose.yml (`make up`).
# This script adds ONLY the quad collector alongside them, so `make up`/`make down`
# keep working unchanged.
#
# TRAP: `file/raw_events` OPENS its path but never CREATES it. A missing /rawout
# kills the collector within seconds and `docker ps` simply shows nothing -- always
# check `docker ps -a` and `docker logs`. This script pre-creates the directory.
#
# Usage: ./quad-rig.sh up | down | status | logs | mem
set -uo pipefail

HOSTBASE="/Users/ashishkolhe/Documents/github/openobserve/.claude/worktrees/db-monitoring/tests/dbm-server-vantage"
BASE="/host_mnt${HOSTBASE}"
IMAGE="otel/opentelemetry-collector-contrib:0.158.0"
AUTH="YUBhLmNvbTpQYXNzIzEyMw=="   # a@a.com:Pass#123
NET="dbm-sv_default"
NAME="dbm-sv-col-quad"

case "${1:-up}" in
  up)
    # Regenerate so the lane config always matches the shared config.yaml.
    python3 "$HOSTBASE/gen-quad-config.py" || { echo "config generation FAILED"; exit 1; }

    mkdir -p "$HOSTBASE/captures/raw_quad"
    : > "$HOSTBASE/captures/raw_quad/receiver-events.jsonl"
    : > "$HOSTBASE/captures/raw_quad/recipe-rows.jsonl"

    timeout 30 docker rm -f "$NAME" >/dev/null 2>&1

    # `collector` alias: the compose workload exports to http://collector:4318 and
    # keeps working unchanged whether the compose collector or this one is up.
    timeout 60 docker run -d --name "$NAME" \
      --network "$NET" \
      --network-alias collector \
      --network-alias collector-quad \
      --user 0:0 -m 4608m \
      --add-host host.docker.internal:host-gateway \
      -e PGHOST=postgres -e PGPORT=5432 -e PGUSER=dbm -e PGPASS=dbm -e PGDATABASE=dbmlab \
      -e MYSQLHOST=mysql -e MYSQLPORT=3306 -e MYSQLUSER=root -e MYSQLPASS=dbm -e MYSQLDB=dbmlab \
      -e MARIAHOST=mariadb -e MARIAPORT=3306 -e MARIAUSER=root -e MARIAPASS=dbm -e MARIADB=dbmlab \
      -e MSSQLHOST=mssql -e MSSQLPORT=1433 -e MSSQLUSER=sa -e 'MSSQLPASS=dbm_Passw0rd#1' -e MSSQLDB=dbmlab \
      -e "O2_AUTH=$AUTH" \
      -v dbm-sv-colstate-quad:/var/lib/otelcol \
      -v "$BASE/captures/raw_quad":/rawout \
      -v "$BASE/collector/config.quad.yaml":/etc/otelcol-contrib/config.yaml:ro \
      -v dbm-sv_pglogs:/pglogs:ro -v dbm-sv_mysqllogs:/mysqllogs:ro -v dbm-sv_mariadblogs:/mariadblogs:ro \
      "$IMAGE" --config=/etc/otelcol-contrib/config.yaml >/dev/null \
      || { echo "docker run FAILED"; exit 1; }

    sleep 20
    st=$(timeout 30 docker inspect "$NAME" --format 'status={{.State.Status}} oom={{.State.OOMKilled}} exit={{.State.ExitCode}}' 2>/dev/null)
    echo "$NAME: $st"
    if ! printf '%s' "$st" | grep -q 'status=running'; then
      echo "FAILED TO STAY UP -- last logs:"
      timeout 30 docker logs --tail 20 "$NAME" 2>&1 | cut -c1-220 | sed 's/^/    /'
      exit 1
    fi
    # `docker logs | grep -q` exits 141 (SIGPIPE) because grep -q closes the pipe
    # on first match, which reads as a false failure. Count instead.
    if [ "$(timeout 30 docker logs "$NAME" 2>&1 | grep -c 'Everything is ready')" -gt 0 ]; then
      echo "pipelines ready -> rig4_oss_t, rig4_oss_nt (5082) + rig4_ent_t, rig4_ent_nt (5084)"
    fi
    ;;
  down)
    timeout 30 docker rm -f "$NAME" >/dev/null 2>&1 && echo "removed $NAME"
    timeout 30 docker volume rm dbm-sv-colstate-quad >/dev/null 2>&1 && echo "removed state volume"
    ;;
  status)
    timeout 30 docker ps -a --filter "name=$NAME" --format '{{.Names}}\t{{.Status}}'
    ;;
  logs)
    timeout 30 docker logs --tail "${2:-60}" "$NAME" 2>&1 | cut -c1-240
    ;;
  mem)
    timeout 30 docker stats --no-stream --format '{{.Name}}\t{{.MemUsage}}\tcpu={{.CPUPerc}}' "$NAME"
    echo -n "data refused (last 2m): "; timeout 60 docker logs --since 2m "$NAME" 2>&1 | grep -c "data refused"
    echo -n "queue full   (last 2m): "; timeout 60 docker logs --since 2m "$NAME" 2>&1 | grep -c "sending queue is full"
    ;;
esac
