// Copyright 2026 OpenObserve Inc.
//
// Structural guards for the catalog. Both rules below fail silently in the UI —
// a repeated emoji just looks like a rendering glitch, and a shared keyword
// resolves to whichever group sorts first — so they are asserted here rather
// than left to review.

import { describe, it, expect } from "vitest";
import { EMOJI_GROUPS, ALL_EMOJIS } from "./emojiCatalog";
import {
  GLYPH_REGISTRY,
  GLYPH_TOKEN_PREFIX,
  AI_GLYPH_SLUGS,
  AI_GLYPH_PREFIX,
  isAiGlyphToken,
  resolveGlyph,
} from "./glyphRegistry";

describe("emojiCatalog", () => {
  it("should never repeat an emoji, which would render a duplicate grid cell", () => {
    const seen = new Map<string, string[]>();
    for (const group of EMOJI_GROUPS) {
      for (const option of group.emojis) {
        seen.set(option.token, [...(seen.get(option.token) ?? []), group.id]);
      }
    }
    const repeated = [...seen.entries()].filter(([, groups]) => groups.length > 1);
    expect(repeated).toEqual([]);
  });

  it("should give every keyword exactly one owner, so suggestions never depend on order", () => {
    const owners = new Map<string, string[]>();
    for (const option of ALL_EMOJIS) {
      for (const keyword of option.keywords) {
        owners.set(keyword, [...(owners.get(keyword) ?? []), option.token]);
      }
    }
    const shared = [...owners.entries()].filter(([, emojis]) => emojis.length > 1);
    expect(shared).toEqual([]);
  });

  it("should use lowercase keywords with no whitespace, as the matcher assumes", () => {
    for (const option of ALL_EMOJIS) {
      for (const keyword of option.keywords) {
        expect(keyword).toBe(keyword.toLowerCase());
        expect(keyword).not.toMatch(/\s/);
        expect(keyword.length).toBeGreaterThan(0);
      }
    }
  });

  it("should give every group a unique id and at least one emoji", () => {
    const ids = EMOJI_GROUPS.map((group) => group.id);
    expect(new Set(ids).size).toBe(ids.length);
    for (const group of EMOJI_GROUPS) {
      expect(group.emojis.length).toBeGreaterThan(0);
    }
  });

  it("should not reuse the reserved 'results' id, which the search view injects", () => {
    expect(EMOJI_GROUPS.map((group) => group.id)).not.toContain("results");
  });

  // The registry and the catalog are edited separately, so they drift silently:
  // a glyph with no catalog entry ships bytes nobody can pick, and a catalog
  // token with no glyph renders as a blank cell. Both directions are checked.
  it("should offer every registered glyph in the picker", () => {
    const offered = new Set(ALL_EMOJIS.map((option) => option.token));
    const unreachable = Object.keys(GLYPH_REGISTRY).filter(
      (name) => !offered.has(`${GLYPH_TOKEN_PREFIX}${name}`),
    );
    expect(unreachable).toEqual([]);
  });

  // The AI logos live in a second namespace whose slug space is regenerated by
  // the o2-datasource sync, so both directions matter: a slug we allowlist but
  // never offer ships nothing, and a sync that DROPS a slug would otherwise
  // render a blank cell. The generic "resolve every token" test above already
  // covers the second case, since "o2:ai-…" also starts with "o2:".
  it("should offer every allowlisted AI integration in the picker", () => {
    const offered = new Set(ALL_EMOJIS.map((option) => option.token));
    const unreachable = AI_GLYPH_SLUGS.filter((slug) => !offered.has(`${AI_GLYPH_PREFIX}${slug}`));
    expect(unreachable).toEqual([]);
  });

  it("should keep the AI namespace distinct from the curated one", () => {
    // "databricks" exists in both spaces — the prefixes must not blur them.
    expect(resolveGlyph("o2:databricks")).not.toBe(resolveGlyph("o2:ai-databricks"));
    expect(resolveGlyph("o2:ai-not-a-real-brand")).toBeNull();
  });

  it("should resolve every curated glyph token the catalog offers", () => {
    const broken = ALL_EMOJIS.map((option) => option.token)
      .filter((token) => token.startsWith(GLYPH_TOKEN_PREFIX) && !isAiGlyphToken(token))
      .filter((token) => resolveGlyph(token) === null);
    expect(broken).toEqual([]);
  });

  // AI logos come from the gitignored generated/ dir, absent until
  // fetch-datasource-content.mjs has run — so a fresh checkout or CI without the
  // fetch would fail this through no fault of the catalog. Same stance
  // modelVendorLogo.spec.ts takes over that directory.
  it("should resolve every AI glyph token when the assets are bundled", () => {
    const aiTokens = ALL_EMOJIS.map((option) => option.token).filter(isAiGlyphToken);
    const resolved = aiTokens.filter((token) => resolveGlyph(token) !== null);
    if (resolved.length === 0) return; // assets not fetched in this environment

    const broken = aiTokens.filter((token) => resolveGlyph(token) === null);
    expect(broken).toEqual([]);
  });

  // Every data source the Ingestion pages list should be pickable as a folder
  // icon, so a "Postgres" folder can carry the same logo the integration tile
  // shows.
  //
  // The list is DERIVED from the filesystem, not hand-maintained. A hardcoded
  // array is what let FileBeat, Categraf, Nightingale, VMagent, LoongCollector,
  // macOS and Windows ship without icons while this test still passed: they were
  // simply never added to it. Reading the components means adding an integration
  // without a glyph fails here on its own.
  it("should cover every service on the integrations pages", () => {
    // Vite resolves this at transform time, so it needs no filesystem paths and
    // works the same in vitest as in the app build. Per-service pages live one
    // level down (databases/Postgres.vue); the top level holds category pages
    // and layout, which are not data sources.
    const modules = import.meta.glob("../../../components/ingestion/*/*.vue");

    // Component name -> glyph key, only where they differ. Anything absent is
    // matched by its lowercased component name.
    const GLYPH_FOR: Record<string, string> = {
      Postgres: "postgresql",
      SqlServer: "sqlserver",
      SAPHana: "saphana",
      GithubActions: "githubactions",
      GoogleWorkspace: "googleworkspace",
      OSQuery: "osquery",
      DotNetLogs: "dotnet",
      DotNetTracing: "dotnet",
      LogstashDatasource: "logstash",
      SyslogNg: "syslog",
      OtelCollector: "opentelemetry",
      OtelConfig: "opentelemetry",
      OpenTelemetry: "opentelemetry",
      CloudWatchMetrics: "cloudwatch",
      PrometheusConfig: "prometheus",
      TelegrafConfig: "telegraf",
      CategrafConfig: "categraf",
      NightingaleConfig: "nightingale",
      VMagentConfig: "vmagent",
      KubernetesConfig: "kubernetes",
      LinuxConfig: "linux",
      MacOSConfig: "macos",
      WindowsConfig: "windows",
      AWSConfig: "aws",
      AWSIndividualServices: "aws",
      AzureConfig: "azure",
      GCPConfig: "gcp",
    };

    // Not third-party products, so there is no vendor mark to ship:
    //   Index          — the category landing page, not a service
    //   FrontendRum    — OpenObserve's own browser RUM setup
    //   AWSIntegrationTile / AWSQuickSetup — UI pieces of the AWS page
    const NOT_A_SERVICE = new Set([
      "Index",
      "FrontendRumConfig",
      "AWSIntegrationTile",
      "AWSQuickSetup",
    ]);

    // Directories that hold UI, not data sources. `ai/` holds card and detail
    // COMPONENTS, not one page per provider — the AI providers themselves are
    // data (ai/data.ts) and their logos are covered separately by
    // AI_GLYPH_SLUGS, asserted in its own test above.
    const NOT_SERVICE_DIRS = new Set(["ai", "setupCard"]);

    const services: string[] = [];
    for (const path of Object.keys(modules)) {
      const segments = path.split("/");
      const dir = segments[segments.length - 2];
      if (NOT_SERVICE_DIRS.has(dir)) continue;
      const component = segments[segments.length - 1].slice(0, -".vue".length);
      if (NOT_A_SERVICE.has(component)) continue;
      services.push(GLYPH_FOR[component] ?? component.toLowerCase());
    }
    // A silent zero would make this test vacuous if the tree ever moves.
    expect(services.length).toBeGreaterThan(60);

    const missing = [...new Set(services)].filter(
      (name) => resolveGlyph(`${GLYPH_TOKEN_PREFIX}${name}`) === null,
    );
    expect(missing).toEqual([]);
  });
});
