// Copyright 2026 OpenObserve Inc.
//
// The icon catalog behind OEmojiPicker. Entries are ICON TOKENS: either a
// Unicode emoji ("🚀") or a registry glyph reference ("o2:redis", see
// glyphRegistry.ts). Both kinds live in one list so search, suggestion and
// rendering treat them identically.
//
// Deliberately curated rather than exhaustive: everything here reads sensibly
// at 16px next to a folder name, and every glyph token costs bundle size.
// `keywords` drives both the picker's search box and the app-side name -> icon
// suggestion, so they are matching data (plain lowercase English), never
// user-facing copy.
//
// Two rules hold this file together, and the spec enforces both:
//
//  1. NO TOKEN APPEARS TWICE. A repeat renders as a duplicate cell in the grid.
//  2. NO KEYWORD HAS TWO OWNERS. Ties are broken by catalog order, so a shared
//     keyword silently resolves to whichever group comes first — which is how
//     "docker" once landed on a generic package box instead of the whale.
//
// Rule 2 is why the Brands group owns every PRODUCT name while the Creatures
// group keeps only the CREATURE names: typing "docker" gets you the Docker
// mark, and 🐳 is still there for anyone who just wants a whale.

import type { EmojiGroup } from "./OEmojiPicker.types";

export const EMOJI_GROUPS: readonly EmojiGroup[] = [
  {
    id: "status",
    labelKey: "components.emojiPicker.groups.status",
    emojis: [
      { token: "🚀", keywords: ["prod", "production", "launch", "release", "deploy", "ship"] },
      { token: "🔥", keywords: ["hot", "incident", "urgent", "fire", "critical", "burn"] },
      { token: "⚠️", keywords: ["warning", "warn", "caution", "risk"] },
      { token: "✅", keywords: ["ok", "pass", "passing", "done", "success", "complete"] },
      { token: "❌", keywords: ["fail", "failed", "failure", "error", "errors", "broken"] },
      { token: "🐛", keywords: ["bug", "bugs", "defect", "issue", "debug", "crash"] },
      { token: "🚨", keywords: ["alert", "alerts", "alarm", "siren", "escalation"] },
      { token: "🔒", keywords: ["security", "secure", "locked", "private", "encrypted"] },
      { token: "🔓", keywords: ["unlocked", "public", "open", "exposed"] },
      {
        token: "🛡️",
        keywords: ["protection", "defense", "compliance", "guard", "waf", "firewall"],
      },
      { token: "⏱️", keywords: ["latency", "duration", "timing", "sla", "response", "p99"] },
      { token: "⏳", keywords: ["pending", "waiting", "queue", "backlog", "delay", "throttled"] },
      { token: "📉", keywords: ["drop", "decline", "regression", "loss", "decrease"] },
      { token: "📈", keywords: ["metrics", "timeseries", "graph", "trend", "growth", "increase"] },
      { token: "🟢", keywords: ["green", "online", "live", "active", "up", "healthy"] },
      { token: "🔴", keywords: ["red", "offline", "outage", "down", "downtime", "stopped"] },
      { token: "🟡", keywords: ["yellow", "degraded", "partial", "amber", "flaky"] },
      { token: "🩺", keywords: ["health", "healthcheck", "diagnostics", "probe", "uptime"] },
    ],
  },
  {
    // Full-colour marks for the services OpenObserve integrates with — the same
    // logos the Ingestion pages show. Sits ahead of the generic groups so a
    // product name wins a tie: "Docker Hosts" is about Docker, not about hosts.
    id: "services",
    labelKey: "components.emojiPicker.groups.services",
    emojis: [
      { token: "o2:postgresql", keywords: ["postgres", "postgresql", "pgsql"] },
      { token: "o2:mysql", keywords: ["mysql"] },
      { token: "o2:mariadb", keywords: ["mariadb"] },
      { token: "o2:mongodb", keywords: ["mongo", "mongodb"] },
      { token: "o2:redis", keywords: ["redis", "valkey"] },
      { token: "o2:oracle", keywords: ["oracle"] },
      { token: "o2:snowflake", keywords: ["snowflake"] },
      { token: "o2:cassandra", keywords: ["cassandra", "scylla"] },
      { token: "o2:dynamodb", keywords: ["dynamodb"] },
      { token: "o2:aerospike", keywords: ["aerospike"] },
      { token: "o2:couchdb", keywords: ["couchdb", "couch"] },
      { token: "o2:sqlite", keywords: ["sqlite"] },
      { token: "o2:saphana", keywords: ["saphana", "sap", "hana"] },
      { token: "o2:sqlserver", keywords: ["sqlserver", "mssql"] },
      { token: "o2:zookeeper", keywords: ["zookeeper"] },
      { token: "o2:databricks", keywords: ["databricks"] },
      { token: "o2:kafka", keywords: ["kafka"] },
      { token: "o2:rabbitmq", keywords: ["rabbitmq", "amqp"] },
      { token: "o2:nats", keywords: ["nats"] },
      { token: "o2:spark", keywords: ["spark"] },
      { token: "o2:nginx", keywords: ["nginx", "reverseproxy"] },
      { token: "o2:apache", keywords: ["apache", "httpd"] },
      { token: "o2:iis", keywords: ["iis"] },
      { token: "o2:cloudflare", keywords: ["cloudflare"] },
      { token: "o2:syslog", keywords: ["syslog"] },
      { token: "o2:netflow", keywords: ["netflow"] },
      { token: "o2:openvpn", keywords: ["openvpn", "vpn"] },
      { token: "o2:kubernetes", keywords: ["kubernetes", "k8s", "kube", "cluster", "pods"] },
      { token: "o2:docker", keywords: ["docker", "container", "containers", "oci"] },
      { token: "o2:helm", keywords: ["helm", "helmchart"] },
      { token: "o2:argo", keywords: ["argo", "argocd", "gitops"] },
      { token: "o2:terraform", keywords: ["terraform", "iac", "hcl"] },
      { token: "o2:ansible", keywords: ["ansible", "playbook"] },
      { token: "o2:jenkins", keywords: ["jenkins"] },
      { token: "o2:githubactions", keywords: ["githubactions", "ci", "cicd"] },
      { token: "o2:vercel", keywords: ["vercel"] },
      { token: "o2:heroku", keywords: ["heroku"] },
      { token: "o2:airflow", keywords: ["airflow", "dags"] },
      { token: "o2:airbyte", keywords: ["airbyte"] },
      { token: "o2:vault", keywords: ["vault", "secretsmanager"] },
      { token: "o2:consul", keywords: ["consul"] },
      { token: "o2:linux", keywords: ["linux", "ubuntu", "debian", "rhel"] },
      { token: "o2:aws", keywords: ["aws", "amazon", "ec2", "lambda"] },
      { token: "o2:azure", keywords: ["azure"] },
      { token: "o2:gcp", keywords: ["gcp", "googlecloud", "bigquery"] },
      { token: "o2:cloudwatch", keywords: ["cloudwatch"] },
      { token: "o2:kinesis", keywords: ["kinesis", "firehose"] },
      { token: "o2:prometheus", keywords: ["prometheus", "promql"] },
      { token: "o2:grafana", keywords: ["grafana"] },
      { token: "o2:opentelemetry", keywords: ["opentelemetry", "otel", "otlp"] },
      { token: "o2:elasticsearch", keywords: ["elasticsearch", "elastic", "elk"] },
      { token: "o2:logstash", keywords: ["logstash"] },
      { token: "o2:kibana", keywords: ["kibana"] },
      { token: "o2:opensearch", keywords: ["opensearch"] },
      { token: "o2:influxdb", keywords: ["influxdb", "influx"] },
      { token: "o2:vector", keywords: ["vector", "vectordev"] },
      { token: "o2:datadog", keywords: ["datadog"] },
      { token: "o2:sentry", keywords: ["sentry"] },
      { token: "o2:fluentd", keywords: ["fluentd"] },
      { token: "o2:fluentbit", keywords: ["fluentbit", "fluent"] },
      { token: "o2:telegraf", keywords: ["telegraf"] },
      { token: "o2:cribl", keywords: ["cribl"] },
      { token: "o2:filebeat", keywords: ["filebeat", "beats"] },
      { token: "o2:loongcollector", keywords: ["loongcollector", "loong"] },
      { token: "o2:categraf", keywords: ["categraf"] },
      { token: "o2:nightingale", keywords: ["nightingale", "n9e"] },
      { token: "o2:vmagent", keywords: ["vmagent", "victoriametrics"] },
      { token: "o2:macos", keywords: ["macos", "mac", "osx", "darwin"] },
      { token: "o2:windows", keywords: ["windows", "winlogbeat", "win32"] },
      { token: "o2:curl", keywords: ["curl"] },
      { token: "o2:java", keywords: ["java", "jvm", "kotlin", "spring"] },
      { token: "o2:python", keywords: ["python", "py", "django", "flask"] },
      { token: "o2:rust", keywords: ["rust", "cargo"] },
      { token: "o2:go", keywords: ["go", "golang", "gopher"] },
      { token: "o2:nodejs", keywords: ["nodejs", "npm"] },
      { token: "o2:dotnet", keywords: ["dotnet", "csharp"] },
      { token: "o2:fastapi", keywords: ["fastapi"] },
      { token: "o2:typescript", keywords: ["typescript"] },
      { token: "o2:react", keywords: ["react"] },
      { token: "o2:vue", keywords: ["vue", "vuejs"] },
      { token: "o2:graphql", keywords: ["graphql"] },
      { token: "o2:github", keywords: ["github", "git", "repo", "vcs"] },
      { token: "o2:gitlab", keywords: ["gitlab"] },
      { token: "o2:jira", keywords: ["jira"] },
      { token: "o2:slack", keywords: ["slack"] },
      { token: "o2:pagerduty", keywords: ["pagerduty"] },
      { token: "o2:opsgenie", keywords: ["opsgenie"] },
      { token: "o2:okta", keywords: ["okta", "sso"] },
      { token: "o2:osquery", keywords: ["osquery"] },
      { token: "o2:falco", keywords: ["falco"] },
      { token: "o2:jumpcloud", keywords: ["jumpcloud"] },
      { token: "o2:googleworkspace", keywords: ["googleworkspace", "gsuite"] },
      { token: "o2:office365", keywords: ["office365", "o365", "microsoft"] },
    ],
  },
  {
    // AI Integrations — one cell per BRAND, not per SDK, so the four Anthropic
    // slugs upstream don't become four cells fighting over "claude".
    // Roster lives in AI_GLYPH_SLUGS (glyphRegistry.ts).
    id: "ai",
    labelKey: "components.emojiPicker.groups.ai",
    emojis: [
      { token: "o2:ai-agno", keywords: ["agno"] },
      { token: "o2:ai-amazon-bedrock", keywords: ["bedrock", "amazonbedrock"] },
      { token: "o2:ai-anannas", keywords: ["anannas"] },
      { token: "o2:ai-anthropic", keywords: ["anthropic", "claude"] },
      { token: "o2:ai-autogen", keywords: ["autogen"] },
      { token: "o2:ai-beeai", keywords: ["beeai"] },
      { token: "o2:ai-byteplus", keywords: ["byteplus"] },
      { token: "o2:ai-cerebras", keywords: ["cerebras"] },
      { token: "o2:ai-claude-code", keywords: ["claudecode"] },
      { token: "o2:ai-codename-goose", keywords: ["goose"] },
      { token: "o2:ai-codex", keywords: ["codex"] },
      { token: "o2:ai-cognee", keywords: ["cognee"] },
      { token: "o2:ai-cohere", keywords: ["cohere"] },
      { token: "o2:ai-cometapi", keywords: ["cometapi"] },
      { token: "o2:ai-crewai", keywords: ["crewai"] },
      { token: "o2:ai-cursor", keywords: ["cursor"] },
      { token: "o2:ai-deepagents", keywords: ["deepagents"] },
      { token: "o2:ai-deepseek", keywords: ["deepseek"] },
      { token: "o2:ai-dspy", keywords: ["dspy"] },
      { token: "o2:ai-exa", keywords: ["exa"] },
      { token: "o2:ai-firecrawl", keywords: ["firecrawl"] },
      { token: "o2:ai-fireworks", keywords: ["fireworks"] },
      { token: "o2:ai-flowise", keywords: ["flowise"] },
      { token: "o2:ai-gemini", keywords: ["gemini"] },
      { token: "o2:ai-github-copilot", keywords: ["copilot", "githubcopilot"] },
      { token: "o2:ai-google-adk", keywords: ["googleadk", "adk"] },
      { token: "o2:ai-gradio", keywords: ["gradio"] },
      { token: "o2:ai-groq", keywords: ["groq"] },
      { token: "o2:ai-haystack", keywords: ["haystack"] },
      { token: "o2:ai-huggingface", keywords: ["huggingface", "hf"] },
      { token: "o2:ai-instructor", keywords: ["instructor"] },
      { token: "o2:ai-kong-gateway", keywords: ["kong"] },
      { token: "o2:ai-koog", keywords: ["koog"] },
      { token: "o2:ai-langchain", keywords: ["langchain"] },
      { token: "o2:ai-langflow", keywords: ["langflow"] },
      { token: "o2:ai-langgraph", keywords: ["langgraph"] },
      { token: "o2:ai-langserve", keywords: ["langserve"] },
      { token: "o2:ai-librechat", keywords: ["librechat"] },
      { token: "o2:ai-litellm", keywords: ["litellm"] },
      { token: "o2:ai-livekit", keywords: ["livekit"] },
      { token: "o2:ai-llamaindex", keywords: ["llamaindex"] },
      { token: "o2:ai-lobechat", keywords: ["lobechat"] },
      { token: "o2:ai-mastra", keywords: ["mastra"] },
      { token: "o2:ai-mcp-use", keywords: ["mcpuse"] },
      { token: "o2:ai-microsoft-agent-framework", keywords: ["agentframework"] },
      { token: "o2:ai-milvus", keywords: ["milvus"] },
      { token: "o2:ai-mirascope", keywords: ["mirascope"] },
      { token: "o2:ai-mistral", keywords: ["mistral"] },
      { token: "o2:ai-mixpanel", keywords: ["mixpanel"] },
      { token: "o2:ai-n8n", keywords: ["n8n"] },
      { token: "o2:ai-novita", keywords: ["novita"] },
      { token: "o2:ai-ollama", keywords: ["ollama"] },
      { token: "o2:ai-openai", keywords: ["openai", "gpt", "chatgpt"] },
      { token: "o2:ai-opencode", keywords: ["opencode"] },
      { token: "o2:ai-openrouter", keywords: ["openrouter"] },
      { token: "o2:ai-openwebui", keywords: ["openwebui"] },
      { token: "o2:ai-parallel", keywords: ["parallelai"] },
      { token: "o2:ai-pipecat", keywords: ["pipecat"] },
      { token: "o2:ai-portkey", keywords: ["portkey"] },
      { token: "o2:ai-posthog", keywords: ["posthog"] },
      { token: "o2:ai-promptfoo", keywords: ["promptfoo"] },
      { token: "o2:ai-pydantic-ai", keywords: ["pydantic", "pydanticai"] },
      { token: "o2:ai-quarkus-langchain4j", keywords: ["quarkus", "langchain4j"] },
      { token: "o2:ai-ragas", keywords: ["ragas"] },
      { token: "o2:ai-semantic-kernel", keywords: ["semantickernel"] },
      { token: "o2:ai-smolagents", keywords: ["smolagents"] },
      { token: "o2:ai-spring-ai", keywords: ["springai"] },
      { token: "o2:ai-strands-agents", keywords: ["strands"] },
      { token: "o2:ai-swiftide", keywords: ["swiftide"] },
      { token: "o2:ai-temporal", keywords: ["temporal"] },
      { token: "o2:ai-together-ai", keywords: ["togetherai", "together"] },
      { token: "o2:ai-trubrics", keywords: ["trubrics"] },
      { token: "o2:ai-vapi", keywords: ["vapi"] },
      { token: "o2:ai-vercel-ai-sdk", keywords: ["vercelai"] },
      { token: "o2:ai-vllm", keywords: ["vllm"] },
      { token: "o2:ai-voltagent", keywords: ["voltagent"] },
      { token: "o2:ai-xai-grok", keywords: ["grok", "xai"] },
      { token: "o2:ai-zapier", keywords: ["zapier"] },
    ],
  },
  {
    // The animals and objects the Brands group borrows its mascots from. These
    // keep only the CREATURE word, never the product name.
    id: "creatures",
    labelKey: "components.emojiPicker.groups.creatures",
    emojis: [
      { token: "🐳", keywords: ["whale", "moby", "orca"] },
      { token: "🐘", keywords: ["elephant"] },
      { token: "🐬", keywords: ["dolphin"] },
      { token: "🍃", keywords: ["leaf", "foliage", "herb"] },
      { token: "🐇", keywords: ["rabbit", "bunny", "hare"] },
      { token: "🐍", keywords: ["snake", "serpent", "viper"] },
      { token: "🦀", keywords: ["crab", "ferris", "shellfish"] },
      { token: "🐹", keywords: ["hamster"] },
      { token: "☕", keywords: ["coffee", "espresso", "brew", "cafe"] },
      { token: "🐧", keywords: ["penguin"] },
      { token: "🐙", keywords: ["octopus", "tentacles", "kraken"] },
      { token: "🦊", keywords: ["fox", "firefox"] },
      { token: "⚛️", keywords: ["atom", "physics", "nuclear"] },
      { token: "🤖", keywords: ["bot", "robot", "automaton", "android"] },
      { token: "🍎", keywords: ["apple", "fruit"] },
    ],
  },
  {
    id: "infra",
    labelKey: "components.emojiPicker.groups.infra",
    emojis: [
      { token: "🗄️", keywords: ["database", "db", "sql", "storage", "schema", "warehouse"] },
      { token: "☁️", keywords: ["cloud", "saas", "s3", "bucket"] },
      { token: "🖥️", keywords: ["server", "host", "hosts", "node", "nodes", "machine", "vm"] },
      { token: "🌐", keywords: ["network", "web", "http", "dns", "internet", "edge", "cdn"] },
      { token: "⚙️", keywords: ["config", "settings", "system", "engine", "ops", "runtime"] },
      { token: "📦", keywords: ["package", "packages", "artifact", "bundle", "dependency"] },
      { token: "🔧", keywords: ["maintenance", "tooling", "fix", "repair", "wrench"] },
      { token: "🧱", keywords: ["platform", "infra", "infrastructure", "foundation", "core"] },
      { token: "🏗️", keywords: ["staging", "construction", "buildout", "scaffold", "build"] },
      { token: "🔌", keywords: ["integration", "plugin", "connector", "api", "webhook"] },
      { token: "🛰️", keywords: ["telemetry", "agent", "collector", "satellite", "remote"] },
      { token: "🧭", keywords: ["routing", "gateway", "proxy", "ingress", "discovery"] },
      { token: "💾", keywords: ["disk", "volume", "backup", "persistence", "snapshot"] },
      { token: "🔗", keywords: ["link", "links", "chain", "upstream", "downstream", "linked"] },
      { token: "🕸️", keywords: ["mesh", "service", "services", "microservices", "topology"] },
      { token: "⚡", keywords: ["performance", "perf", "fast", "speed", "cache", "realtime"] },
      { token: "🧊", keywords: ["cold", "frozen", "tier", "glacier"] },
      { token: "🔁", keywords: ["retry", "loop", "sync", "replication", "pipeline", "etl"] },
    ],
  },
  {
    id: "data",
    labelKey: "components.emojiPicker.groups.data",
    emojis: [
      { token: "📊", keywords: ["dashboard", "dashboards", "chart", "charts", "analytics"] },
      { token: "🧮", keywords: ["calculation", "aggregate", "count", "math", "sum"] },
      { token: "🔍", keywords: ["search", "query", "queries", "explore", "find", "inspect"] },
      { token: "🧪", keywords: ["test", "tests", "testing", "experiment", "qa", "lab"] },
      { token: "📋", keywords: ["report", "reports", "list", "summary", "clipboard"] },
      { token: "🗂️", keywords: ["index", "catalog", "organize", "sections", "tabs"] },
      { token: "🧾", keywords: ["billing", "invoice", "usage", "cost", "receipt", "spend"] },
      { token: "📁", keywords: ["folder", "folders", "files", "general", "default"] },
      { token: "📌", keywords: ["pinned", "bookmark", "sticky", "saved", "shortcuts"] },
      { token: "🗃️", keywords: ["archive", "archived", "records", "dataset", "table", "store"] },
      { token: "🔢", keywords: ["numbers", "counters", "stats", "quota", "limits"] },
      { token: "🧬", keywords: ["trace", "traces", "span", "spans", "lineage", "correlation"] },
      { token: "📐", keywords: ["blueprint", "spec", "structure", "layout", "geometry"] },
      { token: "🗺️", keywords: ["map", "overview", "landscape", "plan", "roadmap"] },
      { token: "📝", keywords: ["logs", "log", "notes", "journal", "changelog", "write"] },
      { token: "🧠", keywords: ["ai", "ml", "model", "models", "intelligence", "anomaly"] },
      { token: "🔬", keywords: ["analysis", "research", "deep", "microscope", "rca"] },
    ],
  },
  {
    id: "teams",
    labelKey: "components.emojiPicker.groups.teams",
    emojis: [
      { token: "👥", keywords: ["team", "teams", "group", "groups", "users", "people"] },
      { token: "🧑‍💻", keywords: ["engineering", "developer", "dev", "coding", "code"] },
      { token: "🛠️", keywords: ["devops", "sre", "tools", "operations", "toolchain"] },
      { token: "🎯", keywords: ["goals", "objectives", "targets", "okr", "focus", "slo", "sli"] },
      { token: "🏢", keywords: ["company", "org", "organization", "business", "enterprise"] },
      { token: "💼", keywords: ["work", "projects", "portfolio", "client", "account"] },
      { token: "📣", keywords: ["marketing", "announcements", "broadcast", "megaphone"] },
      { token: "🤝", keywords: ["partners", "shared", "collaboration", "vendor", "customer"] },
      {
        token: "🕵️",
        keywords: ["audit", "investigation", "investigate", "forensics", "detective"],
      },
      { token: "🎧", keywords: ["support", "helpdesk", "tickets", "csat"] },
      { token: "👤", keywords: ["personal", "mine", "user", "individual", "profile"] },
      { token: "🏆", keywords: ["wins", "top", "best", "achievement", "award", "leaderboard"] },
      { token: "✉️", keywords: ["email", "mail", "inbox", "message", "destination"] },
      { token: "🗓️", keywords: ["schedule", "calendar", "weekly", "monthly", "planning"] },
      { token: "📞", keywords: ["oncall", "paging", "pager", "call", "phone", "rotation"] },
      { token: "🧑‍🚀", keywords: ["exploration", "mission", "pioneer", "beta", "preview"] },
    ],
  },
  {
    id: "objects",
    labelKey: "components.emojiPicker.groups.objects",
    emojis: [
      { token: "💡", keywords: ["ideas", "insights", "proposal", "tips", "light"] },
      { token: "🔑", keywords: ["keys", "credentials", "secrets", "tokens", "iam", "access"] },
      { token: "⭐", keywords: ["favorites", "starred", "important", "featured", "highlights"] },
      { token: "❤️", keywords: ["favorite", "loved", "liked", "hearts"] },
      { token: "🔔", keywords: ["notifications", "reminders", "bell", "subscribe"] },
      { token: "🔕", keywords: ["muted", "silenced", "snoozed", "paused", "disabled"] },
      { token: "🧩", keywords: ["modules", "plugins", "components", "pieces", "extensions"] },
      { token: "🎨", keywords: ["design", "ui", "ux", "theme", "branding", "frontend"] },
      { token: "🎉", keywords: ["celebration", "milestone", "party", "anniversary"] },
      { token: "📚", keywords: ["docs", "documentation", "library", "reference", "guides"] },
      { token: "🏷️", keywords: ["labels", "tags", "categories", "taxonomy"] },
      { token: "🧰", keywords: ["toolbox", "utilities", "helpers", "misc", "kit"] },
      { token: "🪄", keywords: ["automation", "magic", "generated", "auto", "wizard"] },
      { token: "🧹", keywords: ["cleanup", "retention", "housekeeping", "purge", "gc"] },
      { token: "🗑️", keywords: ["trash", "deprecated", "removed", "old", "obsolete"] },
      { token: "🚧", keywords: ["wip", "draft", "experimental", "temp", "unfinished"] },
    ],
  },
  {
    id: "world",
    labelKey: "components.emojiPicker.groups.world",
    emojis: [
      { token: "🌍", keywords: ["global", "world", "region", "regions", "eu", "emea", "earth"] },
      { token: "🌎", keywords: ["americas", "us", "usa", "west", "amer", "latam"] },
      { token: "🌏", keywords: ["apac", "asia", "east", "japan", "india"] },
      { token: "🪐", keywords: ["orbit", "universe", "everything", "space", "wide"] },
      { token: "🌱", keywords: ["new", "seed", "starter", "sprout", "sandbox"] },
      { token: "🌊", keywords: ["stream", "streams", "streaming", "flow", "ingest", "wave"] },
      { token: "🍀", keywords: ["luck", "canary", "lucky", "clover"] },
      { token: "🌙", keywords: ["nightly", "night", "offhours", "dark", "cron"] },
      { token: "☀️", keywords: ["daily", "day", "daytime", "sunny", "peak"] },
      { token: "🌈", keywords: ["variety", "mixed", "colorful", "diverse", "all"] },
      { token: "🦉", keywords: ["observability", "owl", "o11y", "nocturnal"] },
      { token: "🔭", keywords: ["monitoring", "monitor", "watch", "synthetics", "telescope"] },
    ],
  },
] as const;

/** Flat view of the catalog — used by search and by the app-side suggester. */
export const ALL_EMOJIS: readonly { token: string; keywords: readonly string[] }[] =
  EMOJI_GROUPS.flatMap((group) => group.emojis);
