"""PromQL offset and label_replace regressions  [#11322, #11321].

Both fixed in PR #11335: an instant query with `offset` returned nothing, and a
label generated by `label_replace` was not visible to an aggregation grouping by
it.

#13892 (mixed-case `__name__` selectors) is deliberately NOT covered here: it
only reproduces with `ZO_FORMAT_STREAM_NAME_TO_LOWERCASE=false`, which is not the
default, so on a stock server the name is lowercased at ingest and the selector
legitimately finds nothing. `tests/regression/test_promql_mixed_case_metric_name.py`
already covers the related #13926 -- though note that folder is excluded from the
integration run, so it never executes.
"""

import time
import uuid

import pytest

from support.wait import wait_until

SAMPLES = 6
SPACING_SEC = 30


@pytest.fixture(scope="module")
def seeded_metric(create_session, base_url, org_id):
    """A gauge sampled every 30s, ~20 minutes in the past, on two instances."""
    session = create_session
    metric = f"pytest_selector_{uuid.uuid4().hex[:6]}"
    t0 = (int(time.time()) // SPACING_SEC) * SPACING_SEC - 20 * 60

    payload = [
        {
            "__name__": metric,
            "__type__": "gauge",
            "job": "pytest_selectors",
            "instance": f"host{i % 2}",
            "_timestamp": (t0 + i * SPACING_SEC) * 1000,
            "value": float(i + 1),
        }
        for i in range(SAMPLES)
    ]
    resp = session.post(f"{base_url}api/{org_id}/ingest/metrics/_json", json=payload)
    assert resp.status_code == 200, f"metrics ingest failed: {resp.status_code} {resp.text[:400]}"

    def visible():
        r = session.get(
            f"{base_url}api/{org_id}/prometheus/api/v1/query",
            params={"query": f'{{__name__="{metric}"}}', "time": str(t0 + (SAMPLES - 1) * SPACING_SEC)},
        )
        return r.status_code == 200 and bool(r.json().get("data", {}).get("result"))

    wait_until(visible, timeout=120, interval=2,
               msg=f"metric {metric} never became queryable by __name__ selector")
    return metric, t0


def _instant(session, base_url, org_id, query, at):
    r = session.get(f"{base_url}api/{org_id}/prometheus/api/v1/query",
                    params={"query": query, "time": str(at)})
    assert r.status_code == 200, f"instant query failed: {r.status_code} {r.text[:300]}"
    body = r.json()
    assert body.get("status") == "success", body
    return body["data"]["result"]


def test_instant_query_with_offset_returns_the_earlier_sample(create_session, base_url, org_id, seeded_metric):
    """`offset` must shift the evaluation back, not return an empty result."""
    metric, t0 = seeded_metric
    at = t0 + (SAMPLES - 1) * SPACING_SEC

    now_res = _instant(create_session, base_url, org_id, f'{{__name__="{metric}"}}', at)
    off_res = _instant(create_session, base_url, org_id,
                       f'{{__name__="{metric}"}} offset {SPACING_SEC}s', at)

    assert off_res, f"offset query returned nothing (the defect); plain query returned {len(now_res)}"
    now_val = float(now_res[0]["value"][1])
    off_val = float(off_res[0]["value"][1])
    # Values ascend with time, so the offset sample must be strictly earlier/smaller.
    assert off_val < now_val, \
        f"offset must evaluate an earlier sample: offset={off_val} current={now_val}"


def test_label_replace_output_is_available_to_aggregation(create_session, base_url, org_id, seeded_metric):
    """A label generated by `label_replace` must be groupable by an aggregation."""
    metric, t0 = seeded_metric
    at = t0 + (SAMPLES - 1) * SPACING_SEC

    query = (
        f'sum by (derived) (label_replace({{__name__="{metric}"}}, '
        f'"derived", "$1", "instance", "(.*)"))'
    )
    result = _instant(create_session, base_url, org_id, query, at)
    assert result, "aggregation over a label_replace-generated label returned nothing"

    derived = {r["metric"].get("derived") for r in result}
    assert derived and all(d for d in derived), \
        f"the generated label must reach the aggregation output, got {derived}"
