// Copyright 2026 OpenObserve Inc.
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.

use axum::{
    Json,
    extract::{Path, Query},
    http::StatusCode,
    response::{IntoResponse, Response},
};
use config::utils::time::now_micros;
use infra::table::org_ai_toolsets::OrgToolset;
use o2_enterprise::enterprise::ai::toolsets::{
    ToolsetCreateRequest, ToolsetKind, ToolsetListResponse, ToolsetResponse, ToolsetUpdateRequest,
    validate_data,
};
use serde::Deserialize;

use crate::{
    common::{meta::http::HttpResponse as MetaHttpResponse, utils::auth::UserEmail},
    handler::http::extractors::Headers,
};

// ---------------------------------------------------------------------------
// Create
// ---------------------------------------------------------------------------

#[utoipa::path(
    post,
    path = "/{org_id}/ai/toolsets",
    context_path = "/api",
    tag = "AI",
    operation_id = "CreateAiToolset",
    summary = "Create an AI toolset",
    description = "Creates a new AI toolset (MCP server, CLI tool, skill, or generic config). \
                   The `data` field is encrypted at rest using per-org envelope encryption. \
                   Only available in enterprise deployments.",
    request_body(
        content = inline(ToolsetCreateRequest),
        description = "Toolset configuration",
        content_type = "application/json",
    ),
    responses(
        (status = 200, description = "Toolset created", content_type = "application/json"),
        (status = 400, description = "Invalid request", content_type = "application/json"),
        (status = 409, description = "Toolset with this name already exists", content_type = "application/json"),
    ),
    extensions(("x-o2-mcp" = json!({"enabled": false})))
)]
pub async fn create(
    Path(org_id): Path<String>,
    Headers(user_email): Headers<UserEmail>,
    Json(body): Json<ToolsetCreateRequest>,
) -> Response {
    if let Err(e) = validate_data(body.kind, &body.data) {
        return MetaHttpResponse::bad_request(e);
    }

    let data_str = body
        .data
        .as_ref()
        .map(|v| serde_json::to_string(v).unwrap());

    let now = now_micros();
    let entry = OrgToolset {
        id: String::new(), // generated by add()
        org: org_id.clone(),
        name: body.name.clone(),
        kind: body.kind.to_string(),
        description: body.description.clone(),
        data: data_str,
        created_by: user_email.user_id.clone(),
        created_at: now,
        updated_at: now,
    };

    match infra::table::org_ai_toolsets::add(entry).await {
        Ok(_) => {}
        Err(infra::errors::Error::DbError(infra::errors::DbError::UniqueViolation)) => {
            return MetaHttpResponse::conflict(format!(
                "toolset '{}' already exists in org '{}'",
                body.name, org_id
            ));
        }
        Err(e) => return MetaHttpResponse::internal_error(e),
    }

    // Fetch the saved record to get the generated id.
    let saved = match infra::table::org_ai_toolsets::get_by_name(&org_id, &body.name).await {
        Ok(Some(t)) => t,
        Ok(None) => return MetaHttpResponse::internal_error("toolset not found after insert"),
        Err(e) => return MetaHttpResponse::internal_error(e),
    };

    (StatusCode::OK, Json(toolset_to_response(saved))).into_response()
}

// ---------------------------------------------------------------------------
// Get
// ---------------------------------------------------------------------------

#[utoipa::path(
    get,
    path = "/{org_id}/ai/toolsets/{id}",
    context_path = "/api",
    tag = "AI",
    operation_id = "GetAiToolset",
    summary = "Get an AI toolset",
    description = "Retrieves a single AI toolset by its id. Only available in enterprise deployments.",
    params(
        ("org_id" = String, Path, description = "Organization name"),
        ("id" = String, Path, description = "Toolset id (KSUID)"),
    ),
    responses(
        (status = 200, description = "Toolset details", content_type = "application/json"),
        (status = 404, description = "Toolset not found", content_type = "application/json"),
        (status = 403, description = "Feature not supported", content_type = "application/json"),
    ),
    extensions(("x-o2-mcp" = json!({"enabled": false})))
)]
pub async fn get(Path(path): Path<(String, String)>) -> Response {
    let (org_id, id) = path;
    match infra::table::org_ai_toolsets::get(&org_id, &id).await {
        Ok(Some(t)) => Json(toolset_to_response(t)).into_response(),
        Ok(None) => MetaHttpResponse::not_found(format!("toolset '{id}' not found")),
        Err(e) => MetaHttpResponse::internal_error(e),
    }
}

// ---------------------------------------------------------------------------
// List
// ---------------------------------------------------------------------------

/// Query parameters accepted by the list endpoint.
#[derive(Debug, Default, Deserialize)]
pub struct ListQuery {
    /// Substring filter on the toolset name (case-insensitive `LIKE '%val%'`).
    pub name: Option<String>,
    /// Exact filter on the toolset kind (`mcp`, `cli`, `skill`, `generic`).
    pub kind: Option<String>,
    /// Maximum number of results to return.
    pub limit: Option<i64>,
}

#[utoipa::path(
    get,
    path = "/{org_id}/ai/toolsets",
    context_path = "/api",
    tag = "AI",
    operation_id = "ListAiToolsets",
    summary = "List AI toolsets",
    description = "Lists AI toolsets for the org with optional filtering. Only available in enterprise deployments.",
    params(
        ("org_id" = String, Path, description = "Organization name"),
        ("name"   = Option<String>, Query, description = "Substring filter on name (case-insensitive)"),
        ("kind"   = Option<String>, Query, description = "Exact filter on kind: mcp | cli | skill | generic"),
        ("limit"  = Option<i64>,   Query, description = "Maximum number of results"),
    ),
    responses(
        (status = 200, description = "List of toolsets", content_type = "application/json"),
        (status = 403, description = "Feature not supported", content_type = "application/json"),
    ),
    extensions(("x-o2-mcp" = json!({"enabled": false})))
)]
pub async fn list(Path(org_id): Path<String>, Query(params): Query<ListQuery>) -> Response {
    let filter = infra::table::org_ai_toolsets::ListFilter {
        name: params.name,
        kind: params.kind,
    };
    match infra::table::org_ai_toolsets::list(&org_id, filter, params.limit).await {
        Ok(toolsets) => {
            let res = ToolsetListResponse {
                toolsets: toolsets.into_iter().map(toolset_to_response).collect(),
            };
            Json(res).into_response()
        }
        Err(e) => MetaHttpResponse::internal_error(e),
    }
}

// ---------------------------------------------------------------------------
// Update
// ---------------------------------------------------------------------------

#[utoipa::path(
    put,
    path = "/{org_id}/ai/toolsets/{id}",
    context_path = "/api",
    tag = "AI",
    operation_id = "UpdateAiToolset",
    summary = "Update an AI toolset",
    description = "Updates the description and/or data of an existing AI toolset. \
                   When `data` is provided it fully replaces the existing config. \
                   Only available in enterprise deployments.",
    params(
        ("org_id" = String, Path, description = "Organization name"),
        ("id" = String, Path, description = "Toolset id (KSUID)"),
    ),
    request_body(
        content = inline(ToolsetUpdateRequest),
        description = "Fields to update",
        content_type = "application/json",
    ),
    responses(
        (status = 200, description = "Toolset updated", content_type = "application/json"),
        (status = 400, description = "Invalid request", content_type = "application/json"),
        (status = 404, description = "Toolset not found", content_type = "application/json"),
    ),
    extensions(("x-o2-mcp" = json!({"enabled": false})))
)]
pub async fn update(
    Path(path): Path<(String, String)>,
    Json(body): Json<ToolsetUpdateRequest>,
) -> Response {
    let (org_id, id) = path;

    let existing = match infra::table::org_ai_toolsets::get(&org_id, &id).await {
        Ok(Some(t)) => t,
        Ok(None) => return MetaHttpResponse::not_found(format!("toolset '{id}' not found")),
        Err(e) => return MetaHttpResponse::internal_error(e),
    };

    // Validate incoming data against the existing kind.
    if body.data.is_some()
        && let Ok(kind) = ToolsetKind::try_from(existing.kind.as_str())
        && let Err(e) = validate_data(kind, &body.data)
    {
        return MetaHttpResponse::bad_request(e);
    }

    let data_str = body
        .data
        .as_ref()
        .map(|v| serde_json::to_string(v).unwrap())
        .or(existing.data.clone());

    let updated = OrgToolset {
        id: existing.id.clone(),
        org: existing.org.clone(),
        name: existing.name.clone(),
        kind: existing.kind.clone(),
        description: body.description.or(existing.description),
        data: data_str,
        created_by: existing.created_by.clone(),
        created_at: existing.created_at,
        updated_at: now_micros(),
    };

    if let Err(e) = infra::table::org_ai_toolsets::update(updated.clone()).await {
        return MetaHttpResponse::internal_error(e);
    }

    Json(toolset_to_response(updated)).into_response()
}

// ---------------------------------------------------------------------------
// Delete
// ---------------------------------------------------------------------------

#[utoipa::path(
    delete,
    path = "/{org_id}/ai/toolsets/{id}",
    context_path = "/api",
    tag = "AI",
    operation_id = "DeleteAiToolset",
    summary = "Delete an AI toolset",
    description = "Permanently deletes an AI toolset. Only available in enterprise deployments.",
    params(
        ("org_id" = String, Path, description = "Organization name"),
        ("id" = String, Path, description = "Toolset id (KSUID)"),
    ),
    responses(
        (status = 200, description = "Toolset deleted", content_type = "application/json"),
        (status = 404, description = "Toolset not found", content_type = "application/json"),
        (status = 403, description = "Feature not supported", content_type = "application/json"),
    ),
    extensions(("x-o2-mcp" = json!({"enabled": false})))
)]
pub async fn delete(Path(path): Path<(String, String)>) -> Response {
    let (org_id, id) = path;

    // Verify existence before deleting.
    match infra::table::org_ai_toolsets::get(&org_id, &id).await {
        Ok(Some(_)) => {}
        Ok(None) => return MetaHttpResponse::not_found(format!("toolset '{id}' not found")),
        Err(e) => return MetaHttpResponse::internal_error(e),
    }

    if let Err(e) = infra::table::org_ai_toolsets::remove(&org_id, &id).await {
        return MetaHttpResponse::internal_error(e);
    }

    (
        StatusCode::OK,
        Json(MetaHttpResponse::message(
            StatusCode::OK,
            "toolset deleted successfully",
        )),
    )
        .into_response()
}

// ---------------------------------------------------------------------------
// Helper
// ---------------------------------------------------------------------------

fn toolset_to_response(t: OrgToolset) -> ToolsetResponse {
    let data = t
        .data
        .as_deref()
        .and_then(|s| match serde_json::from_str(s) {
            Ok(v) => Some(v),
            Err(e) => {
                log::warn!(
                    "toolset '{}' (id={}) has unreadable data: {e}",
                    t.name,
                    t.id
                );
                None
            }
        });
    ToolsetResponse {
        id: t.id,
        org: t.org,
        name: t.name,
        kind: ToolsetKind::try_from(t.kind.as_str()).unwrap_or(ToolsetKind::Generic),
        description: t.description,
        data,
        created_by: t.created_by,
        created_at: t.created_at,
        updated_at: t.updated_at,
    }
}
