# syntax=docker/dockerfile:1

FROM public.ecr.aws/debian/debian:bullseye-slim as runtime
RUN apt-get update && apt-get install -y --no-install-recommends ca-certificates curl htop iftop sysstat procps lsof net-tools
RUN update-ca-certificates
COPY ./bin/openobserve /
RUN ["/openobserve", "init-dir", "-p", "/data/"]
CMD ["/openobserve"]
