// Copyright 2026 OpenObserve Inc.
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.

// The proven v2 SQL (productAnalyticsProvenSql) with its chain windows replaced by the engine's sequence functions.
export const Q7_FUNNEL_SESSIONS = String.raw`WITH x00 AS (SELECT session_id AS sid, type AS ty, MIN(date) AS t, MIN(view_url) AS url, MIN(action_target_name) AS atn FROM "_rumdata" WHERE {scope} AND (type = 'view' OR (type = 'action' AND action_target_name <> '' AND {CK(action_target_name)} = 'menu-link-/logs-item')) GROUP BY session_id, type, CASE WHEN type = 'view' THEN view_id WHEN type = 'action' THEN COALESCE(action_id, CAST(date AS VARCHAR)) ELSE type END),
x0 AS (SELECT sid, t, ty, CASE WHEN ty = 'view' THEN {PK(url)} WHEN ty = 'action' THEN {CK(atn)} END AS k FROM x00 WHERE ty = 'action' OR (ty = 'view' AND (((strpos(url, '/web') > 0) AND {PK(url)} = '/web') OR ((strpos(url, '/web/logs') > 0) AND {PK(url)} = '/web/logs')))),
x1 AS (SELECT sid, t, ty, k, CASE WHEN ty = 'view' AND k = '/web' THEN 1 ELSE 0 END AS m1, CASE WHEN ty = 'action' AND k = 'menu-link-/logs-item' THEN 1 ELSE 0 END AS m2, CASE WHEN ty = 'view' AND k = '/web/logs' THEN 1 ELSE 0 END AS m3, CAST(NULL AS VARCHAR) AS uid FROM x0),
s AS (SELECT sid, MAX(uid) AS uid, sequence_step_times(0, t, m1 = 1, m2 = 1, m3 = 1) AS f, SUM(m1) AS seen1, SUM(m2) AS seen2, SUM(m3) AS seen3 FROM x1 GROUP BY sid),
ps AS (SELECT sid, uid, CASE WHEN f[1] IS NOT NULL THEN 1 ELSE 0 END AS r1, CASE WHEN f[2] IS NOT NULL THEN 1 ELSE 0 END AS r2, CASE WHEN f[3] IS NOT NULL THEN 1 ELSE 0 END AS r3, f[2] AS d2, f[3] AS d3, seen1, seen2, seen3 FROM s)
SELECT SUM(r1) AS c1, SUM(r2) AS c2, SUM(r3) AS c3, SUM(seen1) AS seen1, SUM(seen2) AS seen2, SUM(seen3) AS seen3, approx_percentile_cont(d2, 0.5) AS med2, approx_percentile_cont(d2, 0.9) AS p90_2, approx_percentile_cont(d3, 0.5) AS med3, approx_percentile_cont(d3, 0.9) AS p90_3 FROM ps LIMIT 1`;

export const Q7_FUNNEL_USERS_7D = String.raw`WITH x00 AS (SELECT session_id AS sid, type AS ty, MIN(date) AS t, MIN(view_url) AS url, MIN(action_target_name) AS atn, first_value(NULLIF(usr_email, '') ORDER BY CASE WHEN NULLIF(usr_email, '') IS NULL THEN 1 ELSE 0 END, date) AS u0, MIN(CASE WHEN NULLIF(usr_email, '') IS NOT NULL THEN date END) AS ut FROM "_rumdata" WHERE {scope} AND (type = 'view' OR (type = 'action' AND action_target_name <> '' AND {CK(action_target_name)} = 'menu-link-/logs-item') OR NULLIF(usr_email, '') IS NOT NULL) GROUP BY session_id, type, CASE WHEN type = 'view' THEN view_id WHEN type = 'action' THEN COALESCE(action_id, CAST(date AS VARCHAR)) ELSE type END),
x0 AS (SELECT sid, t, ty, CASE WHEN ty = 'view' THEN {PK(url)} WHEN ty = 'action' THEN {CK(atn)} END AS k, u0, ut FROM x00 WHERE ty = 'action' OR (ty = 'view' AND (((strpos(url, '/web') > 0) AND {PK(url)} = '/web') OR ((strpos(url, '/web/logs') > 0) AND {PK(url)} = '/web/logs'))) OR u0 IS NOT NULL),
x1 AS (SELECT sid, t, ty, k, CASE WHEN ty = 'view' AND k = '/web' THEN 1 ELSE 0 END AS m1, CASE WHEN ty = 'action' AND k = 'menu-link-/logs-item' THEN 1 ELSE 0 END AS m2, CASE WHEN ty = 'view' AND k = '/web/logs' THEN 1 ELSE 0 END AS m3, FIRST_VALUE(u0) OVER (PARTITION BY sid ORDER BY CASE WHEN u0 IS NULL THEN 1 ELSE 0 END, ut) AS uid FROM x0),
x2 AS (SELECT sid, t, ty, k, m1, m2, m3, uid FROM x1 WHERE m1 = 1 OR m2 = 1 OR m3 = 1),
su AS (SELECT CASE WHEN uid IS NULL THEN 1 ELSE 0 END AS anon, sequence_step_times(604800000, t, m1 = 1, m2 = 1, m3 = 1) AS f, SUM(m1) AS seen1, SUM(m2) AS seen2, SUM(m3) AS seen3, COUNT(DISTINCT CASE WHEN m1 = 1 THEN sid END) AS s1s FROM x2 GROUP BY COALESCE(uid, 's:' || sid), CASE WHEN uid IS NULL THEN 1 ELSE 0 END),
pu AS (SELECT anon, CASE WHEN f[1] IS NOT NULL THEN 1 ELSE 0 END AS r1, CASE WHEN f[2] IS NOT NULL THEN 1 ELSE 0 END AS r2, CASE WHEN f[3] IS NOT NULL THEN 1 ELSE 0 END AS r3, f[2] AS d2, f[3] AS d3, seen1, seen2, seen3, s1s FROM su)
SELECT SUM(CASE WHEN anon = 0 THEN r1 ELSE 0 END) AS c1, SUM(CASE WHEN anon = 0 THEN r2 ELSE 0 END) AS c2, SUM(CASE WHEN anon = 0 THEN r3 ELSE 0 END) AS c3, SUM(seen1) AS seen1, SUM(seen2) AS seen2, SUM(seen3) AS seen3, SUM(s1s) AS s1_sessions, SUM(CASE WHEN anon = 1 THEN s1s ELSE 0 END) AS left_out, approx_percentile_cont(CASE WHEN anon = 0 THEN d2 END, 0.5) AS med2, approx_percentile_cont(CASE WHEN anon = 0 THEN d2 END, 0.9) AS p90_2, approx_percentile_cont(CASE WHEN anon = 0 THEN d3 END, 0.5) AS med3, approx_percentile_cont(CASE WHEN anon = 0 THEN d3 END, 0.9) AS p90_3 FROM pu LIMIT 1`;

export const Q7_FUNNEL_BREAKDOWN = String.raw`WITH x00 AS (SELECT session_id AS sid, type AS ty, MIN(date) AS t, MIN(view_url) AS url, MIN(action_target_name) AS atn, MIN(user_agent_user_agent_family) AS dim FROM "_rumdata" WHERE {scope} AND (type = 'view' OR (type = 'action' AND action_target_name <> '' AND {CK(action_target_name)} = 'menu-link-/logs-item')) GROUP BY session_id, type, CASE WHEN type = 'view' THEN view_id WHEN type = 'action' THEN COALESCE(action_id, CAST(date AS VARCHAR)) ELSE type END),
x0 AS (SELECT sid, t, ty, CASE WHEN ty = 'view' THEN {PK(url)} WHEN ty = 'action' THEN {CK(atn)} END AS k, dim FROM x00 WHERE ty = 'action' OR (ty = 'view' AND (((strpos(url, '/web') > 0) AND {PK(url)} = '/web') OR ((strpos(url, '/web/logs') > 0) AND {PK(url)} = '/web/logs')))),
x1 AS (SELECT sid, t, ty, k, dim, CASE WHEN ty = 'view' AND k = '/web' THEN 1 ELSE 0 END AS m1, CASE WHEN ty = 'action' AND k = 'menu-link-/logs-item' THEN 1 ELSE 0 END AS m2, CASE WHEN ty = 'view' AND k = '/web/logs' THEN 1 ELSE 0 END AS m3, CAST(NULL AS VARCHAR) AS uid FROM x0),
s AS (SELECT sid, MAX(uid) AS uid, sequence_step_times(0, t, m1 = 1, m2 = 1, m3 = 1) AS f, SUM(m1) AS seen1, SUM(m2) AS seen2, SUM(m3) AS seen3, first_value(dim ORDER BY CASE WHEN m1 = 1 THEN 0 ELSE 1 END, t) AS dim, MIN(CASE WHEN m1 = 1 THEN t END) AS t1 FROM x1 GROUP BY sid),
ps AS (SELECT sid, uid, CASE WHEN f[1] IS NOT NULL THEN 1 ELSE 0 END AS r1, CASE WHEN f[2] IS NOT NULL THEN 1 ELSE 0 END AS r2, CASE WHEN f[3] IS NOT NULL THEN 1 ELSE 0 END AS r3, f[2] AS d2, f[3] AS d3, seen1, seen2, seen3, dim, t1 FROM s)
SELECT dim, SUM(r1) AS c1, SUM(r2) AS c2, SUM(r3) AS c3 FROM ps GROUP BY dim ORDER BY c1 DESC LIMIT 1000`;

export const Q7_PANEL = String.raw`WITH x00 AS (SELECT session_id AS sid, type AS ty, MIN(date) AS t, MIN(view_url) AS url, MIN(action_target_name) AS atn FROM "_rumdata" WHERE {scope} AND (type = 'view' OR (type = 'action' AND action_target_name <> '' AND {CK(action_target_name)} = 'menu-link-/logs-item')) GROUP BY session_id, type, CASE WHEN type = 'view' THEN view_id WHEN type = 'action' THEN COALESCE(action_id, CAST(date AS VARCHAR)) ELSE type END),
x0 AS (SELECT sid, t, ty, CASE WHEN ty = 'view' THEN {PK(url)} WHEN ty = 'action' THEN {CK(atn)} END AS k FROM x00 WHERE ty = 'action' OR (ty = 'view' AND (((strpos(url, '/web') > 0) AND {PK(url)} = '/web') OR ((strpos(url, '/web/logs') > 0) AND {PK(url)} = '/web/logs')))),
x1 AS (SELECT sid, t, ty, k, CASE WHEN ty = 'view' AND k = '/web' THEN 1 ELSE 0 END AS m1, CASE WHEN ty = 'action' AND k = 'menu-link-/logs-item' THEN 1 ELSE 0 END AS m2, CASE WHEN ty = 'view' AND k = '/web/logs' THEN 1 ELSE 0 END AS m3, CAST(NULL AS VARCHAR) AS uid FROM x0),
s AS (SELECT sid, MAX(uid) AS uid, sequence_step_times(0, t, m1 = 1, m2 = 1, m3 = 1) AS f, SUM(m1) AS seen1, SUM(m2) AS seen2, SUM(m3) AS seen3 FROM x1 GROUP BY sid),
ps AS (SELECT sid, uid, CASE WHEN f[1] IS NOT NULL THEN 1 ELSE 0 END AS r1, CASE WHEN f[2] IS NOT NULL THEN 1 ELSE 0 END AS r2, CASE WHEN f[3] IS NOT NULL THEN 1 ELSE 0 END AS r3, f[2] AS d2, f[3] AS d3, seen1, seen2, seen3 FROM s),
fin AS (SELECT SUM(r1) AS c1, SUM(r2) AS c2, SUM(r3) AS c3, SUM(seen1) AS seen1, SUM(seen2) AS seen2, SUM(seen3) AS seen3 FROM ps)
SELECT unnest(make_array('1. /web', '2. menu-link-/logs-item', '3. /web/logs')) AS x_axis_1, unnest(make_array(c1, c2, c3)) AS y_axis_1 FROM fin`;

export const Q8_NEXT_STEPS = String.raw`WITH x00 AS (SELECT session_id AS sid, type AS ty, MIN(date) AS t, MIN(view_url) AS url, MIN(action_target_name) AS atn, MAX(CASE WHEN session_has_replay IS NOT NULL THEN 1 ELSE 0 END) AS hr FROM "_rumdata" WHERE {scope} AND (type IN ('view') OR (type = 'action' AND action_target_name <> '')) GROUP BY session_id, type, CASE WHEN type = 'view' THEN view_id WHEN type = 'action' THEN COALESCE(action_id, CAST(date AS VARCHAR)) WHEN type = 'error' THEN CAST(date AS VARCHAR) ELSE type END),
x0 AS (SELECT sid, ty, t, hr, CASE WHEN ty = 'view' THEN {PK(url)} WHEN ty = 'action' THEN {CK(atn)} END AS k FROM x00 WHERE ty IN ('view', 'action', 'error')),
x1 AS (SELECT sid, ty, t, hr, k, CASE WHEN ty = 'view' AND k = '/web' THEN 1 ELSE 0 END AS m1, CASE WHEN ty = 'action' AND k = 'menu-link-/logs-item' THEN 1 ELSE 0 END AS m2, CASE WHEN ty = 'view' AND k = '/web/logs' THEN 1 ELSE 0 END AS m3, CAST(NULL AS VARCHAR) AS uid FROM x0),
x2 AS (SELECT * FROM (SELECT *, MAX(m1) OVER (PARTITION BY sid) AS h1 FROM x1) q WHERE h1 = 1 AND ty IN ('view', 'action', 'error')),
w AS (SELECT *, sequence_depth(0, t, m1 = 1, m2 = 1, m3 = 1) OVER (PARTITION BY sid) AS wr, sequence_step_match(0, 3, t, m1 = 1, m2 = 1, m3 = 1) OVER (PARTITION BY sid) AS wv FROM x2),
v AS (SELECT *, CASE WHEN wv THEN 1 ELSE 0 END AS v3 FROM w),
r AS (SELECT *, MIN(CASE WHEN v3 = 1 THEN t END) OVER (PARTITION BY sid) AS tk, substr(MIN(CASE WHEN v3 = 1 THEN CAST(t AS VARCHAR) || sid END) OVER (PARTITION BY sid), 14) AS sk, MAX(v3) OVER (PARTITION BY sid) AS rk FROM v WHERE sid IS NOT NULL),
nu0 AS (SELECT sid AS unit, MIN(CASE WHEN sid = sk AND t > tk AND ty IN ('view', 'action') AND k IS NOT NULL AND NOT (ty = 'view' AND k = '/web/logs') THEN CAST(t AS VARCHAR) || CASE WHEN ty = 'view' THEN 'p' ELSE 'c' END || k END) AS nx FROM r WHERE rk = 1 GROUP BY sid),
nu AS (SELECT unit, CASE substr(nx, 14, 1) WHEN 'p' THEN 'view' WHEN 'c' THEN 'action' END AS nty, substr(nx, 15) AS nk FROM nu0)
SELECT CASE WHEN nty IS NULL THEN 0 ELSE 1 END AS is_next, CASE WHEN nty = 'view' THEN 'p' WHEN nty = 'action' THEN 'c' END AS kind, nk AS k, COUNT(*) AS units FROM nu WHERE nty IS NOT NULL GROUP BY nty, nk ORDER BY units DESC, k LIMIT 5`;

export const Q11_DROPOFF_NEXT_USERS_7D = String.raw`WITH x00 AS (SELECT session_id AS sid, type AS ty, MIN(date) AS t, MIN(view_url) AS url, MIN(action_target_name) AS atn, MAX(CASE WHEN session_has_replay IS NOT NULL THEN 1 ELSE 0 END) AS hr, first_value(NULLIF(usr_email, '') ORDER BY CASE WHEN NULLIF(usr_email, '') IS NULL THEN 1 ELSE 0 END, date) AS u0, MIN(CASE WHEN NULLIF(usr_email, '') IS NOT NULL THEN date END) AS ut FROM "_rumdata" WHERE {scope} AND (type IN ('view') OR (type = 'action' AND action_target_name <> '') OR NULLIF(usr_email, '') IS NOT NULL) GROUP BY session_id, type, CASE WHEN type = 'view' THEN view_id WHEN type = 'action' THEN COALESCE(action_id, CAST(date AS VARCHAR)) WHEN type = 'error' THEN CAST(date AS VARCHAR) ELSE type END),
x0 AS (SELECT sid, ty, t, hr, u0, ut, CASE WHEN ty = 'view' THEN {PK(url)} WHEN ty = 'action' THEN {CK(atn)} END AS k FROM x00),
x1 AS (SELECT sid, ty, t, hr, k, CASE WHEN ty = 'view' AND k = '/web' THEN 1 ELSE 0 END AS m1, CASE WHEN ty = 'action' AND k = 'menu-link-/logs-item' THEN 1 ELSE 0 END AS m2, CASE WHEN ty = 'view' AND k = '/web/logs' THEN 1 ELSE 0 END AS m3, FIRST_VALUE(u0) OVER (PARTITION BY sid ORDER BY CASE WHEN u0 IS NULL THEN 1 ELSE 0 END, ut) AS uid FROM x0),
x2 AS (SELECT * FROM (SELECT *, MAX(m1) OVER (PARTITION BY COALESCE(uid, 's:' || sid)) AS h1 FROM x1) q WHERE h1 = 1 AND ty IN ('view', 'action', 'error')),
w AS (SELECT *, sequence_depth(604800000, t, m1 = 1, m2 = 1, m3 = 1) OVER (PARTITION BY COALESCE(uid, 's:' || sid)) AS wr, sequence_step_match(604800000, 1, t, m1 = 1, m2 = 1, m3 = 1) OVER (PARTITION BY COALESCE(uid, 's:' || sid)) AS wv FROM x2),
v AS (SELECT *, CASE WHEN wv THEN 1 ELSE 0 END AS v1, CASE WHEN wr >= 2 THEN 1 ELSE 0 END AS v2 FROM w),
r AS (SELECT *, MIN(CASE WHEN v1 = 1 THEN t END) OVER (PARTITION BY uid) AS tk, substr(MIN(CASE WHEN v1 = 1 THEN CAST(t AS VARCHAR) || sid END) OVER (PARTITION BY uid), 14) AS sk, MAX(v1) OVER (PARTITION BY uid) AS rk, MAX(v2) OVER (PARTITION BY uid) AS rk1 FROM v WHERE uid IS NOT NULL),
nu0 AS (SELECT uid AS unit, MIN(CASE WHEN sid = sk AND t > tk AND ty IN ('view', 'action') AND k IS NOT NULL AND NOT (ty = 'view' AND k = '/web') THEN CAST(t AS VARCHAR) || CASE WHEN ty = 'view' THEN 'p' ELSE 'c' END || k END) AS nx FROM r WHERE rk = 1 AND rk1 = 0 GROUP BY uid),
nu AS (SELECT unit, CASE substr(nx, 14, 1) WHEN 'p' THEN 'view' WHEN 'c' THEN 'action' END AS nty, substr(nx, 15) AS nk FROM nu0)
SELECT CASE WHEN nty IS NULL THEN 0 ELSE 1 END AS is_next, CASE WHEN nty = 'view' THEN 'p' WHEN nty = 'action' THEN 'c' END AS kind, nk AS k, COUNT(*) AS units FROM nu GROUP BY nty, nk ORDER BY is_next, units DESC, k LIMIT 6`;

export const Q12_HEALTH_SESSIONS = String.raw`WITH x00 AS (SELECT session_id AS sid, type AS ty, MIN(date) AS t, MIN(view_url) AS url, MIN(action_target_name) AS atn, MAX(CASE WHEN session_has_replay IS NOT NULL THEN 1 ELSE 0 END) AS hr FROM "_rumdata" WHERE {scope} AND (type IN ('view', 'error') OR (type = 'action' AND action_target_name <> '')) GROUP BY session_id, type, CASE WHEN type = 'view' THEN view_id WHEN type = 'action' THEN COALESCE(action_id, CAST(date AS VARCHAR)) WHEN type = 'error' THEN CAST(date AS VARCHAR) ELSE type END),
x0 AS (SELECT sid, ty, t, hr, CASE WHEN ty = 'view' THEN {PK(url)} WHEN ty = 'action' THEN {CK(atn)} END AS k FROM x00 WHERE ty IN ('view', 'action', 'error')),
x1 AS (SELECT sid, ty, t, hr, k, CASE WHEN ty = 'view' AND k = '/web' THEN 1 ELSE 0 END AS m1, CASE WHEN ty = 'action' AND k = 'menu-link-/logs-item' THEN 1 ELSE 0 END AS m2, CASE WHEN ty = 'view' AND k = '/web/logs' THEN 1 ELSE 0 END AS m3, CAST(NULL AS VARCHAR) AS uid FROM x0),
x2 AS (SELECT * FROM (SELECT *, MAX(m1) OVER (PARTITION BY sid) AS h1 FROM x1) q WHERE h1 = 1 AND ty IN ('view', 'action', 'error')),
w AS (SELECT *, sequence_depth(0, t, m1 = 1, m2 = 1, m3 = 1) OVER (PARTITION BY sid) AS wr, sequence_step_match(0, 1, t, m1 = 1, m2 = 1, m3 = 1) OVER (PARTITION BY sid) AS wv FROM x2),
v AS (SELECT *, CASE WHEN wv THEN 1 ELSE 0 END AS v1, CASE WHEN wr >= 2 THEN 1 ELSE 0 END AS v2 FROM w),
r AS (SELECT *, MIN(CASE WHEN v1 = 1 THEN t END) OVER (PARTITION BY sid) AS tk, substr(MIN(CASE WHEN v1 = 1 THEN CAST(t AS VARCHAR) || sid END) OVER (PARTITION BY sid), 14) AS sk, MAX(v1) OVER (PARTITION BY sid) AS rk, MAX(v2) OVER (PARTITION BY sid) AS rk1 FROM v WHERE sid IS NOT NULL),
hu AS (SELECT sid AS unit, MAX(rk1) AS conv, MAX(CASE WHEN ty = 'error' AND sid = sk AND t >= tk THEN 1 ELSE 0 END) AS e, COUNT(DISTINCT CASE WHEN v1 = 1 THEN sid END) AS s FROM r WHERE rk = 1 GROUP BY sid)
SELECT CASE WHEN conv = 1 THEN 'converted' ELSE 'dropped' END AS side, COUNT(*) AS units, SUM(s) AS sessions, SUM(e) AS with_error, 0 AS with_frustration FROM hu GROUP BY conv ORDER BY side LIMIT 2`;

export const Q13_COHORT_SESSIONS = String.raw`WITH x00 AS (SELECT session_id AS sid, type AS ty, MIN(date) AS t, MIN(view_url) AS url, MIN(action_target_name) AS atn, MAX(CASE WHEN session_has_replay IS NOT NULL THEN 1 ELSE 0 END) AS hr, first_value(NULLIF(usr_email, '') ORDER BY CASE WHEN NULLIF(usr_email, '') IS NULL THEN 1 ELSE 0 END, date) AS u0, MIN(CASE WHEN NULLIF(usr_email, '') IS NOT NULL THEN date END) AS ut FROM "_rumdata" WHERE {scope} AND (type IN ('view', 'error') OR (type = 'action' AND action_target_name <> '') OR NULLIF(usr_email, '') IS NOT NULL) GROUP BY session_id, type, CASE WHEN type = 'view' THEN view_id WHEN type = 'action' THEN COALESCE(action_id, CAST(date AS VARCHAR)) WHEN type = 'error' THEN CAST(date AS VARCHAR) ELSE type END),
x0 AS (SELECT sid, ty, t, hr, u0, ut, CASE WHEN ty = 'view' THEN {PK(url)} WHEN ty = 'action' THEN {CK(atn)} END AS k FROM x00),
x1 AS (SELECT sid, ty, t, hr, k, CASE WHEN ty = 'view' AND k = '/web' THEN 1 ELSE 0 END AS m1, CASE WHEN ty = 'action' AND k = 'menu-link-/logs-item' THEN 1 ELSE 0 END AS m2, CASE WHEN ty = 'view' AND k = '/web/logs' THEN 1 ELSE 0 END AS m3, FIRST_VALUE(u0) OVER (PARTITION BY sid ORDER BY CASE WHEN u0 IS NULL THEN 1 ELSE 0 END, ut) AS uid FROM x0),
x2 AS (SELECT * FROM (SELECT *, MAX(m1) OVER (PARTITION BY sid) AS h1 FROM x1) q WHERE h1 = 1 AND ty IN ('view', 'action', 'error')),
w AS (SELECT *, sequence_depth(0, t, m1 = 1, m2 = 1, m3 = 1) OVER (PARTITION BY sid) AS wr, sequence_step_match(0, 1, t, m1 = 1, m2 = 1, m3 = 1) OVER (PARTITION BY sid) AS wv FROM x2),
v AS (SELECT *, CASE WHEN wv THEN 1 ELSE 0 END AS v1, CASE WHEN wr >= 2 THEN 1 ELSE 0 END AS v2 FROM w),
r AS (SELECT *, MIN(CASE WHEN v1 = 1 THEN t END) OVER (PARTITION BY sid) AS tk, substr(MIN(CASE WHEN v1 = 1 THEN CAST(t AS VARCHAR) || sid END) OVER (PARTITION BY sid), 14) AS sk, MAX(v1) OVER (PARTITION BY sid) AS rk, MAX(v2) OVER (PARTITION BY sid) AS rk1 FROM v WHERE sid IS NOT NULL),
cs AS (SELECT sid, MIN(CASE WHEN v1 = 1 THEN t END) AS step_t, SUM(CASE WHEN ty = 'error' THEN 1 ELSE 0 END) AS errors, 0 AS frustrations, MAX(hr) AS has_replay, MIN(t) AS started, MAX(t) AS ended, MAX(uid) AS user_label FROM r WHERE rk = 1 AND rk1 = 0 GROUP BY sid)
SELECT sid, step_t, errors, frustrations, has_replay, started, ended, user_label, COUNT(*) OVER () AS total FROM cs WHERE step_t IS NOT NULL ORDER BY has_replay DESC, step_t DESC, sid LIMIT 200 OFFSET 0`;
