name: Enterprise Build Callback

on:
  repository_dispatch:
    types: [enterprise-build-complete]

jobs:
  handle-enterprise-completion:
    runs-on: ubuntu-latest

    steps:

      - name: Check enterprise build result
        env:
          CONCLUSION: ${{ github.event.client_payload.conclusion }}
          RUN_URL: ${{ github.event.client_payload.run_url }}
        run: |
          echo "Enterprise build completed with: $CONCLUSION"
          echo "Build URL: $RUN_URL"

          if [ "$CONCLUSION" = "success" ]; then
            echo "✅ Enterprise build passed"
          else
            echo "❌ Enterprise build failed"
            exit 1
          fi